Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.datosBancariosObligatorios','Para aprobar una solicitud debe rellenar los datos bancarios','0','1',to_date('20/06/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.datosBancariosObligatorios','Per aprovar una sol·licitud d''emplenar les dades bancàries','0','2',to_date('20/06/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.datosBancariosObligatorios','Para aprobar una solicitud debe rellenar los datos bancarios#EU','0','3',to_date('20/06/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.datosBancariosObligatorios','Para aprobar una solicitud debe rellenar los datos bancarios#GL','0','4',to_date('20/06/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.revisionServiciosyFacturasCuentas','Se van a revisar los servicios y facturas pendientes para asignar una cuenta en lugar de esta','0','1',to_date('20/06/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.revisionServiciosyFacturasCuentas','Es van a revisar les serveis i factures pendents per a assignar un compte en lloc d''aquesta','0','2',to_date('20/06/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.revisionServiciosyFacturasCuentas','Se van a revisar los servicios y facturas pendientes para asignar una cuenta en lugar de esta#EU','0','3',to_date('20/06/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.revisionServiciosyFacturasCuentas','Se van a revisar los servicios y facturas pendientes para asignar una cuenta en lugar de esta#GL','0','4',to_date('20/06/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.preguntaRevisionServiciosyFacturasCuentas','¿Quiere revisar las suscripciones y facturas para asignarlas según corresponda a esta cuenta?','0','1',to_date('20/06/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.preguntaRevisionServiciosyFacturasCuentas','Vol revisar les subscripcions i factures per assignar-les segons correspongui a aquest compte?','0','2',to_date('20/06/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.preguntaRevisionServiciosyFacturasCuentas','¿Quiere revisar las suscripciones y facturas para asignarlas según corresponda a esta cuenta?#EU','0','3',to_date('20/06/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.preguntaRevisionServiciosyFacturasCuentas','¿Quiere revisar las suscripciones y facturas para asignarlas según corresponda a esta cuenta?#GL','0','4',to_date('20/06/12','DD/MM/RR'),'0','19');
