Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.fichaColegial.datosGenerales.literal.numDocumentoExistente.noColegiado','El nuevo número de identificación introducido ya existe en el sistema. Cree otro registro de no colegiado con el nuevo número de identificación, o bien contacte con el administrador','0','1',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.fichaColegial.datosGenerales.literal.numDocumentoExistente.noColegiado','El nou número d''identificació introduït ja existeix al sistema. Creu altre registre de no col·legiat amb el nou Número d''identificació, o bé contacti amb l''administrador','0','2',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.fichaColegial.datosGenerales.literal.numDocumentoExistente.noColegiado','El nuevo número de identificación introducido ya existe en el sistema. Cree otro registro de no colegiado con el nuevo número de identificación, o bien contacte con el administrador#GL','0','4',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.fichaColegial.datosGenerales.literal.numDocumentoExistente.noColegiado','El nuevo número de identificación introducido ya existe en el sistema. Cree otro registro de no colegiado con el nuevo número de identificación, o bien contacte con el administrador#EU','0','3',to_date('25/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.fichaColegial.datosGenerales.literal.numDocumentoExistente.colegiado','El nuevo número de identificación introducido ya existe en el sistema. Cree otro registro de colegiado con el nuevo número de identificación, o bien contacte con el administrador','0','1',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.fichaColegial.datosGenerales.literal.numDocumentoExistente.colegiado','El nou número d''identificació introduït ja existeix al sistema. Creu altre registre de col·legiat amb el nou número d''identificació, o bé contacti amb l''administrador','0','2',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.fichaColegial.datosGenerales.literal.numDocumentoExistente.colegiado','El nuevo número de identificación introducido ya existe en el sistema. Cree otro registro de colegiado con el nuevo número de identificación, o bien contacte con el administrador#GL','0','4',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.fichaColegial.datosGenerales.literal.numDocumentoExistente.colegiado','El nuevo número de identificación introducido ya existe en el sistema. Cree otro registro de colegiado con el nuevo número de identificación, o bien contacte con el administrador#EU','0','3',to_date('25/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.censo.fichaNoColegial','Ficha No Colegiado','0','1',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.censo.fichaNoColegial','Fitxa No Col·legiat','0','2',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.censo.fichaNoColegial','Ficha No Colegiado#GL','0','4',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.censo.fichaNoColegial','Ficha No Colegiado#EU','0','3',to_date('25/03/19','DD/MM/RR'),'0','19');

ALTER TABLE CEN_SOLICITUDINCORPORACION ADD FECHAESTADOSOLICITUD DATE;
COMMIT;