package org.itcgae.siga.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.AdmTiposaccesoHistorico;
import org.itcgae.siga.db.entities.AdmTiposaccesoHistoricoExample;

public interface AdmTiposaccesoHistoricoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.ADM_TIPOSACCESO_HISTORICO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@SelectProvider(type = AdmTiposaccesoHistoricoSqlProvider.class, method = "countByExample")
	long countByExample(AdmTiposaccesoHistoricoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.ADM_TIPOSACCESO_HISTORICO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@DeleteProvider(type = AdmTiposaccesoHistoricoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(AdmTiposaccesoHistoricoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.ADM_TIPOSACCESO_HISTORICO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Insert({ "insert into ADM_TIPOSACCESO_HISTORICO (IDPROCESO, IDPERFIL, ", "FECHAMODIFICACION, USUMODIFICACION, ",
			"DERECHOACCESO, IDINSTITUCION, ", "USUELIMINACION, FECHAELIMINACION)",
			"values (#{idproceso,jdbcType=VARCHAR}, #{idperfil,jdbcType=VARCHAR}, ",
			"#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL}, ",
			"#{derechoacceso,jdbcType=DECIMAL}, #{idinstitucion,jdbcType=DECIMAL}, ",
			"#{usueliminacion,jdbcType=DECIMAL}, #{fechaeliminacion,jdbcType=TIMESTAMP})" })
	int insert(AdmTiposaccesoHistorico record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.ADM_TIPOSACCESO_HISTORICO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@InsertProvider(type = AdmTiposaccesoHistoricoSqlProvider.class, method = "insertSelective")
	int insertSelective(AdmTiposaccesoHistorico record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.ADM_TIPOSACCESO_HISTORICO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@SelectProvider(type = AdmTiposaccesoHistoricoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "IDPROCESO", property = "idproceso", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IDPERFIL", property = "idperfil", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DERECHOACCESO", property = "derechoacceso", jdbcType = JdbcType.DECIMAL),
			@Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "USUELIMINACION", property = "usueliminacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "FECHAELIMINACION", property = "fechaeliminacion", jdbcType = JdbcType.TIMESTAMP) })
	List<AdmTiposaccesoHistorico> selectByExample(AdmTiposaccesoHistoricoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.ADM_TIPOSACCESO_HISTORICO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = AdmTiposaccesoHistoricoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") AdmTiposaccesoHistorico record,
			@Param("example") AdmTiposaccesoHistoricoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.ADM_TIPOSACCESO_HISTORICO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = AdmTiposaccesoHistoricoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") AdmTiposaccesoHistorico record,
			@Param("example") AdmTiposaccesoHistoricoExample example);
}