package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.CenAcCliente;
import org.itcgae.siga.db.entities.CenAcClienteExample;

public interface CenAcClienteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@SelectProvider(type = CenAcClienteSqlProvider.class, method = "countByExample")
	long countByExample(CenAcClienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@DeleteProvider(type = CenAcClienteSqlProvider.class, method = "deleteByExample")
	int deleteByExample(CenAcClienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Delete({ "delete from CEN_AC_CLIENTE", "where IDCENACCLIENTE = #{idcenaccliente,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Integer idcenaccliente);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Insert({ "insert into CEN_AC_CLIENTE (IDCENACCLIENTE, IDCENACSERVICIO, ", "NOMBRE, ACTIVO, ",
			"CODIDIOMA, USUMODIFICACION, ", "FECHAMODIFICACION)",
			"values (#{idcenaccliente,jdbcType=DECIMAL}, #{idcenacservicio,jdbcType=DECIMAL}, ",
			"#{nombre,jdbcType=VARCHAR}, #{activo,jdbcType=DECIMAL}, ",
			"#{codidioma,jdbcType=VARCHAR}, #{usumodificacion,jdbcType=DECIMAL}, ",
			"#{fechamodificacion,jdbcType=TIMESTAMP})" })
	int insert(CenAcCliente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@InsertProvider(type = CenAcClienteSqlProvider.class, method = "insertSelective")
	int insertSelective(CenAcCliente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@SelectProvider(type = CenAcClienteSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "IDCENACCLIENTE", property = "idcenaccliente", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDCENACSERVICIO", property = "idcenacservicio", jdbcType = JdbcType.DECIMAL),
			@Result(column = "NOMBRE", property = "nombre", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ACTIVO", property = "activo", jdbcType = JdbcType.DECIMAL),
			@Result(column = "CODIDIOMA", property = "codidioma", jdbcType = JdbcType.VARCHAR),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP) })
	List<CenAcCliente> selectByExample(CenAcClienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Select({ "select", "IDCENACCLIENTE, IDCENACSERVICIO, NOMBRE, ACTIVO, CODIDIOMA, USUMODIFICACION, ",
			"FECHAMODIFICACION", "from CEN_AC_CLIENTE", "where IDCENACCLIENTE = #{idcenaccliente,jdbcType=DECIMAL}" })
	@Results({ @Result(column = "IDCENACCLIENTE", property = "idcenaccliente", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDCENACSERVICIO", property = "idcenacservicio", jdbcType = JdbcType.DECIMAL),
			@Result(column = "NOMBRE", property = "nombre", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ACTIVO", property = "activo", jdbcType = JdbcType.DECIMAL),
			@Result(column = "CODIDIOMA", property = "codidioma", jdbcType = JdbcType.VARCHAR),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP) })
	CenAcCliente selectByPrimaryKey(Integer idcenaccliente);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenAcClienteSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") CenAcCliente record, @Param("example") CenAcClienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenAcClienteSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") CenAcCliente record, @Param("example") CenAcClienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenAcClienteSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(CenAcCliente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_AC_CLIENTE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Update({ "update CEN_AC_CLIENTE", "set IDCENACSERVICIO = #{idcenacservicio,jdbcType=DECIMAL},",
			"NOMBRE = #{nombre,jdbcType=VARCHAR},", "ACTIVO = #{activo,jdbcType=DECIMAL},",
			"CODIDIOMA = #{codidioma,jdbcType=VARCHAR},", "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
			"FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP}",
			"where IDCENACCLIENTE = #{idcenaccliente,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(CenAcCliente record);
}