package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.CenDireccionTipodireccion;
import org.itcgae.siga.db.entities.CenDireccionTipodireccionExample;
import org.itcgae.siga.db.entities.CenDireccionTipodireccionKey;

public interface CenDireccionTipodireccionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@SelectProvider(type = CenDireccionTipodireccionSqlProvider.class, method = "countByExample")
	long countByExample(CenDireccionTipodireccionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@DeleteProvider(type = CenDireccionTipodireccionSqlProvider.class, method = "deleteByExample")
	int deleteByExample(CenDireccionTipodireccionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Delete({ "delete from CEN_DIRECCION_TIPODIRECCION", "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
			"and IDPERSONA = #{idpersona,jdbcType=DECIMAL}", "and IDDIRECCION = #{iddireccion,jdbcType=DECIMAL}",
			"and IDTIPODIRECCION = #{idtipodireccion,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(CenDireccionTipodireccionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Insert({ "insert into CEN_DIRECCION_TIPODIRECCION (IDINSTITUCION, IDPERSONA, ", "IDDIRECCION, IDTIPODIRECCION, ",
			"FECHAMODIFICACION, USUMODIFICACION)",
			"values (#{idinstitucion,jdbcType=DECIMAL}, #{idpersona,jdbcType=DECIMAL}, ",
			"#{iddireccion,jdbcType=DECIMAL}, #{idtipodireccion,jdbcType=DECIMAL}, ",
			"#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL})" })
	int insert(CenDireccionTipodireccion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@InsertProvider(type = CenDireccionTipodireccionSqlProvider.class, method = "insertSelective")
	int insertSelective(CenDireccionTipodireccion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@SelectProvider(type = CenDireccionTipodireccionSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDPERSONA", property = "idpersona", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDDIRECCION", property = "iddireccion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDTIPODIRECCION", property = "idtipodireccion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL) })
	List<CenDireccionTipodireccion> selectByExample(CenDireccionTipodireccionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Select({ "select", "IDINSTITUCION, IDPERSONA, IDDIRECCION, IDTIPODIRECCION, FECHAMODIFICACION, USUMODIFICACION",
			"from CEN_DIRECCION_TIPODIRECCION", "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
			"and IDPERSONA = #{idpersona,jdbcType=DECIMAL}", "and IDDIRECCION = #{iddireccion,jdbcType=DECIMAL}",
			"and IDTIPODIRECCION = #{idtipodireccion,jdbcType=DECIMAL}" })
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDPERSONA", property = "idpersona", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDDIRECCION", property = "iddireccion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDTIPODIRECCION", property = "idtipodireccion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL) })
	CenDireccionTipodireccion selectByPrimaryKey(CenDireccionTipodireccionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenDireccionTipodireccionSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") CenDireccionTipodireccion record,
			@Param("example") CenDireccionTipodireccionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenDireccionTipodireccionSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") CenDireccionTipodireccion record,
			@Param("example") CenDireccionTipodireccionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenDireccionTipodireccionSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(CenDireccionTipodireccion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_DIRECCION_TIPODIRECCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Update({ "update CEN_DIRECCION_TIPODIRECCION", "set FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
			"USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}",
			"where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}", "and IDPERSONA = #{idpersona,jdbcType=DECIMAL}",
			"and IDDIRECCION = #{iddireccion,jdbcType=DECIMAL}",
			"and IDTIPODIRECCION = #{idtipodireccion,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(CenDireccionTipodireccion record);
}