package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.CenRegMercantil;
import org.itcgae.siga.db.entities.CenRegMercantilExample;

public interface CenRegMercantilMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @SelectProvider(type=CenRegMercantilSqlProvider.class, method="countByExample")
    long countByExample(CenRegMercantilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @DeleteProvider(type=CenRegMercantilSqlProvider.class, method="deleteByExample")
    int deleteByExample(CenRegMercantilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @Delete({
        "delete from CEN_REG_MERCANTIL",
        "where ID_DATOS_REG = #{idDatosReg,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long idDatosReg);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @Insert({
        "insert into CEN_REG_MERCANTIL (ID_DATOS_REG, NUM_REGISTRO, ",
        "IDENTIFICACION_REG, FECHA_INSCRIPCION, ",
        "FECHA_CANCELACION, FECHAMODIFICACION, ",
        "USUMODIFICACION)",
        "values (#{idDatosReg,jdbcType=DECIMAL}, #{numRegistro,jdbcType=VARCHAR}, ",
        "#{identificacionReg,jdbcType=VARCHAR}, #{fechaInscripcion,jdbcType=TIMESTAMP}, ",
        "#{fechaCancelacion,jdbcType=TIMESTAMP}, #{fechamodificacion,jdbcType=TIMESTAMP}, ",
        "#{usumodificacion,jdbcType=DECIMAL})"
    })
    @SelectKey(statement="SELECT seq_id_datos_reg.NEXTVAL FROM DUAL", keyProperty="idDatosReg", before=true, resultType=Long.class)
    int insert(CenRegMercantil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @InsertProvider(type=CenRegMercantilSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT seq_id_datos_reg.NEXTVAL FROM DUAL", keyProperty="idDatosReg", before=true, resultType=Long.class)
    int insertSelective(CenRegMercantil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @SelectProvider(type=CenRegMercantilSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID_DATOS_REG", property="idDatosReg", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NUM_REGISTRO", property="numRegistro", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDENTIFICACION_REG", property="identificacionReg", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHA_INSCRIPCION", property="fechaInscripcion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHA_CANCELACION", property="fechaCancelacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)
    })
    List<CenRegMercantil> selectByExample(CenRegMercantilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @Select({
        "select",
        "ID_DATOS_REG, NUM_REGISTRO, IDENTIFICACION_REG, FECHA_INSCRIPCION, FECHA_CANCELACION, ",
        "FECHAMODIFICACION, USUMODIFICACION",
        "from CEN_REG_MERCANTIL",
        "where ID_DATOS_REG = #{idDatosReg,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID_DATOS_REG", property="idDatosReg", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NUM_REGISTRO", property="numRegistro", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDENTIFICACION_REG", property="identificacionReg", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHA_INSCRIPCION", property="fechaInscripcion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHA_CANCELACION", property="fechaCancelacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)
    })
    CenRegMercantil selectByPrimaryKey(Long idDatosReg);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @UpdateProvider(type=CenRegMercantilSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CenRegMercantil record, @Param("example") CenRegMercantilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @UpdateProvider(type=CenRegMercantilSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CenRegMercantil record, @Param("example") CenRegMercantilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @UpdateProvider(type=CenRegMercantilSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CenRegMercantil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.CEN_REG_MERCANTIL
     *
     * @mbg.generated Fri Aug 03 11:55:27 CEST 2018
     */
    @Update({
        "update CEN_REG_MERCANTIL",
        "set NUM_REGISTRO = #{numRegistro,jdbcType=VARCHAR},",
          "IDENTIFICACION_REG = #{identificacionReg,jdbcType=VARCHAR},",
          "FECHA_INSCRIPCION = #{fechaInscripcion,jdbcType=TIMESTAMP},",
          "FECHA_CANCELACION = #{fechaCancelacion,jdbcType=TIMESTAMP},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}",
        "where ID_DATOS_REG = #{idDatosReg,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(CenRegMercantil record);
}