package org.itcgae.siga.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.CenSucursales;
import org.itcgae.siga.db.entities.CenSucursalesExample;
import org.itcgae.siga.db.entities.CenSucursalesKey;

public interface CenSucursalesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@SelectProvider(type = CenSucursalesSqlProvider.class, method = "countByExample")
	long countByExample(CenSucursalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@DeleteProvider(type = CenSucursalesSqlProvider.class, method = "deleteByExample")
	int deleteByExample(CenSucursalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Delete({ "delete from CEN_SUCURSALES", "where BANCOS_CODIGO = #{bancosCodigo,jdbcType=VARCHAR}",
			"and COD_SUCURSAL = #{codSucursal,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(CenSucursalesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Insert({ "insert into CEN_SUCURSALES (BANCOS_CODIGO, COD_SUCURSAL, ", "NOMBRE, DOMICILIO, ",
			"CODIGOPOSTAL, COD_PLAZA, ", "FECHAMODIFICACION, USUMODIFICACION)",
			"values (#{bancosCodigo,jdbcType=VARCHAR}, #{codSucursal,jdbcType=VARCHAR}, ",
			"#{nombre,jdbcType=VARCHAR}, #{domicilio,jdbcType=VARCHAR}, ",
			"#{codigopostal,jdbcType=VARCHAR}, #{codPlaza,jdbcType=VARCHAR}, ",
			"#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL})" })
	int insert(CenSucursales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@InsertProvider(type = CenSucursalesSqlProvider.class, method = "insertSelective")
	int insertSelective(CenSucursales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@SelectProvider(type = CenSucursalesSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "BANCOS_CODIGO", property = "bancosCodigo", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "COD_SUCURSAL", property = "codSucursal", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "NOMBRE", property = "nombre", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DOMICILIO", property = "domicilio", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CODIGOPOSTAL", property = "codigopostal", jdbcType = JdbcType.VARCHAR),
			@Result(column = "COD_PLAZA", property = "codPlaza", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL) })
	List<CenSucursales> selectByExample(CenSucursalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Select({ "select", "BANCOS_CODIGO, COD_SUCURSAL, NOMBRE, DOMICILIO, CODIGOPOSTAL, COD_PLAZA, FECHAMODIFICACION, ",
			"USUMODIFICACION", "from CEN_SUCURSALES", "where BANCOS_CODIGO = #{bancosCodigo,jdbcType=VARCHAR}",
			"and COD_SUCURSAL = #{codSucursal,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "BANCOS_CODIGO", property = "bancosCodigo", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "COD_SUCURSAL", property = "codSucursal", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "NOMBRE", property = "nombre", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DOMICILIO", property = "domicilio", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CODIGOPOSTAL", property = "codigopostal", jdbcType = JdbcType.VARCHAR),
			@Result(column = "COD_PLAZA", property = "codPlaza", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL) })
	CenSucursales selectByPrimaryKey(CenSucursalesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenSucursalesSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") CenSucursales record, @Param("example") CenSucursalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenSucursalesSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") CenSucursales record, @Param("example") CenSucursalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenSucursalesSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(CenSucursales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Update({ "update CEN_SUCURSALES", "set NOMBRE = #{nombre,jdbcType=VARCHAR},",
			"DOMICILIO = #{domicilio,jdbcType=VARCHAR},", "CODIGOPOSTAL = #{codigopostal,jdbcType=VARCHAR},",
			"COD_PLAZA = #{codPlaza,jdbcType=VARCHAR},", "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
			"USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}",
			"where BANCOS_CODIGO = #{bancosCodigo,jdbcType=VARCHAR}",
			"and COD_SUCURSAL = #{codSucursal,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(CenSucursales record);
}