package org.itcgae.siga.db.mappers;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.db.entities.CenSolicitudmodificacioncv;
import org.itcgae.siga.db.entities.CenSolicitudmodificacioncvExample;
import org.itcgae.siga.db.entities.CenSolicitudmodificacioncvExample.Criteria;
import org.itcgae.siga.db.entities.CenSolicitudmodificacioncvExample.Criterion;

public class CenSolicitudmodificacioncvSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SOLICITUDMODIFICACIONCV
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String countByExample(CenSolicitudmodificacioncvExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("CEN_SOLICITUDMODIFICACIONCV");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SOLICITUDMODIFICACIONCV
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String deleteByExample(CenSolicitudmodificacioncvExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("CEN_SOLICITUDMODIFICACIONCV");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SOLICITUDMODIFICACIONCV
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String insertSelective(CenSolicitudmodificacioncv record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("CEN_SOLICITUDMODIFICACIONCV");
		if (record.getIdsolicitud() != null) {
			sql.VALUES("IDSOLICITUD", "#{idsolicitud,jdbcType=DECIMAL}");
		}
		if (record.getMotivo() != null) {
			sql.VALUES("MOTIVO", "#{motivo,jdbcType=VARCHAR}");
		}
		if (record.getFechainicio() != null) {
			sql.VALUES("FECHAINICIO", "#{fechainicio,jdbcType=TIMESTAMP}");
		}
		if (record.getFechafin() != null) {
			sql.VALUES("FECHAFIN", "#{fechafin,jdbcType=TIMESTAMP}");
		}
		if (record.getDescripcion() != null) {
			sql.VALUES("DESCRIPCION", "#{descripcion,jdbcType=VARCHAR}");
		}
		if (record.getIdpersona() != null) {
			sql.VALUES("IDPERSONA", "#{idpersona,jdbcType=DECIMAL}");
		}
		if (record.getIdinstitucion() != null) {
			sql.VALUES("IDINSTITUCION", "#{idinstitucion,jdbcType=DECIMAL}");
		}
		if (record.getIdtipocv() != null) {
			sql.VALUES("IDTIPOCV", "#{idtipocv,jdbcType=DECIMAL}");
		}
		if (record.getFechamodificacion() != null) {
			sql.VALUES("FECHAMODIFICACION", "#{fechamodificacion,jdbcType=TIMESTAMP}");
		}
		if (record.getUsumodificacion() != null) {
			sql.VALUES("USUMODIFICACION", "#{usumodificacion,jdbcType=DECIMAL}");
		}
		if (record.getIdestadosolic() != null) {
			sql.VALUES("IDESTADOSOLIC", "#{idestadosolic,jdbcType=DECIMAL}");
		}
		if (record.getFechaalta() != null) {
			sql.VALUES("FECHAALTA", "#{fechaalta,jdbcType=TIMESTAMP}");
		}
		if (record.getIdcv() != null) {
			sql.VALUES("IDCV", "#{idcv,jdbcType=DECIMAL}");
		}
		if (record.getIdtipocvsubtipo1() != null) {
			sql.VALUES("IDTIPOCVSUBTIPO1", "#{idtipocvsubtipo1,jdbcType=DECIMAL}");
		}
		if (record.getIdtipocvsubtipo2() != null) {
			sql.VALUES("IDTIPOCVSUBTIPO2", "#{idtipocvsubtipo2,jdbcType=DECIMAL}");
		}
		if (record.getIdinstitucionSubt1() != null) {
			sql.VALUES("IDINSTITUCION_SUBT1", "#{idinstitucionSubt1,jdbcType=DECIMAL}");
		}
		if (record.getIdinstitucionSubt2() != null) {
			sql.VALUES("IDINSTITUCION_SUBT2", "#{idinstitucionSubt2,jdbcType=DECIMAL}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SOLICITUDMODIFICACIONCV
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String selectByExample(CenSolicitudmodificacioncvExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("IDSOLICITUD");
		} else {
			sql.SELECT("IDSOLICITUD");
		}
		sql.SELECT("MOTIVO");
		sql.SELECT("FECHAINICIO");
		sql.SELECT("FECHAFIN");
		sql.SELECT("DESCRIPCION");
		sql.SELECT("IDPERSONA");
		sql.SELECT("IDINSTITUCION");
		sql.SELECT("IDTIPOCV");
		sql.SELECT("FECHAMODIFICACION");
		sql.SELECT("USUMODIFICACION");
		sql.SELECT("IDESTADOSOLIC");
		sql.SELECT("FECHAALTA");
		sql.SELECT("IDCV");
		sql.SELECT("IDTIPOCVSUBTIPO1");
		sql.SELECT("IDTIPOCVSUBTIPO2");
		sql.SELECT("IDINSTITUCION_SUBT1");
		sql.SELECT("IDINSTITUCION_SUBT2");
		sql.FROM("CEN_SOLICITUDMODIFICACIONCV");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SOLICITUDMODIFICACIONCV
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		CenSolicitudmodificacioncv record = (CenSolicitudmodificacioncv) parameter.get("record");
		CenSolicitudmodificacioncvExample example = (CenSolicitudmodificacioncvExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("CEN_SOLICITUDMODIFICACIONCV");
		if (record.getIdsolicitud() != null) {
			sql.SET("IDSOLICITUD = #{record.idsolicitud,jdbcType=DECIMAL}");
		}
		if (record.getMotivo() != null) {
			sql.SET("MOTIVO = #{record.motivo,jdbcType=VARCHAR}");
		}
		if (record.getFechainicio() != null) {
			sql.SET("FECHAINICIO = #{record.fechainicio,jdbcType=TIMESTAMP}");
		}
		if (record.getFechafin() != null) {
			sql.SET("FECHAFIN = #{record.fechafin,jdbcType=TIMESTAMP}");
		}
		if (record.getDescripcion() != null) {
			sql.SET("DESCRIPCION = #{record.descripcion,jdbcType=VARCHAR}");
		}
		if (record.getIdpersona() != null) {
			sql.SET("IDPERSONA = #{record.idpersona,jdbcType=DECIMAL}");
		}
		if (record.getIdinstitucion() != null) {
			sql.SET("IDINSTITUCION = #{record.idinstitucion,jdbcType=DECIMAL}");
		}
		if (record.getIdtipocv() != null) {
			sql.SET("IDTIPOCV = #{record.idtipocv,jdbcType=DECIMAL}");
		}
		if (record.getFechamodificacion() != null) {
			sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=TIMESTAMP}");
		}
		if (record.getUsumodificacion() != null) {
			sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=DECIMAL}");
		}
		if (record.getIdestadosolic() != null) {
			sql.SET("IDESTADOSOLIC = #{record.idestadosolic,jdbcType=DECIMAL}");
		}
		if (record.getFechaalta() != null) {
			sql.SET("FECHAALTA = #{record.fechaalta,jdbcType=TIMESTAMP}");
		}
		if (record.getIdcv() != null) {
			sql.SET("IDCV = #{record.idcv,jdbcType=DECIMAL}");
		}
		if (record.getIdtipocvsubtipo1() != null) {
			sql.SET("IDTIPOCVSUBTIPO1 = #{record.idtipocvsubtipo1,jdbcType=DECIMAL}");
		}
		if (record.getIdtipocvsubtipo2() != null) {
			sql.SET("IDTIPOCVSUBTIPO2 = #{record.idtipocvsubtipo2,jdbcType=DECIMAL}");
		}
		if (record.getIdinstitucionSubt1() != null) {
			sql.SET("IDINSTITUCION_SUBT1 = #{record.idinstitucionSubt1,jdbcType=DECIMAL}");
		}
		if (record.getIdinstitucionSubt2() != null) {
			sql.SET("IDINSTITUCION_SUBT2 = #{record.idinstitucionSubt2,jdbcType=DECIMAL}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SOLICITUDMODIFICACIONCV
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("CEN_SOLICITUDMODIFICACIONCV");
		sql.SET("IDSOLICITUD = #{record.idsolicitud,jdbcType=DECIMAL}");
		sql.SET("MOTIVO = #{record.motivo,jdbcType=VARCHAR}");
		sql.SET("FECHAINICIO = #{record.fechainicio,jdbcType=TIMESTAMP}");
		sql.SET("FECHAFIN = #{record.fechafin,jdbcType=TIMESTAMP}");
		sql.SET("DESCRIPCION = #{record.descripcion,jdbcType=VARCHAR}");
		sql.SET("IDPERSONA = #{record.idpersona,jdbcType=DECIMAL}");
		sql.SET("IDINSTITUCION = #{record.idinstitucion,jdbcType=DECIMAL}");
		sql.SET("IDTIPOCV = #{record.idtipocv,jdbcType=DECIMAL}");
		sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=TIMESTAMP}");
		sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=DECIMAL}");
		sql.SET("IDESTADOSOLIC = #{record.idestadosolic,jdbcType=DECIMAL}");
		sql.SET("FECHAALTA = #{record.fechaalta,jdbcType=TIMESTAMP}");
		sql.SET("IDCV = #{record.idcv,jdbcType=DECIMAL}");
		sql.SET("IDTIPOCVSUBTIPO1 = #{record.idtipocvsubtipo1,jdbcType=DECIMAL}");
		sql.SET("IDTIPOCVSUBTIPO2 = #{record.idtipocvsubtipo2,jdbcType=DECIMAL}");
		sql.SET("IDINSTITUCION_SUBT1 = #{record.idinstitucionSubt1,jdbcType=DECIMAL}");
		sql.SET("IDINSTITUCION_SUBT2 = #{record.idinstitucionSubt2,jdbcType=DECIMAL}");
		CenSolicitudmodificacioncvExample example = (CenSolicitudmodificacioncvExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SOLICITUDMODIFICACIONCV
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String updateByPrimaryKeySelective(CenSolicitudmodificacioncv record) {
		SQL sql = new SQL();
		sql.UPDATE("CEN_SOLICITUDMODIFICACIONCV");
		if (record.getMotivo() != null) {
			sql.SET("MOTIVO = #{motivo,jdbcType=VARCHAR}");
		}
		if (record.getFechainicio() != null) {
			sql.SET("FECHAINICIO = #{fechainicio,jdbcType=TIMESTAMP}");
		}
		if (record.getFechafin() != null) {
			sql.SET("FECHAFIN = #{fechafin,jdbcType=TIMESTAMP}");
		}
		if (record.getDescripcion() != null) {
			sql.SET("DESCRIPCION = #{descripcion,jdbcType=VARCHAR}");
		}
		if (record.getIdpersona() != null) {
			sql.SET("IDPERSONA = #{idpersona,jdbcType=DECIMAL}");
		}
		if (record.getIdinstitucion() != null) {
			sql.SET("IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}");
		}
		if (record.getIdtipocv() != null) {
			sql.SET("IDTIPOCV = #{idtipocv,jdbcType=DECIMAL}");
		}
		if (record.getFechamodificacion() != null) {
			sql.SET("FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP}");
		}
		if (record.getUsumodificacion() != null) {
			sql.SET("USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}");
		}
		if (record.getIdestadosolic() != null) {
			sql.SET("IDESTADOSOLIC = #{idestadosolic,jdbcType=DECIMAL}");
		}
		if (record.getFechaalta() != null) {
			sql.SET("FECHAALTA = #{fechaalta,jdbcType=TIMESTAMP}");
		}
		if (record.getIdcv() != null) {
			sql.SET("IDCV = #{idcv,jdbcType=DECIMAL}");
		}
		if (record.getIdtipocvsubtipo1() != null) {
			sql.SET("IDTIPOCVSUBTIPO1 = #{idtipocvsubtipo1,jdbcType=DECIMAL}");
		}
		if (record.getIdtipocvsubtipo2() != null) {
			sql.SET("IDTIPOCVSUBTIPO2 = #{idtipocvsubtipo2,jdbcType=DECIMAL}");
		}
		if (record.getIdinstitucionSubt1() != null) {
			sql.SET("IDINSTITUCION_SUBT1 = #{idinstitucionSubt1,jdbcType=DECIMAL}");
		}
		if (record.getIdinstitucionSubt2() != null) {
			sql.SET("IDINSTITUCION_SUBT2 = #{idinstitucionSubt2,jdbcType=DECIMAL}");
		}
		sql.WHERE("IDSOLICITUD = #{idsolicitud,jdbcType=DECIMAL}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SOLICITUDMODIFICACIONCV
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	protected void applyWhere(SQL sql, CenSolicitudmodificacioncvExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}