package org.itcgae.siga.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.CenTiposolicitud;
import org.itcgae.siga.db.entities.CenTiposolicitudExample;

public interface CenTiposolicitudMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@SelectProvider(type = CenTiposolicitudSqlProvider.class, method = "countByExample")
	long countByExample(CenTiposolicitudExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@DeleteProvider(type = CenTiposolicitudSqlProvider.class, method = "deleteByExample")
	int deleteByExample(CenTiposolicitudExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@Delete({ "delete from CEN_TIPOSOLICITUD", "where IDTIPOSOLICITUD = #{idtiposolicitud,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Short idtiposolicitud);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@Insert({ "insert into CEN_TIPOSOLICITUD (IDTIPOSOLICITUD, FECHAMODIFICACION, ", "USUMODIFICACION, DESCRIPCION)",
			"values (#{idtiposolicitud,jdbcType=DECIMAL}, #{fechamodificacion,jdbcType=TIMESTAMP}, ",
			"#{usumodificacion,jdbcType=DECIMAL}, #{descripcion,jdbcType=VARCHAR})" })
	int insert(CenTiposolicitud record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@InsertProvider(type = CenTiposolicitudSqlProvider.class, method = "insertSelective")
	int insertSelective(CenTiposolicitud record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@SelectProvider(type = CenTiposolicitudSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "IDTIPOSOLICITUD", property = "idtiposolicitud", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DESCRIPCION", property = "descripcion", jdbcType = JdbcType.VARCHAR) })
	List<CenTiposolicitud> selectByExample(CenTiposolicitudExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@Select({ "select", "IDTIPOSOLICITUD, FECHAMODIFICACION, USUMODIFICACION, DESCRIPCION", "from CEN_TIPOSOLICITUD",
			"where IDTIPOSOLICITUD = #{idtiposolicitud,jdbcType=DECIMAL}" })
	@Results({
			@Result(column = "IDTIPOSOLICITUD", property = "idtiposolicitud", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DESCRIPCION", property = "descripcion", jdbcType = JdbcType.VARCHAR) })
	CenTiposolicitud selectByPrimaryKey(Short idtiposolicitud);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@UpdateProvider(type = CenTiposolicitudSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") CenTiposolicitud record,
			@Param("example") CenTiposolicitudExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@UpdateProvider(type = CenTiposolicitudSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") CenTiposolicitud record, @Param("example") CenTiposolicitudExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@UpdateProvider(type = CenTiposolicitudSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(CenTiposolicitud record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CEN_TIPOSOLICITUD
	 * @mbg.generated  Mon Jan 10 13:11:48 CET 2022
	 */
	@Update({ "update CEN_TIPOSOLICITUD", "set FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
			"USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},", "DESCRIPCION = #{descripcion,jdbcType=VARCHAR}",
			"where IDTIPOSOLICITUD = #{idtiposolicitud,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(CenTiposolicitud record);
}