package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.CenTipoidentificacion;
import org.itcgae.siga.db.entities.CenTipoidentificacionExample;

public interface CenTipoidentificacionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@SelectProvider(type = CenTipoidentificacionSqlProvider.class, method = "countByExample")
	long countByExample(CenTipoidentificacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@DeleteProvider(type = CenTipoidentificacionSqlProvider.class, method = "deleteByExample")
	int deleteByExample(CenTipoidentificacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Delete({ "delete from CEN_TIPOIDENTIFICACION",
			"where IDTIPOIDENTIFICACION = #{idtipoidentificacion,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Short idtipoidentificacion);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Insert({ "insert into CEN_TIPOIDENTIFICACION (IDTIPOIDENTIFICACION, DESCRIPCION, ",
			"FECHAMODIFICACION, USUMODIFICACION, ", "CODIGOEXT, CODIGOEJIS)",
			"values (#{idtipoidentificacion,jdbcType=DECIMAL}, #{descripcion,jdbcType=VARCHAR}, ",
			"#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL}, ",
			"#{codigoext,jdbcType=VARCHAR}, #{codigoejis,jdbcType=VARCHAR})" })
	int insert(CenTipoidentificacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@InsertProvider(type = CenTipoidentificacionSqlProvider.class, method = "insertSelective")
	int insertSelective(CenTipoidentificacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@SelectProvider(type = CenTipoidentificacionSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "IDTIPOIDENTIFICACION", property = "idtipoidentificacion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "DESCRIPCION", property = "descripcion", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "CODIGOEXT", property = "codigoext", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CODIGOEJIS", property = "codigoejis", jdbcType = JdbcType.VARCHAR) })
	List<CenTipoidentificacion> selectByExample(CenTipoidentificacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Select({ "select", "IDTIPOIDENTIFICACION, DESCRIPCION, FECHAMODIFICACION, USUMODIFICACION, CODIGOEXT, ",
			"CODIGOEJIS", "from CEN_TIPOIDENTIFICACION",
			"where IDTIPOIDENTIFICACION = #{idtipoidentificacion,jdbcType=DECIMAL}" })
	@Results({
			@Result(column = "IDTIPOIDENTIFICACION", property = "idtipoidentificacion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "DESCRIPCION", property = "descripcion", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "CODIGOEXT", property = "codigoext", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CODIGOEJIS", property = "codigoejis", jdbcType = JdbcType.VARCHAR) })
	CenTipoidentificacion selectByPrimaryKey(Short idtipoidentificacion);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenTipoidentificacionSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") CenTipoidentificacion record,
			@Param("example") CenTipoidentificacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenTipoidentificacionSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") CenTipoidentificacion record,
			@Param("example") CenTipoidentificacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@UpdateProvider(type = CenTipoidentificacionSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(CenTipoidentificacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_TIPOIDENTIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	@Update({ "update CEN_TIPOIDENTIFICACION", "set DESCRIPCION = #{descripcion,jdbcType=VARCHAR},",
			"FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
			"USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},", "CODIGOEXT = #{codigoext,jdbcType=VARCHAR},",
			"CODIGOEJIS = #{codigoejis,jdbcType=VARCHAR}",
			"where IDTIPOIDENTIFICACION = #{idtipoidentificacion,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(CenTipoidentificacion record);
}