package org.itcgae.siga.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ConConsulta;
import org.itcgae.siga.db.entities.ConConsultaExample;
import org.itcgae.siga.db.entities.ConConsultaKey;

public interface ConConsultaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@SelectProvider(type = ConConsultaSqlProvider.class, method = "countByExample")
	long countByExample(ConConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@DeleteProvider(type = ConConsultaSqlProvider.class, method = "deleteByExample")
	int deleteByExample(ConConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@Delete({ "delete from CON_CONSULTA", "where IDINSTITUCION = #{idinstitucion,jdbcType=NUMERIC}",
			"and IDCONSULTA = #{idconsulta,jdbcType=NUMERIC}" })
	int deleteByPrimaryKey(ConConsultaKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@Insert({ "insert into CON_CONSULTA (IDINSTITUCION, IDCONSULTA, ", "DESCRIPCION, GENERAL, ",
			"TIPOCONSULTA, IDMODULO, ", "FECHAMODIFICACION, USUMODIFICACION, ", "BASES, IDTABLA, ",
			"ESEXPERTA, OBSERVACIONES, ", "IDCLASECOMUNICACION, FECHABAJA, ", "IDOBJETIVO, SENTENCIA)",
			"values (#{idinstitucion,jdbcType=NUMERIC}, #{idconsulta,jdbcType=NUMERIC}, ",
			"#{descripcion,jdbcType=VARCHAR}, #{general,jdbcType=VARCHAR}, ",
			"#{tipoconsulta,jdbcType=VARCHAR}, #{idmodulo,jdbcType=NUMERIC}, ",
			"#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=NUMERIC}, ",
			"#{bases,jdbcType=VARCHAR}, #{idtabla,jdbcType=NUMERIC}, ",
			"#{esexperta,jdbcType=VARCHAR}, #{observaciones,jdbcType=VARCHAR}, ",
			"#{idclasecomunicacion,jdbcType=NUMERIC}, #{fechabaja,jdbcType=TIMESTAMP}, ",
			"#{idobjetivo,jdbcType=NUMERIC}, #{sentencia,jdbcType=CLOB})" })
	int insert(ConConsulta row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@InsertProvider(type = ConConsultaSqlProvider.class, method = "insertSelective")
	int insertSelective(ConConsulta row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@SelectProvider(type = ConConsultaSqlProvider.class, method = "selectByExampleWithBLOBs")
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.NUMERIC, id = true),
			@Result(column = "IDCONSULTA", property = "idconsulta", jdbcType = JdbcType.NUMERIC, id = true),
			@Result(column = "DESCRIPCION", property = "descripcion", jdbcType = JdbcType.VARCHAR),
			@Result(column = "GENERAL", property = "general", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TIPOCONSULTA", property = "tipoconsulta", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IDMODULO", property = "idmodulo", jdbcType = JdbcType.NUMERIC),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.NUMERIC),
			@Result(column = "BASES", property = "bases", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IDTABLA", property = "idtabla", jdbcType = JdbcType.NUMERIC),
			@Result(column = "ESEXPERTA", property = "esexperta", jdbcType = JdbcType.VARCHAR),
			@Result(column = "OBSERVACIONES", property = "observaciones", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IDCLASECOMUNICACION", property = "idclasecomunicacion", jdbcType = JdbcType.NUMERIC),
			@Result(column = "FECHABAJA", property = "fechabaja", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "IDOBJETIVO", property = "idobjetivo", jdbcType = JdbcType.NUMERIC),
			@Result(column = "SENTENCIA", property = "sentencia", jdbcType = JdbcType.CLOB) })
	List<ConConsulta> selectByExampleWithBLOBs(ConConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@SelectProvider(type = ConConsultaSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.NUMERIC, id = true),
			@Result(column = "IDCONSULTA", property = "idconsulta", jdbcType = JdbcType.NUMERIC, id = true),
			@Result(column = "DESCRIPCION", property = "descripcion", jdbcType = JdbcType.VARCHAR),
			@Result(column = "GENERAL", property = "general", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TIPOCONSULTA", property = "tipoconsulta", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IDMODULO", property = "idmodulo", jdbcType = JdbcType.NUMERIC),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.NUMERIC),
			@Result(column = "BASES", property = "bases", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IDTABLA", property = "idtabla", jdbcType = JdbcType.NUMERIC),
			@Result(column = "ESEXPERTA", property = "esexperta", jdbcType = JdbcType.VARCHAR),
			@Result(column = "OBSERVACIONES", property = "observaciones", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IDCLASECOMUNICACION", property = "idclasecomunicacion", jdbcType = JdbcType.NUMERIC),
			@Result(column = "FECHABAJA", property = "fechabaja", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "IDOBJETIVO", property = "idobjetivo", jdbcType = JdbcType.NUMERIC) })
	List<ConConsulta> selectByExample(ConConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@Select({ "select", "IDINSTITUCION, IDCONSULTA, DESCRIPCION, GENERAL, TIPOCONSULTA, IDMODULO, FECHAMODIFICACION, ",
			"USUMODIFICACION, BASES, IDTABLA, ESEXPERTA, OBSERVACIONES, IDCLASECOMUNICACION, ",
			"FECHABAJA, IDOBJETIVO, SENTENCIA", "from CON_CONSULTA",
			"where IDINSTITUCION = #{idinstitucion,jdbcType=NUMERIC}",
			"and IDCONSULTA = #{idconsulta,jdbcType=NUMERIC}" })
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.NUMERIC, id = true),
			@Result(column = "IDCONSULTA", property = "idconsulta", jdbcType = JdbcType.NUMERIC, id = true),
			@Result(column = "DESCRIPCION", property = "descripcion", jdbcType = JdbcType.VARCHAR),
			@Result(column = "GENERAL", property = "general", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TIPOCONSULTA", property = "tipoconsulta", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IDMODULO", property = "idmodulo", jdbcType = JdbcType.NUMERIC),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.NUMERIC),
			@Result(column = "BASES", property = "bases", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IDTABLA", property = "idtabla", jdbcType = JdbcType.NUMERIC),
			@Result(column = "ESEXPERTA", property = "esexperta", jdbcType = JdbcType.VARCHAR),
			@Result(column = "OBSERVACIONES", property = "observaciones", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IDCLASECOMUNICACION", property = "idclasecomunicacion", jdbcType = JdbcType.NUMERIC),
			@Result(column = "FECHABAJA", property = "fechabaja", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "IDOBJETIVO", property = "idobjetivo", jdbcType = JdbcType.NUMERIC),
			@Result(column = "SENTENCIA", property = "sentencia", jdbcType = JdbcType.CLOB) })
	ConConsulta selectByPrimaryKey(ConConsultaKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@UpdateProvider(type = ConConsultaSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("row") ConConsulta row, @Param("example") ConConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@UpdateProvider(type = ConConsultaSqlProvider.class, method = "updateByExampleWithBLOBs")
	int updateByExampleWithBLOBs(@Param("row") ConConsulta row, @Param("example") ConConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@UpdateProvider(type = ConConsultaSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("row") ConConsulta row, @Param("example") ConConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@UpdateProvider(type = ConConsultaSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(ConConsulta row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@Update({ "update CON_CONSULTA", "set DESCRIPCION = #{descripcion,jdbcType=VARCHAR},",
			"GENERAL = #{general,jdbcType=VARCHAR},", "TIPOCONSULTA = #{tipoconsulta,jdbcType=VARCHAR},",
			"IDMODULO = #{idmodulo,jdbcType=NUMERIC},", "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
			"USUMODIFICACION = #{usumodificacion,jdbcType=NUMERIC},", "BASES = #{bases,jdbcType=VARCHAR},",
			"IDTABLA = #{idtabla,jdbcType=NUMERIC},", "ESEXPERTA = #{esexperta,jdbcType=VARCHAR},",
			"OBSERVACIONES = #{observaciones,jdbcType=VARCHAR},",
			"IDCLASECOMUNICACION = #{idclasecomunicacion,jdbcType=NUMERIC},",
			"FECHABAJA = #{fechabaja,jdbcType=TIMESTAMP},", "IDOBJETIVO = #{idobjetivo,jdbcType=NUMERIC},",
			"SENTENCIA = #{sentencia,jdbcType=CLOB}", "where IDINSTITUCION = #{idinstitucion,jdbcType=NUMERIC}",
			"and IDCONSULTA = #{idconsulta,jdbcType=NUMERIC}" })
	int updateByPrimaryKeyWithBLOBs(ConConsulta row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.CON_CONSULTA
	 * @mbg.generated  Mon Feb 27 13:05:47 CET 2023
	 */
	@Update({ "update CON_CONSULTA", "set DESCRIPCION = #{descripcion,jdbcType=VARCHAR},",
			"GENERAL = #{general,jdbcType=VARCHAR},", "TIPOCONSULTA = #{tipoconsulta,jdbcType=VARCHAR},",
			"IDMODULO = #{idmodulo,jdbcType=NUMERIC},", "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
			"USUMODIFICACION = #{usumodificacion,jdbcType=NUMERIC},", "BASES = #{bases,jdbcType=VARCHAR},",
			"IDTABLA = #{idtabla,jdbcType=NUMERIC},", "ESEXPERTA = #{esexperta,jdbcType=VARCHAR},",
			"OBSERVACIONES = #{observaciones,jdbcType=VARCHAR},",
			"IDCLASECOMUNICACION = #{idclasecomunicacion,jdbcType=NUMERIC},",
			"FECHABAJA = #{fechabaja,jdbcType=TIMESTAMP},", "IDOBJETIVO = #{idobjetivo,jdbcType=NUMERIC}",
			"where IDINSTITUCION = #{idinstitucion,jdbcType=NUMERIC}",
			"and IDCONSULTA = #{idconsulta,jdbcType=NUMERIC}" })
	int updateByPrimaryKey(ConConsulta row);
}