package org.itcgae.siga.db.mappers;


import java.util.List;

import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.DemoStates;
import org.itcgae.siga.db.entities.DemoStatesExample;
import org.itcgae.siga.db.services.DemoStatesSqlProvider;

public interface DemoStatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_SOCIEDADES.DEMO_STATES
     *
     * @mbg.generated Wed Jan 31 17:21:07 CET 2018
     */
    @SelectProvider(type=DemoStatesSqlProvider.class, method="countByExample")
    long countByExample(DemoStatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_SOCIEDADES.DEMO_STATES
     *
     * @mbg.generated Wed Jan 31 17:21:07 CET 2018
     */
    @DeleteProvider(type=DemoStatesSqlProvider.class, method="deleteByExample")
    int deleteByExample(DemoStatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_SOCIEDADES.DEMO_STATES
     *
     * @mbg.generated Wed Jan 31 17:21:07 CET 2018
     */
    @Insert({
        "insert into DEMO_SOCIEDADES.DEMO_STATES (ST, STATE_NAME)",
        "values (#{st,jdbcType=VARCHAR}, #{stateName,jdbcType=VARCHAR})"
    })
    int insert(DemoStates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_SOCIEDADES.DEMO_STATES
     *
     * @mbg.generated Wed Jan 31 17:21:07 CET 2018
     */
    @InsertProvider(type=DemoStatesSqlProvider.class, method="insertSelective")
    int insertSelective(DemoStates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_SOCIEDADES.DEMO_STATES
     *
     * @mbg.generated Wed Jan 31 17:21:07 CET 2018
     */
    @SelectProvider(type=DemoStatesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ST", property="st", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATE_NAME", property="stateName", jdbcType=JdbcType.VARCHAR)
    })
    List<DemoStates> selectByExample(DemoStatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_SOCIEDADES.DEMO_STATES
     *
     * @mbg.generated Wed Jan 31 17:21:07 CET 2018
     */
    @UpdateProvider(type=DemoStatesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DemoStates record, @Param("example") DemoStatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_SOCIEDADES.DEMO_STATES
     *
     * @mbg.generated Wed Jan 31 17:21:07 CET 2018
     */
    @UpdateProvider(type=DemoStatesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") DemoStates record, @Param("example") DemoStatesExample example);
}