package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.EcomColaParametros;
import org.itcgae.siga.db.entities.EcomColaParametrosExample;
import org.itcgae.siga.db.entities.EcomColaParametrosKey;

public interface EcomColaParametrosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @SelectProvider(type=EcomColaParametrosSqlProvider.class, method="countByExample")
    long countByExample(EcomColaParametrosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @DeleteProvider(type=EcomColaParametrosSqlProvider.class, method="deleteByExample")
    int deleteByExample(EcomColaParametrosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @Delete({
        "delete from ECOM_COLA_PARAMETROS",
        "where IDECOMCOLA = #{idecomcola,jdbcType=DECIMAL}",
          "and CLAVE = #{clave,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(EcomColaParametrosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @Insert({
        "insert into ECOM_COLA_PARAMETROS (IDECOMCOLA, CLAVE, ",
        "VALOR)",
        "values (#{idecomcola,jdbcType=DECIMAL}, #{clave,jdbcType=VARCHAR}, ",
        "#{valor,jdbcType=VARCHAR})"
    })
    int insert(EcomColaParametros record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @InsertProvider(type=EcomColaParametrosSqlProvider.class, method="insertSelective")
    int insertSelective(EcomColaParametros record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @SelectProvider(type=EcomColaParametrosSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDECOMCOLA", property="idecomcola", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="CLAVE", property="clave", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="VALOR", property="valor", jdbcType=JdbcType.VARCHAR)
    })
    List<EcomColaParametros> selectByExample(EcomColaParametrosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @Select({
        "select",
        "IDECOMCOLA, CLAVE, VALOR",
        "from ECOM_COLA_PARAMETROS",
        "where IDECOMCOLA = #{idecomcola,jdbcType=DECIMAL}",
          "and CLAVE = #{clave,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="IDECOMCOLA", property="idecomcola", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="CLAVE", property="clave", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="VALOR", property="valor", jdbcType=JdbcType.VARCHAR)
    })
    EcomColaParametros selectByPrimaryKey(EcomColaParametrosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @UpdateProvider(type=EcomColaParametrosSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EcomColaParametros record, @Param("example") EcomColaParametrosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @UpdateProvider(type=EcomColaParametrosSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EcomColaParametros record, @Param("example") EcomColaParametrosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @UpdateProvider(type=EcomColaParametrosSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EcomColaParametros record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ECOM_COLA_PARAMETROS
     *
     * @mbg.generated Wed Jun 30 17:47:23 CEST 2021
     */
    @Update({
        "update ECOM_COLA_PARAMETROS",
        "set VALOR = #{valor,jdbcType=VARCHAR}",
        "where IDECOMCOLA = #{idecomcola,jdbcType=DECIMAL}",
          "and CLAVE = #{clave,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EcomColaParametros record);
}