package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.EnvValorcampoclave;
import org.itcgae.siga.db.entities.EnvValorcampoclaveExample;
import org.itcgae.siga.db.entities.EnvValorcampoclaveKey;

public interface EnvValorcampoclaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @SelectProvider(type=EnvValorcampoclaveSqlProvider.class, method="countByExample")
    long countByExample(EnvValorcampoclaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @DeleteProvider(type=EnvValorcampoclaveSqlProvider.class, method="deleteByExample")
    int deleteByExample(EnvValorcampoclaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @Delete({
        "delete from ENV_VALORCAMPOCLAVE",
        "where IDVALOR = #{idvalor,jdbcType=DECIMAL}",
          "and CLAVE = #{clave,jdbcType=VARCHAR}",
          "and CAMPO = #{campo,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(EnvValorcampoclaveKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @Insert({
        "insert into ENV_VALORCAMPOCLAVE (IDVALOR, CLAVE, ",
        "CAMPO, IDPROGRAM, ",
        "IDENVIO, IDINSTITUCION, ",
        "IDPERSONA, IDINSTITUCION_PERSONA, ",
        "FECHAMODIFICACION, USUMODIFICACION, ",
        "IDTIPOINFORME, VALOR)",
        "values (#{idvalor,jdbcType=DECIMAL}, #{clave,jdbcType=VARCHAR}, ",
        "#{campo,jdbcType=VARCHAR}, #{idprogram,jdbcType=DECIMAL}, ",
        "#{idenvio,jdbcType=DECIMAL}, #{idinstitucion,jdbcType=DECIMAL}, ",
        "#{idpersona,jdbcType=DECIMAL}, #{idinstitucionPersona,jdbcType=DECIMAL}, ",
        "#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL}, ",
        "#{idtipoinforme,jdbcType=VARCHAR}, #{valor,jdbcType=VARCHAR})"
    })
    int insert(EnvValorcampoclave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @InsertProvider(type=EnvValorcampoclaveSqlProvider.class, method="insertSelective")
    int insertSelective(EnvValorcampoclave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @SelectProvider(type=EnvValorcampoclaveSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDVALOR", property="idvalor", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="CLAVE", property="clave", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CAMPO", property="campo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="IDPROGRAM", property="idprogram", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDENVIO", property="idenvio", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDPERSONA", property="idpersona", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDINSTITUCION_PERSONA", property="idinstitucionPersona", jdbcType=JdbcType.DECIMAL),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDTIPOINFORME", property="idtipoinforme", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALOR", property="valor", jdbcType=JdbcType.VARCHAR)
    })
    List<EnvValorcampoclave> selectByExample(EnvValorcampoclaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @Select({
        "select",
        "IDVALOR, CLAVE, CAMPO, IDPROGRAM, IDENVIO, IDINSTITUCION, IDPERSONA, IDINSTITUCION_PERSONA, ",
        "FECHAMODIFICACION, USUMODIFICACION, IDTIPOINFORME, VALOR",
        "from ENV_VALORCAMPOCLAVE",
        "where IDVALOR = #{idvalor,jdbcType=DECIMAL}",
          "and CLAVE = #{clave,jdbcType=VARCHAR}",
          "and CAMPO = #{campo,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="IDVALOR", property="idvalor", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="CLAVE", property="clave", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CAMPO", property="campo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="IDPROGRAM", property="idprogram", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDENVIO", property="idenvio", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDPERSONA", property="idpersona", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDINSTITUCION_PERSONA", property="idinstitucionPersona", jdbcType=JdbcType.DECIMAL),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDTIPOINFORME", property="idtipoinforme", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALOR", property="valor", jdbcType=JdbcType.VARCHAR)
    })
    EnvValorcampoclave selectByPrimaryKey(EnvValorcampoclaveKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @UpdateProvider(type=EnvValorcampoclaveSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EnvValorcampoclave record, @Param("example") EnvValorcampoclaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @UpdateProvider(type=EnvValorcampoclaveSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EnvValorcampoclave record, @Param("example") EnvValorcampoclaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @UpdateProvider(type=EnvValorcampoclaveSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EnvValorcampoclave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.ENV_VALORCAMPOCLAVE
     *
     * @mbg.generated Mon Jun 07 11:33:17 CEST 2021
     */
    @Update({
        "update ENV_VALORCAMPOCLAVE",
        "set IDPROGRAM = #{idprogram,jdbcType=DECIMAL},",
          "IDENVIO = #{idenvio,jdbcType=DECIMAL},",
          "IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL},",
          "IDPERSONA = #{idpersona,jdbcType=DECIMAL},",
          "IDINSTITUCION_PERSONA = #{idinstitucionPersona,jdbcType=DECIMAL},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
          "IDTIPOINFORME = #{idtipoinforme,jdbcType=VARCHAR},",
          "VALOR = #{valor,jdbcType=VARCHAR}",
        "where IDVALOR = #{idvalor,jdbcType=DECIMAL}",
          "and CLAVE = #{clave,jdbcType=VARCHAR}",
          "and CAMPO = #{campo,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EnvValorcampoclave record);
}