package org.itcgae.siga.db.mappers;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.db.entities.FacLineadevoludisqbanco;
import org.itcgae.siga.db.entities.FacLineadevoludisqbancoExample.Criteria;
import org.itcgae.siga.db.entities.FacLineadevoludisqbancoExample.Criterion;
import org.itcgae.siga.db.entities.FacLineadevoludisqbancoExample;

public class FacLineadevoludisqbancoSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.FAC_LINEADEVOLUDISQBANCO
     *
     * @mbg.generated Wed Jan 12 17:13:18 CET 2022
     */
    public String countByExample(FacLineadevoludisqbancoExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("FAC_LINEADEVOLUDISQBANCO");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.FAC_LINEADEVOLUDISQBANCO
     *
     * @mbg.generated Wed Jan 12 17:13:18 CET 2022
     */
    public String deleteByExample(FacLineadevoludisqbancoExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("FAC_LINEADEVOLUDISQBANCO");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.FAC_LINEADEVOLUDISQBANCO
     *
     * @mbg.generated Wed Jan 12 17:13:18 CET 2022
     */
    public String insertSelective(FacLineadevoludisqbanco record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("FAC_LINEADEVOLUDISQBANCO");
        
        if (record.getIdinstitucion() != null) {
            sql.VALUES("IDINSTITUCION", "#{idinstitucion,jdbcType=DECIMAL}");
        }
        
        if (record.getIddisquetedevoluciones() != null) {
            sql.VALUES("IDDISQUETEDEVOLUCIONES", "#{iddisquetedevoluciones,jdbcType=DECIMAL}");
        }
        
        if (record.getIdrecibo() != null) {
            sql.VALUES("IDRECIBO", "#{idrecibo,jdbcType=VARCHAR}");
        }
        
        if (record.getIddisquetecargos() != null) {
            sql.VALUES("IDDISQUETECARGOS", "#{iddisquetecargos,jdbcType=DECIMAL}");
        }
        
        if (record.getIdfacturaincluidaendisquete() != null) {
            sql.VALUES("IDFACTURAINCLUIDAENDISQUETE", "#{idfacturaincluidaendisquete,jdbcType=DECIMAL}");
        }
        
        if (record.getFechamodificacion() != null) {
            sql.VALUES("FECHAMODIFICACION", "#{fechamodificacion,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUsumodificacion() != null) {
            sql.VALUES("USUMODIFICACION", "#{usumodificacion,jdbcType=DECIMAL}");
        }
        
        if (record.getDescripcionmotivos() != null) {
            sql.VALUES("DESCRIPCIONMOTIVOS", "#{descripcionmotivos,jdbcType=VARCHAR}");
        }
        
        if (record.getGastosdevolucion() != null) {
            sql.VALUES("GASTOSDEVOLUCION", "#{gastosdevolucion,jdbcType=DECIMAL}");
        }
        
        if (record.getCargarcliente() != null) {
            sql.VALUES("CARGARCLIENTE", "#{cargarcliente,jdbcType=VARCHAR}");
        }
        
        if (record.getContabilizada() != null) {
            sql.VALUES("CONTABILIZADA", "#{contabilizada,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.FAC_LINEADEVOLUDISQBANCO
     *
     * @mbg.generated Wed Jan 12 17:13:18 CET 2022
     */
    public String selectByExample(FacLineadevoludisqbancoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("IDINSTITUCION");
        } else {
            sql.SELECT("IDINSTITUCION");
        }
        sql.SELECT("IDDISQUETEDEVOLUCIONES");
        sql.SELECT("IDRECIBO");
        sql.SELECT("IDDISQUETECARGOS");
        sql.SELECT("IDFACTURAINCLUIDAENDISQUETE");
        sql.SELECT("FECHAMODIFICACION");
        sql.SELECT("USUMODIFICACION");
        sql.SELECT("DESCRIPCIONMOTIVOS");
        sql.SELECT("GASTOSDEVOLUCION");
        sql.SELECT("CARGARCLIENTE");
        sql.SELECT("CONTABILIZADA");
        sql.FROM("FAC_LINEADEVOLUDISQBANCO");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.FAC_LINEADEVOLUDISQBANCO
     *
     * @mbg.generated Wed Jan 12 17:13:18 CET 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        FacLineadevoludisqbanco record = (FacLineadevoludisqbanco) parameter.get("record");
        FacLineadevoludisqbancoExample example = (FacLineadevoludisqbancoExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("FAC_LINEADEVOLUDISQBANCO");
        
        if (record.getIdinstitucion() != null) {
            sql.SET("IDINSTITUCION = #{record.idinstitucion,jdbcType=DECIMAL}");
        }
        
        if (record.getIddisquetedevoluciones() != null) {
            sql.SET("IDDISQUETEDEVOLUCIONES = #{record.iddisquetedevoluciones,jdbcType=DECIMAL}");
        }
        
        if (record.getIdrecibo() != null) {
            sql.SET("IDRECIBO = #{record.idrecibo,jdbcType=VARCHAR}");
        }
        
        if (record.getIddisquetecargos() != null) {
            sql.SET("IDDISQUETECARGOS = #{record.iddisquetecargos,jdbcType=DECIMAL}");
        }
        
        if (record.getIdfacturaincluidaendisquete() != null) {
            sql.SET("IDFACTURAINCLUIDAENDISQUETE = #{record.idfacturaincluidaendisquete,jdbcType=DECIMAL}");
        }
        
        if (record.getFechamodificacion() != null) {
            sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUsumodificacion() != null) {
            sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=DECIMAL}");
        }
        
        if (record.getDescripcionmotivos() != null) {
            sql.SET("DESCRIPCIONMOTIVOS = #{record.descripcionmotivos,jdbcType=VARCHAR}");
        }
        
        if (record.getGastosdevolucion() != null) {
            sql.SET("GASTOSDEVOLUCION = #{record.gastosdevolucion,jdbcType=DECIMAL}");
        }
        
        if (record.getCargarcliente() != null) {
            sql.SET("CARGARCLIENTE = #{record.cargarcliente,jdbcType=VARCHAR}");
        }
        
        if (record.getContabilizada() != null) {
            sql.SET("CONTABILIZADA = #{record.contabilizada,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.FAC_LINEADEVOLUDISQBANCO
     *
     * @mbg.generated Wed Jan 12 17:13:18 CET 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("FAC_LINEADEVOLUDISQBANCO");
        
        sql.SET("IDINSTITUCION = #{record.idinstitucion,jdbcType=DECIMAL}");
        sql.SET("IDDISQUETEDEVOLUCIONES = #{record.iddisquetedevoluciones,jdbcType=DECIMAL}");
        sql.SET("IDRECIBO = #{record.idrecibo,jdbcType=VARCHAR}");
        sql.SET("IDDISQUETECARGOS = #{record.iddisquetecargos,jdbcType=DECIMAL}");
        sql.SET("IDFACTURAINCLUIDAENDISQUETE = #{record.idfacturaincluidaendisquete,jdbcType=DECIMAL}");
        sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=TIMESTAMP}");
        sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=DECIMAL}");
        sql.SET("DESCRIPCIONMOTIVOS = #{record.descripcionmotivos,jdbcType=VARCHAR}");
        sql.SET("GASTOSDEVOLUCION = #{record.gastosdevolucion,jdbcType=DECIMAL}");
        sql.SET("CARGARCLIENTE = #{record.cargarcliente,jdbcType=VARCHAR}");
        sql.SET("CONTABILIZADA = #{record.contabilizada,jdbcType=VARCHAR}");
        
        FacLineadevoludisqbancoExample example = (FacLineadevoludisqbancoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.FAC_LINEADEVOLUDISQBANCO
     *
     * @mbg.generated Wed Jan 12 17:13:18 CET 2022
     */
    public String updateByPrimaryKeySelective(FacLineadevoludisqbanco record) {
        SQL sql = new SQL();
        sql.UPDATE("FAC_LINEADEVOLUDISQBANCO");
        
        if (record.getIddisquetecargos() != null) {
            sql.SET("IDDISQUETECARGOS = #{iddisquetecargos,jdbcType=DECIMAL}");
        }
        
        if (record.getIdfacturaincluidaendisquete() != null) {
            sql.SET("IDFACTURAINCLUIDAENDISQUETE = #{idfacturaincluidaendisquete,jdbcType=DECIMAL}");
        }
        
        if (record.getFechamodificacion() != null) {
            sql.SET("FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUsumodificacion() != null) {
            sql.SET("USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}");
        }
        
        if (record.getDescripcionmotivos() != null) {
            sql.SET("DESCRIPCIONMOTIVOS = #{descripcionmotivos,jdbcType=VARCHAR}");
        }
        
        if (record.getGastosdevolucion() != null) {
            sql.SET("GASTOSDEVOLUCION = #{gastosdevolucion,jdbcType=DECIMAL}");
        }
        
        if (record.getCargarcliente() != null) {
            sql.SET("CARGARCLIENTE = #{cargarcliente,jdbcType=VARCHAR}");
        }
        
        if (record.getContabilizada() != null) {
            sql.SET("CONTABILIZADA = #{contabilizada,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}");
        sql.WHERE("IDDISQUETEDEVOLUCIONES = #{iddisquetedevoluciones,jdbcType=DECIMAL}");
        sql.WHERE("IDRECIBO = #{idrecibo,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.FAC_LINEADEVOLUDISQBANCO
     *
     * @mbg.generated Wed Jan 12 17:13:18 CET 2022
     */
    protected void applyWhere(SQL sql, FacLineadevoludisqbancoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}