package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.FcsDestinatariosRetenciones;
import org.itcgae.siga.db.entities.FcsDestinatariosRetencionesExample;
import org.itcgae.siga.db.entities.FcsDestinatariosRetencionesKey;

public interface FcsDestinatariosRetencionesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @SelectProvider(type=FcsDestinatariosRetencionesSqlProvider.class, method="countByExample")
    long countByExample(FcsDestinatariosRetencionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @DeleteProvider(type=FcsDestinatariosRetencionesSqlProvider.class, method="deleteByExample")
    int deleteByExample(FcsDestinatariosRetencionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @Delete({
        "delete from FCS_DESTINATARIOS_RETENCIONES",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDDESTINATARIO = #{iddestinatario,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(FcsDestinatariosRetencionesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @Insert({
        "insert into FCS_DESTINATARIOS_RETENCIONES (IDINSTITUCION, IDDESTINATARIO, ",
        "NOMBRE, FECHAMODIFICACION, ",
        "USUMODIFICACION, CODIGOEXT, ",
        "BLOQUEADO, CUENTACONTABLE, ",
        "ORDEN, FECHABAJA)",
        "values (#{idinstitucion,jdbcType=DECIMAL}, #{iddestinatario,jdbcType=DECIMAL}, ",
        "#{nombre,jdbcType=VARCHAR}, #{fechamodificacion,jdbcType=TIMESTAMP}, ",
        "#{usumodificacion,jdbcType=DECIMAL}, #{codigoext,jdbcType=VARCHAR}, ",
        "#{bloqueado,jdbcType=CHAR}, #{cuentacontable,jdbcType=VARCHAR}, ",
        "#{orden,jdbcType=DECIMAL}, #{fechabaja,jdbcType=TIMESTAMP})"
    })
    int insert(FcsDestinatariosRetenciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @InsertProvider(type=FcsDestinatariosRetencionesSqlProvider.class, method="insertSelective")
    int insertSelective(FcsDestinatariosRetenciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @SelectProvider(type=FcsDestinatariosRetencionesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDDESTINATARIO", property="iddestinatario", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NOMBRE", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="CODIGOEXT", property="codigoext", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOQUEADO", property="bloqueado", jdbcType=JdbcType.CHAR),
        @Result(column="CUENTACONTABLE", property="cuentacontable", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORDEN", property="orden", jdbcType=JdbcType.DECIMAL),
        @Result(column="FECHABAJA", property="fechabaja", jdbcType=JdbcType.TIMESTAMP)
    })
    List<FcsDestinatariosRetenciones> selectByExample(FcsDestinatariosRetencionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @Select({
        "select",
        "IDINSTITUCION, IDDESTINATARIO, NOMBRE, FECHAMODIFICACION, USUMODIFICACION, CODIGOEXT, ",
        "BLOQUEADO, CUENTACONTABLE, ORDEN, FECHABAJA",
        "from FCS_DESTINATARIOS_RETENCIONES",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDDESTINATARIO = #{iddestinatario,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDDESTINATARIO", property="iddestinatario", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NOMBRE", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="CODIGOEXT", property="codigoext", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOQUEADO", property="bloqueado", jdbcType=JdbcType.CHAR),
        @Result(column="CUENTACONTABLE", property="cuentacontable", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORDEN", property="orden", jdbcType=JdbcType.DECIMAL),
        @Result(column="FECHABAJA", property="fechabaja", jdbcType=JdbcType.TIMESTAMP)
    })
    FcsDestinatariosRetenciones selectByPrimaryKey(FcsDestinatariosRetencionesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @UpdateProvider(type=FcsDestinatariosRetencionesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") FcsDestinatariosRetenciones record, @Param("example") FcsDestinatariosRetencionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @UpdateProvider(type=FcsDestinatariosRetencionesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") FcsDestinatariosRetenciones record, @Param("example") FcsDestinatariosRetencionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @UpdateProvider(type=FcsDestinatariosRetencionesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(FcsDestinatariosRetenciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_DESTINATARIOS_RETENCIONES
     *
     * @mbg.generated Thu Oct 10 13:24:48 CEST 2019
     */
    @Update({
        "update FCS_DESTINATARIOS_RETENCIONES",
        "set NOMBRE = #{nombre,jdbcType=VARCHAR},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
          "CODIGOEXT = #{codigoext,jdbcType=VARCHAR},",
          "BLOQUEADO = #{bloqueado,jdbcType=CHAR},",
          "CUENTACONTABLE = #{cuentacontable,jdbcType=VARCHAR},",
          "ORDEN = #{orden,jdbcType=DECIMAL},",
          "FECHABAJA = #{fechabaja,jdbcType=TIMESTAMP}",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDDESTINATARIO = #{iddestinatario,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(FcsDestinatariosRetenciones record);
}