package org.itcgae.siga.db.mappers;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.db.entities.FcsJeCertanexoEstado;
import org.itcgae.siga.db.entities.FcsJeCertanexoEstadoExample.Criteria;
import org.itcgae.siga.db.entities.FcsJeCertanexoEstadoExample.Criterion;
import org.itcgae.siga.db.entities.FcsJeCertanexoEstadoExample;

public class FcsJeCertanexoEstadoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_JE_CERTANEXO_ESTADO
	 * @mbg.generated  Mon Dec 20 09:00:12 CET 2021
	 */
	public String countByExample(FcsJeCertanexoEstadoExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("FCS_JE_CERTANEXO_ESTADO");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_JE_CERTANEXO_ESTADO
	 * @mbg.generated  Mon Dec 20 09:00:12 CET 2021
	 */
	public String deleteByExample(FcsJeCertanexoEstadoExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("FCS_JE_CERTANEXO_ESTADO");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_JE_CERTANEXO_ESTADO
	 * @mbg.generated  Mon Dec 20 09:00:12 CET 2021
	 */
	public String insertSelective(FcsJeCertanexoEstado record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("FCS_JE_CERTANEXO_ESTADO");
		sql.VALUES("IDCERTIFICACIONANEXOESTADO", "#{idcertificacionanexoestado,jdbcType=DECIMAL}");
		if (record.getIdcertificacionanexo() != null) {
			sql.VALUES("IDCERTIFICACIONANEXO", "#{idcertificacionanexo,jdbcType=DECIMAL}");
		}
		if (record.getIdestado() != null) {
			sql.VALUES("IDESTADO", "#{idestado,jdbcType=DECIMAL}");
		}
		if (record.getIdjeintercambio() != null) {
			sql.VALUES("IDJEINTERCAMBIO", "#{idjeintercambio,jdbcType=DECIMAL}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_JE_CERTANEXO_ESTADO
	 * @mbg.generated  Mon Dec 20 09:00:12 CET 2021
	 */
	public String selectByExample(FcsJeCertanexoEstadoExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("IDCERTIFICACIONANEXOESTADO");
		} else {
			sql.SELECT("IDCERTIFICACIONANEXOESTADO");
		}
		sql.SELECT("IDCERTIFICACIONANEXO");
		sql.SELECT("IDESTADO");
		sql.SELECT("IDJEINTERCAMBIO");
		sql.FROM("FCS_JE_CERTANEXO_ESTADO");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_JE_CERTANEXO_ESTADO
	 * @mbg.generated  Mon Dec 20 09:00:12 CET 2021
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		FcsJeCertanexoEstado record = (FcsJeCertanexoEstado) parameter.get("record");
		FcsJeCertanexoEstadoExample example = (FcsJeCertanexoEstadoExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("FCS_JE_CERTANEXO_ESTADO");
		if (record.getIdcertificacionanexoestado() != null) {
			sql.SET("IDCERTIFICACIONANEXOESTADO = #{record.idcertificacionanexoestado,jdbcType=DECIMAL}");
		}
		if (record.getIdcertificacionanexo() != null) {
			sql.SET("IDCERTIFICACIONANEXO = #{record.idcertificacionanexo,jdbcType=DECIMAL}");
		}
		if (record.getIdestado() != null) {
			sql.SET("IDESTADO = #{record.idestado,jdbcType=DECIMAL}");
		}
		if (record.getIdjeintercambio() != null) {
			sql.SET("IDJEINTERCAMBIO = #{record.idjeintercambio,jdbcType=DECIMAL}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_JE_CERTANEXO_ESTADO
	 * @mbg.generated  Mon Dec 20 09:00:12 CET 2021
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("FCS_JE_CERTANEXO_ESTADO");
		sql.SET("IDCERTIFICACIONANEXOESTADO = #{record.idcertificacionanexoestado,jdbcType=DECIMAL}");
		sql.SET("IDCERTIFICACIONANEXO = #{record.idcertificacionanexo,jdbcType=DECIMAL}");
		sql.SET("IDESTADO = #{record.idestado,jdbcType=DECIMAL}");
		sql.SET("IDJEINTERCAMBIO = #{record.idjeintercambio,jdbcType=DECIMAL}");
		FcsJeCertanexoEstadoExample example = (FcsJeCertanexoEstadoExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_JE_CERTANEXO_ESTADO
	 * @mbg.generated  Mon Dec 20 09:00:12 CET 2021
	 */
	public String updateByPrimaryKeySelective(FcsJeCertanexoEstado record) {
		SQL sql = new SQL();
		sql.UPDATE("FCS_JE_CERTANEXO_ESTADO");
		if (record.getIdcertificacionanexo() != null) {
			sql.SET("IDCERTIFICACIONANEXO = #{idcertificacionanexo,jdbcType=DECIMAL}");
		}
		if (record.getIdestado() != null) {
			sql.SET("IDESTADO = #{idestado,jdbcType=DECIMAL}");
		}
		if (record.getIdjeintercambio() != null) {
			sql.SET("IDJEINTERCAMBIO = #{idjeintercambio,jdbcType=DECIMAL}");
		}
		sql.WHERE("IDCERTIFICACIONANEXOESTADO = #{idcertificacionanexoestado,jdbcType=DECIMAL}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_JE_CERTANEXO_ESTADO
	 * @mbg.generated  Mon Dec 20 09:00:12 CET 2021
	 */
	protected void applyWhere(SQL sql, FcsJeCertanexoEstadoExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}