package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.FcsJeIntercambios;
import org.itcgae.siga.db.entities.FcsJeIntercambiosExample;

public interface FcsJeIntercambiosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @SelectProvider(type=FcsJeIntercambiosSqlProvider.class, method="countByExample")
    long countByExample(FcsJeIntercambiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @DeleteProvider(type=FcsJeIntercambiosSqlProvider.class, method="deleteByExample")
    int deleteByExample(FcsJeIntercambiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @Delete({
        "delete from FCS_JE_INTERCAMBIOS",
        "where IDINTERCAMBIO = #{idintercambio,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long idintercambio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @Insert({
        "insert into FCS_JE_INTERCAMBIOS (IDINTERCAMBIO, IDINSTITUCION, ",
        "DESCRIPCION, IDPERIODO, ",
        "ANIO, IDESTADO, ",
        "FECHAMODIFICACION, USUMODIFICACION)",
        "values (#{idintercambio,jdbcType=DECIMAL}, #{idinstitucion,jdbcType=DECIMAL}, ",
        "#{descripcion,jdbcType=VARCHAR}, #{idperiodo,jdbcType=DECIMAL}, ",
        "#{anio,jdbcType=DECIMAL}, #{idestado,jdbcType=DECIMAL}, ",
        "#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL})"
    })
    @SelectKey(statement="SELECT SEQ_FCS_JE_INTERCAMBIOS.NEXTVAL FROM DUAL", keyProperty="idintercambio", before=true, resultType=Long.class)
    int insert(FcsJeIntercambios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @InsertProvider(type=FcsJeIntercambiosSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT SEQ_FCS_JE_INTERCAMBIOS.NEXTVAL FROM DUAL", keyProperty="idintercambio", before=true, resultType=Long.class)
    int insertSelective(FcsJeIntercambios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @SelectProvider(type=FcsJeIntercambiosSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDINTERCAMBIO", property="idintercambio", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDPERIODO", property="idperiodo", jdbcType=JdbcType.DECIMAL),
        @Result(column="ANIO", property="anio", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDESTADO", property="idestado", jdbcType=JdbcType.DECIMAL),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)
    })
    List<FcsJeIntercambios> selectByExample(FcsJeIntercambiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @Select({
        "select",
        "IDINTERCAMBIO, IDINSTITUCION, DESCRIPCION, IDPERIODO, ANIO, IDESTADO, FECHAMODIFICACION, ",
        "USUMODIFICACION",
        "from FCS_JE_INTERCAMBIOS",
        "where IDINTERCAMBIO = #{idintercambio,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDINTERCAMBIO", property="idintercambio", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDPERIODO", property="idperiodo", jdbcType=JdbcType.DECIMAL),
        @Result(column="ANIO", property="anio", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDESTADO", property="idestado", jdbcType=JdbcType.DECIMAL),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)
    })
    FcsJeIntercambios selectByPrimaryKey(Long idintercambio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @UpdateProvider(type=FcsJeIntercambiosSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") FcsJeIntercambios record, @Param("example") FcsJeIntercambiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @UpdateProvider(type=FcsJeIntercambiosSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") FcsJeIntercambios record, @Param("example") FcsJeIntercambiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @UpdateProvider(type=FcsJeIntercambiosSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(FcsJeIntercambios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.FCS_JE_INTERCAMBIOS
     *
     * @mbg.generated Fri Dec 17 11:59:23 CET 2021
     */
    @Update({
        "update FCS_JE_INTERCAMBIOS",
        "set IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL},",
          "DESCRIPCION = #{descripcion,jdbcType=VARCHAR},",
          "IDPERIODO = #{idperiodo,jdbcType=DECIMAL},",
          "ANIO = #{anio,jdbcType=DECIMAL},",
          "IDESTADO = #{idestado,jdbcType=DECIMAL},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}",
        "where IDINTERCAMBIO = #{idintercambio,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(FcsJeIntercambios record);
}