package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.FcsPagoGrupofactHito;
import org.itcgae.siga.db.entities.FcsPagoGrupofactHitoExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.itcgae.siga.db.entities.FcsPagoGrupofactHitoKey;

public interface FcsPagoGrupofactHitoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@SelectProvider(type=FcsPagoGrupofactHitoSqlProvider.class, method="countByExample") long countByExample(FcsPagoGrupofactHitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@DeleteProvider(type=FcsPagoGrupofactHitoSqlProvider.class, method="deleteByExample") int deleteByExample(FcsPagoGrupofactHitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@Delete({"delete from FCS_PAGO_GRUPOFACT_HITO","where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}","and IDPAGOSJG = #{idpagosjg,jdbcType=DECIMAL}","and IDGRUPOFACTURACION = #{idgrupofacturacion,jdbcType=DECIMAL}","and IDHITOGENERAL = #{idhitogeneral,jdbcType=DECIMAL}"}) int deleteByPrimaryKey(FcsPagoGrupofactHitoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@Insert({"insert into FCS_PAGO_GRUPOFACT_HITO (IDINSTITUCION, IDPAGOSJG, ","IDGRUPOFACTURACION, IDHITOGENERAL, ","FECHAMODIFICACION, USUMODIFICACION)","values (#{idinstitucion,jdbcType=DECIMAL}, #{idpagosjg,jdbcType=DECIMAL}, ","#{idgrupofacturacion,jdbcType=DECIMAL}, #{idhitogeneral,jdbcType=DECIMAL}, ","#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL})"}) int insert(FcsPagoGrupofactHito record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@InsertProvider(type=FcsPagoGrupofactHitoSqlProvider.class, method="insertSelective") int insertSelective(FcsPagoGrupofactHito record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@SelectProvider(type=FcsPagoGrupofactHitoSqlProvider.class, method="selectByExample") @Results({@Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),@Result(column="IDPAGOSJG", property="idpagosjg", jdbcType=JdbcType.DECIMAL, id=true),@Result(column="IDGRUPOFACTURACION", property="idgrupofacturacion", jdbcType=JdbcType.DECIMAL, id=true),@Result(column="IDHITOGENERAL", property="idhitogeneral", jdbcType=JdbcType.DECIMAL, id=true),@Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),@Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)}) List<FcsPagoGrupofactHito> selectByExample(FcsPagoGrupofactHitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@Select({"select","IDINSTITUCION, IDPAGOSJG, IDGRUPOFACTURACION, IDHITOGENERAL, FECHAMODIFICACION, ","USUMODIFICACION","from FCS_PAGO_GRUPOFACT_HITO","where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}","and IDPAGOSJG = #{idpagosjg,jdbcType=DECIMAL}","and IDGRUPOFACTURACION = #{idgrupofacturacion,jdbcType=DECIMAL}","and IDHITOGENERAL = #{idhitogeneral,jdbcType=DECIMAL}"}) @Results({@Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),@Result(column="IDPAGOSJG", property="idpagosjg", jdbcType=JdbcType.DECIMAL, id=true),@Result(column="IDGRUPOFACTURACION", property="idgrupofacturacion", jdbcType=JdbcType.DECIMAL, id=true),@Result(column="IDHITOGENERAL", property="idhitogeneral", jdbcType=JdbcType.DECIMAL, id=true),@Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),@Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)}) FcsPagoGrupofactHito selectByPrimaryKey(FcsPagoGrupofactHitoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@UpdateProvider(type=FcsPagoGrupofactHitoSqlProvider.class, method="updateByExampleSelective") int updateByExampleSelective(@Param("record") FcsPagoGrupofactHito record,@Param("example") FcsPagoGrupofactHitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@UpdateProvider(type=FcsPagoGrupofactHitoSqlProvider.class, method="updateByExample") int updateByExample(@Param("record") FcsPagoGrupofactHito record,@Param("example") FcsPagoGrupofactHitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@UpdateProvider(type=FcsPagoGrupofactHitoSqlProvider.class, method="updateByPrimaryKeySelective") int updateByPrimaryKeySelective(FcsPagoGrupofactHito record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.FCS_PAGO_GRUPOFACT_HITO
	 * @mbg.generated  Mon Jul 19 14:35:43 CEST 2021
	 */@Update({"update FCS_PAGO_GRUPOFACT_HITO","set FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},","USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}","where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}","and IDPAGOSJG = #{idpagosjg,jdbcType=DECIMAL}","and IDGRUPOFACTURACION = #{idgrupofacturacion,jdbcType=DECIMAL}","and IDHITOGENERAL = #{idhitogeneral,jdbcType=DECIMAL}"}) int updateByPrimaryKey(FcsPagoGrupofactHito record);
}