package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.FcsRetencionesJudiciales;
import org.itcgae.siga.db.entities.FcsRetencionesJudicialesExample;
import org.itcgae.siga.db.entities.FcsRetencionesJudicialesKey;

public interface FcsRetencionesJudicialesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@SelectProvider(type = FcsRetencionesJudicialesSqlProvider.class, method = "countByExample")
	long countByExample(FcsRetencionesJudicialesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@DeleteProvider(type = FcsRetencionesJudicialesSqlProvider.class, method = "deleteByExample")
	int deleteByExample(FcsRetencionesJudicialesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@Delete({ "delete from FCS_RETENCIONES_JUDICIALES", "where IDINSTITUCION = #{idinstitucion,jdbcType=NUMERIC}",
			"and IDRETENCION = #{idretencion,jdbcType=NUMERIC}" })
	int deleteByPrimaryKey(FcsRetencionesJudicialesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@Insert({ "insert into FCS_RETENCIONES_JUDICIALES (IDINSTITUCION, IDRETENCION, ", "IDPERSONA, IDDESTINATARIO, ",
			"FECHAALTA, FECHAINICIO, ", "FECHAFIN, TIPORETENCION, ", "IMPORTE, OBSERVACIONES, ",
			"FECHAMODIFICACION, USUMODIFICACION, ", "CONTABILIZADO, ESDETURNO, ", "DESCDESTINATARIO)",
			"values (#{idinstitucion,jdbcType=NUMERIC}, #{idretencion,jdbcType=NUMERIC}, ",
			"#{idpersona,jdbcType=NUMERIC}, #{iddestinatario,jdbcType=NUMERIC}, ",
			"#{fechaalta,jdbcType=TIMESTAMP}, #{fechainicio,jdbcType=TIMESTAMP}, ",
			"#{fechafin,jdbcType=TIMESTAMP}, #{tiporetencion,jdbcType=VARCHAR}, ",
			"#{importe,jdbcType=NUMERIC}, #{observaciones,jdbcType=VARCHAR}, ",
			"#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=NUMERIC}, ",
			"#{contabilizado,jdbcType=VARCHAR}, #{esdeturno,jdbcType=VARCHAR}, ",
			"#{descdestinatario,jdbcType=VARCHAR})" })
	int insert(FcsRetencionesJudiciales row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@InsertProvider(type = FcsRetencionesJudicialesSqlProvider.class, method = "insertSelective")
	int insertSelective(FcsRetencionesJudiciales row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@SelectProvider(type = FcsRetencionesJudicialesSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.NUMERIC, id = true),
			@Result(column = "IDRETENCION", property = "idretencion", jdbcType = JdbcType.NUMERIC, id = true),
			@Result(column = "IDPERSONA", property = "idpersona", jdbcType = JdbcType.NUMERIC),
			@Result(column = "IDDESTINATARIO", property = "iddestinatario", jdbcType = JdbcType.NUMERIC),
			@Result(column = "FECHAALTA", property = "fechaalta", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "FECHAINICIO", property = "fechainicio", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "FECHAFIN", property = "fechafin", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "TIPORETENCION", property = "tiporetencion", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IMPORTE", property = "importe", jdbcType = JdbcType.NUMERIC),
			@Result(column = "OBSERVACIONES", property = "observaciones", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.NUMERIC),
			@Result(column = "CONTABILIZADO", property = "contabilizado", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ESDETURNO", property = "esdeturno", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DESCDESTINATARIO", property = "descdestinatario", jdbcType = JdbcType.VARCHAR) })
	List<FcsRetencionesJudiciales> selectByExample(FcsRetencionesJudicialesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@Select({ "select", "IDINSTITUCION, IDRETENCION, IDPERSONA, IDDESTINATARIO, FECHAALTA, FECHAINICIO, ",
			"FECHAFIN, TIPORETENCION, IMPORTE, OBSERVACIONES, FECHAMODIFICACION, USUMODIFICACION, ",
			"CONTABILIZADO, ESDETURNO, DESCDESTINATARIO", "from FCS_RETENCIONES_JUDICIALES",
			"where IDINSTITUCION = #{idinstitucion,jdbcType=NUMERIC}",
			"and IDRETENCION = #{idretencion,jdbcType=NUMERIC}" })
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.NUMERIC, id = true),
			@Result(column = "IDRETENCION", property = "idretencion", jdbcType = JdbcType.NUMERIC, id = true),
			@Result(column = "IDPERSONA", property = "idpersona", jdbcType = JdbcType.NUMERIC),
			@Result(column = "IDDESTINATARIO", property = "iddestinatario", jdbcType = JdbcType.NUMERIC),
			@Result(column = "FECHAALTA", property = "fechaalta", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "FECHAINICIO", property = "fechainicio", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "FECHAFIN", property = "fechafin", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "TIPORETENCION", property = "tiporetencion", jdbcType = JdbcType.VARCHAR),
			@Result(column = "IMPORTE", property = "importe", jdbcType = JdbcType.NUMERIC),
			@Result(column = "OBSERVACIONES", property = "observaciones", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.NUMERIC),
			@Result(column = "CONTABILIZADO", property = "contabilizado", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ESDETURNO", property = "esdeturno", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DESCDESTINATARIO", property = "descdestinatario", jdbcType = JdbcType.VARCHAR) })
	FcsRetencionesJudiciales selectByPrimaryKey(FcsRetencionesJudicialesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@UpdateProvider(type = FcsRetencionesJudicialesSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("row") FcsRetencionesJudiciales row,
			@Param("example") FcsRetencionesJudicialesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@UpdateProvider(type = FcsRetencionesJudicialesSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("row") FcsRetencionesJudiciales row,
			@Param("example") FcsRetencionesJudicialesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@UpdateProvider(type = FcsRetencionesJudicialesSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(FcsRetencionesJudiciales row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.FCS_RETENCIONES_JUDICIALES
	 * @mbg.generated  Tue Oct 25 21:00:49 CEST 2022
	 */
	@Update({ "update FCS_RETENCIONES_JUDICIALES", "set IDPERSONA = #{idpersona,jdbcType=NUMERIC},",
			"IDDESTINATARIO = #{iddestinatario,jdbcType=NUMERIC},", "FECHAALTA = #{fechaalta,jdbcType=TIMESTAMP},",
			"FECHAINICIO = #{fechainicio,jdbcType=TIMESTAMP},", "FECHAFIN = #{fechafin,jdbcType=TIMESTAMP},",
			"TIPORETENCION = #{tiporetencion,jdbcType=VARCHAR},", "IMPORTE = #{importe,jdbcType=NUMERIC},",
			"OBSERVACIONES = #{observaciones,jdbcType=VARCHAR},",
			"FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
			"USUMODIFICACION = #{usumodificacion,jdbcType=NUMERIC},",
			"CONTABILIZADO = #{contabilizado,jdbcType=VARCHAR},", "ESDETURNO = #{esdeturno,jdbcType=VARCHAR},",
			"DESCDESTINATARIO = #{descdestinatario,jdbcType=VARCHAR}",
			"where IDINSTITUCION = #{idinstitucion,jdbcType=NUMERIC}",
			"and IDRETENCION = #{idretencion,jdbcType=NUMERIC}" })
	int updateByPrimaryKey(FcsRetencionesJudiciales row);
}