package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.GenPeriodo;
import org.itcgae.siga.db.entities.GenPeriodoExample;

public interface GenPeriodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @SelectProvider(type=GenPeriodoSqlProvider.class, method="countByExample")
    long countByExample(GenPeriodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @DeleteProvider(type=GenPeriodoSqlProvider.class, method="deleteByExample")
    int deleteByExample(GenPeriodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @Delete({
        "delete from GEN_PERIODO",
        "where IDPERIODO = #{idperiodo,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Short idperiodo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @Insert({
        "insert into GEN_PERIODO (IDPERIODO, NOMBRE, ",
        "DIAINICIO, MESINICIO, ",
        "ANIOINICIO, DIAFIN, ",
        "MESFIN, ANIOFIN)",
        "values (#{idperiodo,jdbcType=DECIMAL}, #{nombre,jdbcType=VARCHAR}, ",
        "#{diainicio,jdbcType=DECIMAL}, #{mesinicio,jdbcType=DECIMAL}, ",
        "#{anioinicio,jdbcType=DECIMAL}, #{diafin,jdbcType=DECIMAL}, ",
        "#{mesfin,jdbcType=DECIMAL}, #{aniofin,jdbcType=DECIMAL})"
    })
    int insert(GenPeriodo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @InsertProvider(type=GenPeriodoSqlProvider.class, method="insertSelective")
    int insertSelective(GenPeriodo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @SelectProvider(type=GenPeriodoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDPERIODO", property="idperiodo", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NOMBRE", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="DIAINICIO", property="diainicio", jdbcType=JdbcType.DECIMAL),
        @Result(column="MESINICIO", property="mesinicio", jdbcType=JdbcType.DECIMAL),
        @Result(column="ANIOINICIO", property="anioinicio", jdbcType=JdbcType.DECIMAL),
        @Result(column="DIAFIN", property="diafin", jdbcType=JdbcType.DECIMAL),
        @Result(column="MESFIN", property="mesfin", jdbcType=JdbcType.DECIMAL),
        @Result(column="ANIOFIN", property="aniofin", jdbcType=JdbcType.DECIMAL)
    })
    List<GenPeriodo> selectByExample(GenPeriodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @Select({
        "select",
        "IDPERIODO, NOMBRE, DIAINICIO, MESINICIO, ANIOINICIO, DIAFIN, MESFIN, ANIOFIN",
        "from GEN_PERIODO",
        "where IDPERIODO = #{idperiodo,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDPERIODO", property="idperiodo", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NOMBRE", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="DIAINICIO", property="diainicio", jdbcType=JdbcType.DECIMAL),
        @Result(column="MESINICIO", property="mesinicio", jdbcType=JdbcType.DECIMAL),
        @Result(column="ANIOINICIO", property="anioinicio", jdbcType=JdbcType.DECIMAL),
        @Result(column="DIAFIN", property="diafin", jdbcType=JdbcType.DECIMAL),
        @Result(column="MESFIN", property="mesfin", jdbcType=JdbcType.DECIMAL),
        @Result(column="ANIOFIN", property="aniofin", jdbcType=JdbcType.DECIMAL)
    })
    GenPeriodo selectByPrimaryKey(Short idperiodo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @UpdateProvider(type=GenPeriodoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GenPeriodo record, @Param("example") GenPeriodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @UpdateProvider(type=GenPeriodoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GenPeriodo record, @Param("example") GenPeriodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @UpdateProvider(type=GenPeriodoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GenPeriodo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_DESA.GEN_PERIODO
     *
     * @mbg.generated Wed Mar 14 18:23:45 CET 2018
     */
    @Update({
        "update GEN_PERIODO",
        "set NOMBRE = #{nombre,jdbcType=VARCHAR},",
          "DIAINICIO = #{diainicio,jdbcType=DECIMAL},",
          "MESINICIO = #{mesinicio,jdbcType=DECIMAL},",
          "ANIOINICIO = #{anioinicio,jdbcType=DECIMAL},",
          "DIAFIN = #{diafin,jdbcType=DECIMAL},",
          "MESFIN = #{mesfin,jdbcType=DECIMAL},",
          "ANIOFIN = #{aniofin,jdbcType=DECIMAL}",
        "where IDPERIODO = #{idperiodo,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(GenPeriodo record);
}