package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.GenParametros;
import org.itcgae.siga.db.entities.GenParametrosExample;
import org.itcgae.siga.db.entities.GenParametrosKey;

public interface GenParametrosMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@SelectProvider(type = GenParametrosSqlProvider.class, method = "countByExample")
	long countByExample(GenParametrosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@DeleteProvider(type = GenParametrosSqlProvider.class, method = "deleteByExample")
	int deleteByExample(GenParametrosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@Delete({ "delete from GEN_PARAMETROS", "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
			"and MODULO = #{modulo,jdbcType=VARCHAR}", "and PARAMETRO = #{parametro,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(GenParametrosKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@Insert({ "insert into GEN_PARAMETROS (IDINSTITUCION, MODULO, ", "PARAMETRO, VALOR, ",
			"FECHAMODIFICACION, USUMODIFICACION, ", "IDRECURSO, FECHA_BAJA)",
			"values (#{idinstitucion,jdbcType=DECIMAL}, #{modulo,jdbcType=VARCHAR}, ",
			"#{parametro,jdbcType=VARCHAR}, #{valor,jdbcType=VARCHAR}, ",
			"#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL}, ",
			"#{idrecurso,jdbcType=VARCHAR}, #{fechaBaja,jdbcType=TIMESTAMP})" })
	int insert(GenParametros record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@InsertProvider(type = GenParametrosSqlProvider.class, method = "insertSelective")
	int insertSelective(GenParametros record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@SelectProvider(type = GenParametrosSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "MODULO", property = "modulo", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "PARAMETRO", property = "parametro", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "VALOR", property = "valor", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "IDRECURSO", property = "idrecurso", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHA_BAJA", property = "fechaBaja", jdbcType = JdbcType.TIMESTAMP) })
	List<GenParametros> selectByExample(GenParametrosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@Select({ "select", "IDINSTITUCION, MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, ",
			"IDRECURSO, FECHA_BAJA", "from GEN_PARAMETROS", "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
			"and MODULO = #{modulo,jdbcType=VARCHAR}", "and PARAMETRO = #{parametro,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "MODULO", property = "modulo", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "PARAMETRO", property = "parametro", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "VALOR", property = "valor", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "IDRECURSO", property = "idrecurso", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHA_BAJA", property = "fechaBaja", jdbcType = JdbcType.TIMESTAMP) })
	GenParametros selectByPrimaryKey(GenParametrosKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@UpdateProvider(type = GenParametrosSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") GenParametros record, @Param("example") GenParametrosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@UpdateProvider(type = GenParametrosSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") GenParametros record, @Param("example") GenParametrosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@UpdateProvider(type = GenParametrosSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(GenParametros record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.GEN_PARAMETROS
	 * @mbg.generated  Thu Apr 12 14:22:35 CEST 2018
	 */
	@Update({ "update GEN_PARAMETROS", "set VALOR = #{valor,jdbcType=VARCHAR},",
			"FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
			"USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},", "IDRECURSO = #{idrecurso,jdbcType=VARCHAR},",
			"FECHA_BAJA = #{fechaBaja,jdbcType=TIMESTAMP}", "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
			"and MODULO = #{modulo,jdbcType=VARCHAR}", "and PARAMETRO = #{parametro,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(GenParametros record);
}