package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.JeCertanexoValerroneo;
import org.itcgae.siga.db.entities.JeCertanexoValerroneoExample;

public interface JeCertanexoValerroneoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @SelectProvider(type=JeCertanexoValerroneoSqlProvider.class, method="countByExample")
    long countByExample(JeCertanexoValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @DeleteProvider(type=JeCertanexoValerroneoSqlProvider.class, method="deleteByExample")
    int deleteByExample(JeCertanexoValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @Delete({
        "delete from JE_CERTANEXO_VALERRONEO",
        "where IDJECERTANEXOVALERRONEO = #{idjecertanexovalerroneo,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long idjecertanexovalerroneo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @Insert({
        "insert into JE_CERTANEXO_VALERRONEO (IDJECERTANEXOVALERRONEO, IDCERTANEXOESTADO, ",
        "DESCERRORGENERAL)",
        "values (#{idjecertanexovalerroneo,jdbcType=DECIMAL}, #{idcertanexoestado,jdbcType=DECIMAL}, ",
        "#{descerrorgeneral,jdbcType=CLOB})"
    })
    @SelectKey(statement="SELECT SEQ_JE_CERTANEXO_VALERRONEO.NEXTVAL FROM DUAL", keyProperty="idjecertanexovalerroneo", before=true, resultType=Long.class)
    int insert(JeCertanexoValerroneo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @InsertProvider(type=JeCertanexoValerroneoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT SEQ_JE_CERTANEXO_VALERRONEO.NEXTVAL FROM DUAL", keyProperty="idjecertanexovalerroneo", before=true, resultType=Long.class)
    int insertSelective(JeCertanexoValerroneo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @SelectProvider(type=JeCertanexoValerroneoSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="IDJECERTANEXOVALERRONEO", property="idjecertanexovalerroneo", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDCERTANEXOESTADO", property="idcertanexoestado", jdbcType=JdbcType.DECIMAL),
        @Result(column="DESCERRORGENERAL", property="descerrorgeneral", jdbcType=JdbcType.CLOB)
    })
    List<JeCertanexoValerroneo> selectByExampleWithBLOBs(JeCertanexoValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @SelectProvider(type=JeCertanexoValerroneoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDJECERTANEXOVALERRONEO", property="idjecertanexovalerroneo", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDCERTANEXOESTADO", property="idcertanexoestado", jdbcType=JdbcType.DECIMAL)
    })
    List<JeCertanexoValerroneo> selectByExample(JeCertanexoValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @Select({
        "select",
        "IDJECERTANEXOVALERRONEO, IDCERTANEXOESTADO, DESCERRORGENERAL",
        "from JE_CERTANEXO_VALERRONEO",
        "where IDJECERTANEXOVALERRONEO = #{idjecertanexovalerroneo,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDJECERTANEXOVALERRONEO", property="idjecertanexovalerroneo", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDCERTANEXOESTADO", property="idcertanexoestado", jdbcType=JdbcType.DECIMAL),
        @Result(column="DESCERRORGENERAL", property="descerrorgeneral", jdbcType=JdbcType.CLOB)
    })
    JeCertanexoValerroneo selectByPrimaryKey(Long idjecertanexovalerroneo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @UpdateProvider(type=JeCertanexoValerroneoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") JeCertanexoValerroneo record, @Param("example") JeCertanexoValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @UpdateProvider(type=JeCertanexoValerroneoSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") JeCertanexoValerroneo record, @Param("example") JeCertanexoValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @UpdateProvider(type=JeCertanexoValerroneoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") JeCertanexoValerroneo record, @Param("example") JeCertanexoValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @UpdateProvider(type=JeCertanexoValerroneoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(JeCertanexoValerroneo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @Update({
        "update JE_CERTANEXO_VALERRONEO",
        "set IDCERTANEXOESTADO = #{idcertanexoestado,jdbcType=DECIMAL},",
          "DESCERRORGENERAL = #{descerrorgeneral,jdbcType=CLOB}",
        "where IDJECERTANEXOVALERRONEO = #{idjecertanexovalerroneo,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKeyWithBLOBs(JeCertanexoValerroneo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_CERTANEXO_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @Update({
        "update JE_CERTANEXO_VALERRONEO",
        "set IDCERTANEXOESTADO = #{idcertanexoestado,jdbcType=DECIMAL}",
        "where IDJECERTANEXOVALERRONEO = #{idjecertanexovalerroneo,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(JeCertanexoValerroneo record);
}