package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.JeDevValerroneo;
import org.itcgae.siga.db.entities.JeDevValerroneoExample;

public interface JeDevValerroneoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @SelectProvider(type=JeDevValerroneoSqlProvider.class, method="countByExample")
    long countByExample(JeDevValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @DeleteProvider(type=JeDevValerroneoSqlProvider.class, method="deleteByExample")
    int deleteByExample(JeDevValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @Delete({
        "delete from JE_DEV_VALERRONEO",
        "where IDJEDEVVALERRONEO = #{idjedevvalerroneo,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long idjedevvalerroneo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @Insert({
        "insert into JE_DEV_VALERRONEO (IDJEDEVVALERRONEO, IDDEVESTADO, ",
        "DESCERRORGENERAL)",
        "values (#{idjedevvalerroneo,jdbcType=DECIMAL}, #{iddevestado,jdbcType=DECIMAL}, ",
        "#{descerrorgeneral,jdbcType=CLOB})"
    })
    @SelectKey(statement="SELECT SEQ_JE_DEV_VALERRONEO.NEXTVAL FROM DUAL", keyProperty="idjedevvalerroneo", before=true, resultType=Long.class)
    int insert(JeDevValerroneo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @InsertProvider(type=JeDevValerroneoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT SEQ_JE_DEV_VALERRONEO.NEXTVAL FROM DUAL", keyProperty="idjedevvalerroneo", before=true, resultType=Long.class)
    int insertSelective(JeDevValerroneo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @SelectProvider(type=JeDevValerroneoSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="IDJEDEVVALERRONEO", property="idjedevvalerroneo", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDDEVESTADO", property="iddevestado", jdbcType=JdbcType.DECIMAL),
        @Result(column="DESCERRORGENERAL", property="descerrorgeneral", jdbcType=JdbcType.CLOB)
    })
    List<JeDevValerroneo> selectByExampleWithBLOBs(JeDevValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @SelectProvider(type=JeDevValerroneoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDJEDEVVALERRONEO", property="idjedevvalerroneo", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDDEVESTADO", property="iddevestado", jdbcType=JdbcType.DECIMAL)
    })
    List<JeDevValerroneo> selectByExample(JeDevValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @Select({
        "select",
        "IDJEDEVVALERRONEO, IDDEVESTADO, DESCERRORGENERAL",
        "from JE_DEV_VALERRONEO",
        "where IDJEDEVVALERRONEO = #{idjedevvalerroneo,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDJEDEVVALERRONEO", property="idjedevvalerroneo", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDDEVESTADO", property="iddevestado", jdbcType=JdbcType.DECIMAL),
        @Result(column="DESCERRORGENERAL", property="descerrorgeneral", jdbcType=JdbcType.CLOB)
    })
    JeDevValerroneo selectByPrimaryKey(Long idjedevvalerroneo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @UpdateProvider(type=JeDevValerroneoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") JeDevValerroneo record, @Param("example") JeDevValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @UpdateProvider(type=JeDevValerroneoSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") JeDevValerroneo record, @Param("example") JeDevValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @UpdateProvider(type=JeDevValerroneoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") JeDevValerroneo record, @Param("example") JeDevValerroneoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @UpdateProvider(type=JeDevValerroneoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(JeDevValerroneo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @Update({
        "update JE_DEV_VALERRONEO",
        "set IDDEVESTADO = #{iddevestado,jdbcType=DECIMAL},",
          "DESCERRORGENERAL = #{descerrorgeneral,jdbcType=CLOB}",
        "where IDJEDEVVALERRONEO = #{idjedevvalerroneo,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKeyWithBLOBs(JeDevValerroneo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.JE_DEV_VALERRONEO
     *
     * @mbg.generated Mon Dec 20 08:56:07 CET 2021
     */
    @Update({
        "update JE_DEV_VALERRONEO",
        "set IDDEVESTADO = #{iddevestado,jdbcType=DECIMAL}",
        "where IDJEDEVVALERRONEO = #{idjedevvalerroneo,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(JeDevValerroneo record);
}