package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ModClasecomunicaciones;
import org.itcgae.siga.db.entities.ModClasecomunicacionesExample;

public interface ModClasecomunicacionesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @SelectProvider(type=ModClasecomunicacionesSqlProvider.class, method="countByExample")
    long countByExample(ModClasecomunicacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @DeleteProvider(type=ModClasecomunicacionesSqlProvider.class, method="deleteByExample")
    int deleteByExample(ModClasecomunicacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @Delete({
        "delete from MOD_CLASECOMUNICACIONES",
        "where IDCLASECOMUNICACION = #{idclasecomunicacion,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Short idclasecomunicacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @Insert({
        "insert into MOD_CLASECOMUNICACIONES (IDCLASECOMUNICACION, NOMBRE, ",
        "DESCRIPCION, FECHAMODIFICACION, ",
        "USUMODIFICACION, IDMODULO)",
        "values (#{idclasecomunicacion,jdbcType=DECIMAL}, #{nombre,jdbcType=VARCHAR}, ",
        "#{descripcion,jdbcType=VARCHAR}, #{fechamodificacion,jdbcType=TIMESTAMP}, ",
        "#{usumodificacion,jdbcType=DECIMAL}, #{idmodulo,jdbcType=DECIMAL})"
    })
    int insert(ModClasecomunicaciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @InsertProvider(type=ModClasecomunicacionesSqlProvider.class, method="insertSelective")
    int insertSelective(ModClasecomunicaciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @SelectProvider(type=ModClasecomunicacionesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDCLASECOMUNICACION", property="idclasecomunicacion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NOMBRE", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDMODULO", property="idmodulo", jdbcType=JdbcType.DECIMAL)
    })
    List<ModClasecomunicaciones> selectByExample(ModClasecomunicacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @Select({
        "select",
        "IDCLASECOMUNICACION, NOMBRE, DESCRIPCION, FECHAMODIFICACION, USUMODIFICACION, ",
        "IDMODULO",
        "from MOD_CLASECOMUNICACIONES",
        "where IDCLASECOMUNICACION = #{idclasecomunicacion,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDCLASECOMUNICACION", property="idclasecomunicacion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NOMBRE", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDMODULO", property="idmodulo", jdbcType=JdbcType.DECIMAL)
    })
    ModClasecomunicaciones selectByPrimaryKey(Short idclasecomunicacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @UpdateProvider(type=ModClasecomunicacionesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ModClasecomunicaciones record, @Param("example") ModClasecomunicacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @UpdateProvider(type=ModClasecomunicacionesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ModClasecomunicaciones record, @Param("example") ModClasecomunicacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @UpdateProvider(type=ModClasecomunicacionesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ModClasecomunicaciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.MOD_CLASECOMUNICACIONES
     *
     * @mbg.generated Mon Dec 17 12:33:13 CET 2018
     */
    @Update({
        "update MOD_CLASECOMUNICACIONES",
        "set NOMBRE = #{nombre,jdbcType=VARCHAR},",
          "DESCRIPCION = #{descripcion,jdbcType=VARCHAR},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
          "IDMODULO = #{idmodulo,jdbcType=DECIMAL}",
        "where IDCLASECOMUNICACION = #{idclasecomunicacion,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(ModClasecomunicaciones record);
}