package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ModPlantillaenvioConsulta;
import org.itcgae.siga.db.entities.ModPlantillaenvioConsultaExample;
import org.itcgae.siga.db.entities.ModPlantillaenvioConsultaKey;

public interface ModPlantillaenvioConsultaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@SelectProvider(type = ModPlantillaenvioConsultaSqlProvider.class, method = "countByExample")
	long countByExample(ModPlantillaenvioConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@DeleteProvider(type = ModPlantillaenvioConsultaSqlProvider.class, method = "deleteByExample")
	int deleteByExample(ModPlantillaenvioConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@Delete({ "delete from MOD_PLANTILLAENVIO_CONSULTA",
			"where IDPLANTILLAENVIOS = #{idplantillaenvios,jdbcType=DECIMAL}",
			"and IDCONSULTA = #{idconsulta,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(ModPlantillaenvioConsultaKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@Insert({ "insert into MOD_PLANTILLAENVIO_CONSULTA (IDPLANTILLAENVIOS, IDCONSULTA, ",
			"FECHAMODIFICACION, USUMODIFICACION, ", "IDTIPOENVIOS, IDINSTITUCION, ", "FECHABAJA)",
			"values (#{idplantillaenvios,jdbcType=DECIMAL}, #{idconsulta,jdbcType=DECIMAL}, ",
			"#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL}, ",
			"#{idtipoenvios,jdbcType=DECIMAL}, #{idinstitucion,jdbcType=DECIMAL}, ",
			"#{fechabaja,jdbcType=TIMESTAMP})" })
	int insert(ModPlantillaenvioConsulta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@InsertProvider(type = ModPlantillaenvioConsultaSqlProvider.class, method = "insertSelective")
	int insertSelective(ModPlantillaenvioConsulta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@SelectProvider(type = ModPlantillaenvioConsultaSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "IDPLANTILLAENVIOS", property = "idplantillaenvios", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDCONSULTA", property = "idconsulta", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "IDTIPOENVIOS", property = "idtipoenvios", jdbcType = JdbcType.DECIMAL),
			@Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "FECHABAJA", property = "fechabaja", jdbcType = JdbcType.TIMESTAMP) })
	List<ModPlantillaenvioConsulta> selectByExample(ModPlantillaenvioConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@Select({ "select", "IDPLANTILLAENVIOS, IDCONSULTA, FECHAMODIFICACION, USUMODIFICACION, IDTIPOENVIOS, ",
			"IDINSTITUCION, FECHABAJA", "from MOD_PLANTILLAENVIO_CONSULTA",
			"where IDPLANTILLAENVIOS = #{idplantillaenvios,jdbcType=DECIMAL}",
			"and IDCONSULTA = #{idconsulta,jdbcType=DECIMAL}" })
	@Results({
			@Result(column = "IDPLANTILLAENVIOS", property = "idplantillaenvios", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDCONSULTA", property = "idconsulta", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "IDTIPOENVIOS", property = "idtipoenvios", jdbcType = JdbcType.DECIMAL),
			@Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "FECHABAJA", property = "fechabaja", jdbcType = JdbcType.TIMESTAMP) })
	ModPlantillaenvioConsulta selectByPrimaryKey(ModPlantillaenvioConsultaKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@UpdateProvider(type = ModPlantillaenvioConsultaSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") ModPlantillaenvioConsulta record,
			@Param("example") ModPlantillaenvioConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@UpdateProvider(type = ModPlantillaenvioConsultaSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") ModPlantillaenvioConsulta record,
			@Param("example") ModPlantillaenvioConsultaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@UpdateProvider(type = ModPlantillaenvioConsultaSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(ModPlantillaenvioConsulta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.MOD_PLANTILLAENVIO_CONSULTA
	 * @mbg.generated  Tue Jan 22 10:57:32 CET 2019
	 */
	@Update({ "update MOD_PLANTILLAENVIO_CONSULTA", "set FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
			"USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
			"IDTIPOENVIOS = #{idtipoenvios,jdbcType=DECIMAL},", "IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL},",
			"FECHABAJA = #{fechabaja,jdbcType=TIMESTAMP}",
			"where IDPLANTILLAENVIOS = #{idplantillaenvios,jdbcType=DECIMAL}",
			"and IDCONSULTA = #{idconsulta,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(ModPlantillaenvioConsulta record);
}