package org.itcgae.siga.db.mappers;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.db.entities.PysPreciosservicios;
import org.itcgae.siga.db.entities.PysPreciosserviciosExample.Criteria;
import org.itcgae.siga.db.entities.PysPreciosserviciosExample.Criterion;
import org.itcgae.siga.db.entities.PysPreciosserviciosExample;

public class PysPreciosserviciosSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_PRECIOSSERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:24:30 CET 2019
     */
    public String countByExample(PysPreciosserviciosExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("PYS_PRECIOSSERVICIOS");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_PRECIOSSERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:24:30 CET 2019
     */
    public String deleteByExample(PysPreciosserviciosExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("PYS_PRECIOSSERVICIOS");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_PRECIOSSERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:24:30 CET 2019
     */
    public String insertSelective(PysPreciosservicios record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("PYS_PRECIOSSERVICIOS");
        
        if (record.getIdinstitucion() != null) {
            sql.VALUES("IDINSTITUCION", "#{idinstitucion,jdbcType=DECIMAL}");
        }
        
        if (record.getIdtiposervicios() != null) {
            sql.VALUES("IDTIPOSERVICIOS", "#{idtiposervicios,jdbcType=DECIMAL}");
        }
        
        if (record.getIdservicio() != null) {
            sql.VALUES("IDSERVICIO", "#{idservicio,jdbcType=DECIMAL}");
        }
        
        if (record.getIdserviciosinstitucion() != null) {
            sql.VALUES("IDSERVICIOSINSTITUCION", "#{idserviciosinstitucion,jdbcType=DECIMAL}");
        }
        
        if (record.getIdperiodicidad() != null) {
            sql.VALUES("IDPERIODICIDAD", "#{idperiodicidad,jdbcType=DECIMAL}");
        }
        
        if (record.getIdpreciosservicios() != null) {
            sql.VALUES("IDPRECIOSSERVICIOS", "#{idpreciosservicios,jdbcType=DECIMAL}");
        }
        
        if (record.getValor() != null) {
            sql.VALUES("VALOR", "#{valor,jdbcType=DECIMAL}");
        }
        
        if (record.getCriterios() != null) {
            sql.VALUES("CRITERIOS", "#{criterios,jdbcType=VARCHAR}");
        }
        
        if (record.getFechamodificacion() != null) {
            sql.VALUES("FECHAMODIFICACION", "#{fechamodificacion,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUsumodificacion() != null) {
            sql.VALUES("USUMODIFICACION", "#{usumodificacion,jdbcType=DECIMAL}");
        }
        
        if (record.getPordefecto() != null) {
            sql.VALUES("PORDEFECTO", "#{pordefecto,jdbcType=VARCHAR}");
        }
        
        if (record.getIdconsulta() != null) {
            sql.VALUES("IDCONSULTA", "#{idconsulta,jdbcType=DECIMAL}");
        }
        
        if (record.getDescripcion() != null) {
            sql.VALUES("DESCRIPCION", "#{descripcion,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_PRECIOSSERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:24:30 CET 2019
     */
    public String selectByExample(PysPreciosserviciosExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("IDINSTITUCION");
        } else {
            sql.SELECT("IDINSTITUCION");
        }
        sql.SELECT("IDTIPOSERVICIOS");
        sql.SELECT("IDSERVICIO");
        sql.SELECT("IDSERVICIOSINSTITUCION");
        sql.SELECT("IDPERIODICIDAD");
        sql.SELECT("IDPRECIOSSERVICIOS");
        sql.SELECT("VALOR");
        sql.SELECT("CRITERIOS");
        sql.SELECT("FECHAMODIFICACION");
        sql.SELECT("USUMODIFICACION");
        sql.SELECT("PORDEFECTO");
        sql.SELECT("IDCONSULTA");
        sql.SELECT("DESCRIPCION");
        sql.FROM("PYS_PRECIOSSERVICIOS");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_PRECIOSSERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:24:30 CET 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        PysPreciosservicios record = (PysPreciosservicios) parameter.get("record");
        PysPreciosserviciosExample example = (PysPreciosserviciosExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("PYS_PRECIOSSERVICIOS");
        
        if (record.getIdinstitucion() != null) {
            sql.SET("IDINSTITUCION = #{record.idinstitucion,jdbcType=DECIMAL}");
        }
        
        if (record.getIdtiposervicios() != null) {
            sql.SET("IDTIPOSERVICIOS = #{record.idtiposervicios,jdbcType=DECIMAL}");
        }
        
        if (record.getIdservicio() != null) {
            sql.SET("IDSERVICIO = #{record.idservicio,jdbcType=DECIMAL}");
        }
        
        if (record.getIdserviciosinstitucion() != null) {
            sql.SET("IDSERVICIOSINSTITUCION = #{record.idserviciosinstitucion,jdbcType=DECIMAL}");
        }
        
        if (record.getIdperiodicidad() != null) {
            sql.SET("IDPERIODICIDAD = #{record.idperiodicidad,jdbcType=DECIMAL}");
        }
        
        if (record.getIdpreciosservicios() != null) {
            sql.SET("IDPRECIOSSERVICIOS = #{record.idpreciosservicios,jdbcType=DECIMAL}");
        }
        
        if (record.getValor() != null) {
            sql.SET("VALOR = #{record.valor,jdbcType=DECIMAL}");
        }
        
        if (record.getCriterios() != null) {
            sql.SET("CRITERIOS = #{record.criterios,jdbcType=VARCHAR}");
        }
        
        if (record.getFechamodificacion() != null) {
            sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUsumodificacion() != null) {
            sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=DECIMAL}");
        }
        
        if (record.getPordefecto() != null) {
            sql.SET("PORDEFECTO = #{record.pordefecto,jdbcType=VARCHAR}");
        }
        
        if (record.getIdconsulta() != null) {
            sql.SET("IDCONSULTA = #{record.idconsulta,jdbcType=DECIMAL}");
        }
        
        if (record.getDescripcion() != null) {
            sql.SET("DESCRIPCION = #{record.descripcion,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_PRECIOSSERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:24:30 CET 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("PYS_PRECIOSSERVICIOS");
        
        sql.SET("IDINSTITUCION = #{record.idinstitucion,jdbcType=DECIMAL}");
        sql.SET("IDTIPOSERVICIOS = #{record.idtiposervicios,jdbcType=DECIMAL}");
        sql.SET("IDSERVICIO = #{record.idservicio,jdbcType=DECIMAL}");
        sql.SET("IDSERVICIOSINSTITUCION = #{record.idserviciosinstitucion,jdbcType=DECIMAL}");
        sql.SET("IDPERIODICIDAD = #{record.idperiodicidad,jdbcType=DECIMAL}");
        sql.SET("IDPRECIOSSERVICIOS = #{record.idpreciosservicios,jdbcType=DECIMAL}");
        sql.SET("VALOR = #{record.valor,jdbcType=DECIMAL}");
        sql.SET("CRITERIOS = #{record.criterios,jdbcType=VARCHAR}");
        sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=TIMESTAMP}");
        sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=DECIMAL}");
        sql.SET("PORDEFECTO = #{record.pordefecto,jdbcType=VARCHAR}");
        sql.SET("IDCONSULTA = #{record.idconsulta,jdbcType=DECIMAL}");
        sql.SET("DESCRIPCION = #{record.descripcion,jdbcType=VARCHAR}");
        
        PysPreciosserviciosExample example = (PysPreciosserviciosExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_PRECIOSSERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:24:30 CET 2019
     */
    public String updateByPrimaryKeySelective(PysPreciosservicios record) {
        SQL sql = new SQL();
        sql.UPDATE("PYS_PRECIOSSERVICIOS");
        
        if (record.getValor() != null) {
            sql.SET("VALOR = #{valor,jdbcType=DECIMAL}");
        }
        
        if (record.getCriterios() != null) {
            sql.SET("CRITERIOS = #{criterios,jdbcType=VARCHAR}");
        }
        
        if (record.getFechamodificacion() != null) {
            sql.SET("FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUsumodificacion() != null) {
            sql.SET("USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}");
        }
        
        if (record.getPordefecto() != null) {
            sql.SET("PORDEFECTO = #{pordefecto,jdbcType=VARCHAR}");
        }
        
        if (record.getIdconsulta() != null) {
            sql.SET("IDCONSULTA = #{idconsulta,jdbcType=DECIMAL}");
        }
        
        if (record.getDescripcion() != null) {
            sql.SET("DESCRIPCION = #{descripcion,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}");
        sql.WHERE("IDTIPOSERVICIOS = #{idtiposervicios,jdbcType=DECIMAL}");
        sql.WHERE("IDSERVICIO = #{idservicio,jdbcType=DECIMAL}");
        sql.WHERE("IDSERVICIOSINSTITUCION = #{idserviciosinstitucion,jdbcType=DECIMAL}");
        sql.WHERE("IDPERIODICIDAD = #{idperiodicidad,jdbcType=DECIMAL}");
        sql.WHERE("IDPRECIOSSERVICIOS = #{idpreciosservicios,jdbcType=DECIMAL}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_PRECIOSSERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:24:30 CET 2019
     */
    protected void applyWhere(SQL sql, PysPreciosserviciosExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}