package org.itcgae.siga.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.PysServicios;
import org.itcgae.siga.db.entities.PysServiciosExample;
import org.itcgae.siga.db.entities.PysServiciosKey;

public interface PysServiciosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @SelectProvider(type=PysServiciosSqlProvider.class, method="countByExample")
    long countByExample(PysServiciosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @DeleteProvider(type=PysServiciosSqlProvider.class, method="deleteByExample")
    int deleteByExample(PysServiciosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @Delete({
        "delete from PYS_SERVICIOS",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDTIPOSERVICIOS = #{idtiposervicios,jdbcType=DECIMAL}",
          "and IDSERVICIO = #{idservicio,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(PysServiciosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @Insert({
        "insert into PYS_SERVICIOS (IDINSTITUCION, IDTIPOSERVICIOS, ",
        "IDSERVICIO, DESCRIPCION, ",
        "FECHAMODIFICACION, USUMODIFICACION)",
        "values (#{idinstitucion,jdbcType=DECIMAL}, #{idtiposervicios,jdbcType=DECIMAL}, ",
        "#{idservicio,jdbcType=DECIMAL}, #{descripcion,jdbcType=VARCHAR}, ",
        "#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL})"
    })
    int insert(PysServicios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @InsertProvider(type=PysServiciosSqlProvider.class, method="insertSelective")
    int insertSelective(PysServicios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @SelectProvider(type=PysServiciosSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDTIPOSERVICIOS", property="idtiposervicios", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDSERVICIO", property="idservicio", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)
    })
    List<PysServicios> selectByExample(PysServiciosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @Select({
        "select",
        "IDINSTITUCION, IDTIPOSERVICIOS, IDSERVICIO, DESCRIPCION, FECHAMODIFICACION, ",
        "USUMODIFICACION",
        "from PYS_SERVICIOS",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDTIPOSERVICIOS = #{idtiposervicios,jdbcType=DECIMAL}",
          "and IDSERVICIO = #{idservicio,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDTIPOSERVICIOS", property="idtiposervicios", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDSERVICIO", property="idservicio", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)
    })
    PysServicios selectByPrimaryKey(PysServiciosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @UpdateProvider(type=PysServiciosSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PysServicios record, @Param("example") PysServiciosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @UpdateProvider(type=PysServiciosSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PysServicios record, @Param("example") PysServiciosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @UpdateProvider(type=PysServiciosSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PysServicios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_SERVICIOS
     *
     * @mbg.generated Wed Jan 02 12:23:16 CET 2019
     */
    @Update({
        "update PYS_SERVICIOS",
        "set DESCRIPCION = #{descripcion,jdbcType=VARCHAR},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDTIPOSERVICIOS = #{idtiposervicios,jdbcType=DECIMAL}",
          "and IDSERVICIO = #{idservicio,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(PysServicios record);
}