package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.PysTiposervicios;
import org.itcgae.siga.db.entities.PysTiposerviciosExample;

public interface PysTiposerviciosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @SelectProvider(type=PysTiposerviciosSqlProvider.class, method="countByExample")
    long countByExample(PysTiposerviciosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @DeleteProvider(type=PysTiposerviciosSqlProvider.class, method="deleteByExample")
    int deleteByExample(PysTiposerviciosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @Delete({
        "delete from PYS_TIPOSERVICIOS",
        "where IDTIPOSERVICIOS = #{idtiposervicios,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Short idtiposervicios);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @Insert({
        "insert into PYS_TIPOSERVICIOS (IDTIPOSERVICIOS, DESCRIPCION, ",
        "FECHAMODIFICACION, USUMODIFICACION, ",
        "CODIGOEXT, BLOQUEADO, ",
        "FECHA_BAJA)",
        "values (#{idtiposervicios,jdbcType=DECIMAL}, #{descripcion,jdbcType=VARCHAR}, ",
        "#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL}, ",
        "#{codigoext,jdbcType=VARCHAR}, #{bloqueado,jdbcType=CHAR}, ",
        "#{fechaBaja,jdbcType=TIMESTAMP})"
    })
    int insert(PysTiposervicios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @InsertProvider(type=PysTiposerviciosSqlProvider.class, method="insertSelective")
    int insertSelective(PysTiposervicios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @SelectProvider(type=PysTiposerviciosSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDTIPOSERVICIOS", property="idtiposervicios", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="CODIGOEXT", property="codigoext", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOQUEADO", property="bloqueado", jdbcType=JdbcType.CHAR),
        @Result(column="FECHA_BAJA", property="fechaBaja", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PysTiposervicios> selectByExample(PysTiposerviciosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @Select({
        "select",
        "IDTIPOSERVICIOS, DESCRIPCION, FECHAMODIFICACION, USUMODIFICACION, CODIGOEXT, ",
        "BLOQUEADO, FECHA_BAJA",
        "from PYS_TIPOSERVICIOS",
        "where IDTIPOSERVICIOS = #{idtiposervicios,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDTIPOSERVICIOS", property="idtiposervicios", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="CODIGOEXT", property="codigoext", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOQUEADO", property="bloqueado", jdbcType=JdbcType.CHAR),
        @Result(column="FECHA_BAJA", property="fechaBaja", jdbcType=JdbcType.TIMESTAMP)
    })
    PysTiposervicios selectByPrimaryKey(Short idtiposervicios);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @UpdateProvider(type=PysTiposerviciosSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PysTiposervicios record, @Param("example") PysTiposerviciosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @UpdateProvider(type=PysTiposerviciosSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PysTiposervicios record, @Param("example") PysTiposerviciosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @UpdateProvider(type=PysTiposerviciosSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PysTiposervicios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.PYS_TIPOSERVICIOS
     *
     * @mbg.generated Fri Oct 08 14:06:46 CEST 2021
     */
    @Update({
        "update PYS_TIPOSERVICIOS",
        "set DESCRIPCION = #{descripcion,jdbcType=VARCHAR},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
          "CODIGOEXT = #{codigoext,jdbcType=VARCHAR},",
          "BLOQUEADO = #{bloqueado,jdbcType=CHAR},",
          "FECHA_BAJA = #{fechaBaja,jdbcType=TIMESTAMP}",
        "where IDTIPOSERVICIOS = #{idtiposervicios,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(PysTiposervicios record);
}