package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ScsActacomision;
import org.itcgae.siga.db.entities.ScsActacomisionExample;
import org.itcgae.siga.db.entities.ScsActacomisionKey;

public interface ScsActacomisionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @SelectProvider(type=ScsActacomisionSqlProvider.class, method="countByExample")
    long countByExample(ScsActacomisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @DeleteProvider(type=ScsActacomisionSqlProvider.class, method="deleteByExample")
    int deleteByExample(ScsActacomisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @Delete({
        "delete from SCS_ACTACOMISION",
        "where IDACTA = #{idacta,jdbcType=DECIMAL}",
          "and IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and ANIOACTA = #{anioacta,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(ScsActacomisionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @Insert({
        "insert into SCS_ACTACOMISION (IDACTA, IDINSTITUCION, ",
        "ANIOACTA, FECHAREUNION, ",
        "FECHARESOLUCION, HORAINICIOREUNION, ",
        "HORAFINREUNION, IDPRESIDENTE, ",
        "IDSECRETARIO, MIEMBROSCOMISION, ",
        "FECHAMODIFICACION, USUMODIFICACION, ",
        "PENDIENTES, IDINTERCAMBIO, ",
        "FECHAINTERCAMBIO, NUMEROACTA, ",
        "OBSERVACIONES)",
        "values (#{idacta,jdbcType=DECIMAL}, #{idinstitucion,jdbcType=DECIMAL}, ",
        "#{anioacta,jdbcType=DECIMAL}, #{fechareunion,jdbcType=TIMESTAMP}, ",
        "#{fecharesolucion,jdbcType=TIMESTAMP}, #{horainicioreunion,jdbcType=TIMESTAMP}, ",
        "#{horafinreunion,jdbcType=TIMESTAMP}, #{idpresidente,jdbcType=DECIMAL}, ",
        "#{idsecretario,jdbcType=DECIMAL}, #{miembroscomision,jdbcType=VARCHAR}, ",
        "#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL}, ",
        "#{pendientes,jdbcType=VARCHAR}, #{idintercambio,jdbcType=VARCHAR}, ",
        "#{fechaintercambio,jdbcType=TIMESTAMP}, #{numeroacta,jdbcType=VARCHAR}, ",
        "#{observaciones,jdbcType=CLOB})"
    })
    int insert(ScsActacomision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @InsertProvider(type=ScsActacomisionSqlProvider.class, method="insertSelective")
    int insertSelective(ScsActacomision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @SelectProvider(type=ScsActacomisionSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="IDACTA", property="idacta", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ANIOACTA", property="anioacta", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="FECHAREUNION", property="fechareunion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHARESOLUCION", property="fecharesolucion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="HORAINICIOREUNION", property="horainicioreunion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="HORAFINREUNION", property="horafinreunion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="IDPRESIDENTE", property="idpresidente", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDSECRETARIO", property="idsecretario", jdbcType=JdbcType.DECIMAL),
        @Result(column="MIEMBROSCOMISION", property="miembroscomision", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="PENDIENTES", property="pendientes", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDINTERCAMBIO", property="idintercambio", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAINTERCAMBIO", property="fechaintercambio", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="NUMEROACTA", property="numeroacta", jdbcType=JdbcType.VARCHAR),
        @Result(column="OBSERVACIONES", property="observaciones", jdbcType=JdbcType.CLOB)
    })
    List<ScsActacomision> selectByExampleWithBLOBs(ScsActacomisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @SelectProvider(type=ScsActacomisionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDACTA", property="idacta", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ANIOACTA", property="anioacta", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="FECHAREUNION", property="fechareunion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHARESOLUCION", property="fecharesolucion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="HORAINICIOREUNION", property="horainicioreunion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="HORAFINREUNION", property="horafinreunion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="IDPRESIDENTE", property="idpresidente", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDSECRETARIO", property="idsecretario", jdbcType=JdbcType.DECIMAL),
        @Result(column="MIEMBROSCOMISION", property="miembroscomision", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="PENDIENTES", property="pendientes", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDINTERCAMBIO", property="idintercambio", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAINTERCAMBIO", property="fechaintercambio", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="NUMEROACTA", property="numeroacta", jdbcType=JdbcType.VARCHAR)
    })
    List<ScsActacomision> selectByExample(ScsActacomisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @Select({
        "select",
        "IDACTA, IDINSTITUCION, ANIOACTA, FECHAREUNION, FECHARESOLUCION, HORAINICIOREUNION, ",
        "HORAFINREUNION, IDPRESIDENTE, IDSECRETARIO, MIEMBROSCOMISION, FECHAMODIFICACION, ",
        "USUMODIFICACION, PENDIENTES, IDINTERCAMBIO, FECHAINTERCAMBIO, NUMEROACTA, OBSERVACIONES",
        "from SCS_ACTACOMISION",
        "where IDACTA = #{idacta,jdbcType=DECIMAL}",
          "and IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and ANIOACTA = #{anioacta,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDACTA", property="idacta", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ANIOACTA", property="anioacta", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="FECHAREUNION", property="fechareunion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHARESOLUCION", property="fecharesolucion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="HORAINICIOREUNION", property="horainicioreunion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="HORAFINREUNION", property="horafinreunion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="IDPRESIDENTE", property="idpresidente", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDSECRETARIO", property="idsecretario", jdbcType=JdbcType.DECIMAL),
        @Result(column="MIEMBROSCOMISION", property="miembroscomision", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="PENDIENTES", property="pendientes", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDINTERCAMBIO", property="idintercambio", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAINTERCAMBIO", property="fechaintercambio", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="NUMEROACTA", property="numeroacta", jdbcType=JdbcType.VARCHAR),
        @Result(column="OBSERVACIONES", property="observaciones", jdbcType=JdbcType.CLOB)
    })
    ScsActacomision selectByPrimaryKey(ScsActacomisionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @UpdateProvider(type=ScsActacomisionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ScsActacomision record, @Param("example") ScsActacomisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @UpdateProvider(type=ScsActacomisionSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") ScsActacomision record, @Param("example") ScsActacomisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @UpdateProvider(type=ScsActacomisionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ScsActacomision record, @Param("example") ScsActacomisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @UpdateProvider(type=ScsActacomisionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ScsActacomision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @Update({
        "update SCS_ACTACOMISION",
        "set FECHAREUNION = #{fechareunion,jdbcType=TIMESTAMP},",
          "FECHARESOLUCION = #{fecharesolucion,jdbcType=TIMESTAMP},",
          "HORAINICIOREUNION = #{horainicioreunion,jdbcType=TIMESTAMP},",
          "HORAFINREUNION = #{horafinreunion,jdbcType=TIMESTAMP},",
          "IDPRESIDENTE = #{idpresidente,jdbcType=DECIMAL},",
          "IDSECRETARIO = #{idsecretario,jdbcType=DECIMAL},",
          "MIEMBROSCOMISION = #{miembroscomision,jdbcType=VARCHAR},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
          "PENDIENTES = #{pendientes,jdbcType=VARCHAR},",
          "IDINTERCAMBIO = #{idintercambio,jdbcType=VARCHAR},",
          "FECHAINTERCAMBIO = #{fechaintercambio,jdbcType=TIMESTAMP},",
          "NUMEROACTA = #{numeroacta,jdbcType=VARCHAR},",
          "OBSERVACIONES = #{observaciones,jdbcType=CLOB}",
        "where IDACTA = #{idacta,jdbcType=DECIMAL}",
          "and IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and ANIOACTA = #{anioacta,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKeyWithBLOBs(ScsActacomision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_ACTACOMISION
     *
     * @mbg.generated Tue Jan 21 11:38:26 CET 2020
     */
    @Update({
        "update SCS_ACTACOMISION",
        "set FECHAREUNION = #{fechareunion,jdbcType=TIMESTAMP},",
          "FECHARESOLUCION = #{fecharesolucion,jdbcType=TIMESTAMP},",
          "HORAINICIOREUNION = #{horainicioreunion,jdbcType=TIMESTAMP},",
          "HORAFINREUNION = #{horafinreunion,jdbcType=TIMESTAMP},",
          "IDPRESIDENTE = #{idpresidente,jdbcType=DECIMAL},",
          "IDSECRETARIO = #{idsecretario,jdbcType=DECIMAL},",
          "MIEMBROSCOMISION = #{miembroscomision,jdbcType=VARCHAR},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
          "PENDIENTES = #{pendientes,jdbcType=VARCHAR},",
          "IDINTERCAMBIO = #{idintercambio,jdbcType=VARCHAR},",
          "FECHAINTERCAMBIO = #{fechaintercambio,jdbcType=TIMESTAMP},",
          "NUMEROACTA = #{numeroacta,jdbcType=VARCHAR}",
        "where IDACTA = #{idacta,jdbcType=DECIMAL}",
          "and IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and ANIOACTA = #{anioacta,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(ScsActacomision record);
}