package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ScsDelitosasistencia;
import org.itcgae.siga.db.entities.ScsDelitosasistenciaExample;
import org.itcgae.siga.db.entities.ScsDelitosasistenciaKey;

public interface ScsDelitosasistenciaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @SelectProvider(type=ScsDelitosasistenciaSqlProvider.class, method="countByExample")
    long countByExample(ScsDelitosasistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @DeleteProvider(type=ScsDelitosasistenciaSqlProvider.class, method="deleteByExample")
    int deleteByExample(ScsDelitosasistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @Delete({
        "delete from SCS_DELITOSASISTENCIA",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and NUMERO = #{numero,jdbcType=DECIMAL}",
          "and ANIO = #{anio,jdbcType=DECIMAL}",
          "and IDDELITO = #{iddelito,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(ScsDelitosasistenciaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @Insert({
        "insert into SCS_DELITOSASISTENCIA (IDINSTITUCION, NUMERO, ",
        "ANIO, IDDELITO, ",
        "FECHAMODIFICACION, USUMODIFICACION)",
        "values (#{idinstitucion,jdbcType=DECIMAL}, #{numero,jdbcType=DECIMAL}, ",
        "#{anio,jdbcType=DECIMAL}, #{iddelito,jdbcType=DECIMAL}, ",
        "#{fechamodificacion,jdbcType=DATE}, #{usumodificacion,jdbcType=DECIMAL})"
    })
    int insert(ScsDelitosasistencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @InsertProvider(type=ScsDelitosasistenciaSqlProvider.class, method="insertSelective")
    int insertSelective(ScsDelitosasistencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @SelectProvider(type=ScsDelitosasistenciaSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NUMERO", property="numero", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ANIO", property="anio", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDDELITO", property="iddelito", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.DATE),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)
    })
    List<ScsDelitosasistencia> selectByExample(ScsDelitosasistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @Select({
        "select",
        "IDINSTITUCION, NUMERO, ANIO, IDDELITO, FECHAMODIFICACION, USUMODIFICACION",
        "from SCS_DELITOSASISTENCIA",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and NUMERO = #{numero,jdbcType=DECIMAL}",
          "and ANIO = #{anio,jdbcType=DECIMAL}",
          "and IDDELITO = #{iddelito,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NUMERO", property="numero", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ANIO", property="anio", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDDELITO", property="iddelito", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.DATE),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)
    })
    ScsDelitosasistencia selectByPrimaryKey(ScsDelitosasistenciaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @UpdateProvider(type=ScsDelitosasistenciaSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ScsDelitosasistencia record, @Param("example") ScsDelitosasistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @UpdateProvider(type=ScsDelitosasistenciaSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ScsDelitosasistencia record, @Param("example") ScsDelitosasistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @UpdateProvider(type=ScsDelitosasistenciaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ScsDelitosasistencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DELITOSASISTENCIA
     *
     * @mbg.generated Mon Aug 02 09:12:34 CEST 2021
     */
    @Update({
        "update SCS_DELITOSASISTENCIA",
        "set FECHAMODIFICACION = #{fechamodificacion,jdbcType=DATE},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and NUMERO = #{numero,jdbcType=DECIMAL}",
          "and ANIO = #{anio,jdbcType=DECIMAL}",
          "and IDDELITO = #{iddelito,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(ScsDelitosasistencia record);
}