package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ScsDictamenejg;
import org.itcgae.siga.db.entities.ScsDictamenejgExample;
import org.itcgae.siga.db.entities.ScsDictamenejgKey;

public interface ScsDictamenejgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @SelectProvider(type=ScsDictamenejgSqlProvider.class, method="countByExample")
    long countByExample(ScsDictamenejgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @DeleteProvider(type=ScsDictamenejgSqlProvider.class, method="deleteByExample")
    int deleteByExample(ScsDictamenejgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @Delete({
        "delete from SCS_DICTAMENEJG",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDDICTAMEN = #{iddictamen,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(ScsDictamenejgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @Insert({
        "insert into SCS_DICTAMENEJG (IDINSTITUCION, IDDICTAMEN, ",
        "ABREVIATURA, DESCRIPCION, ",
        "IDTIPODICTAMEN, IDFUNDAMENTO, ",
        "FECHAMODIFICACION, USUMODIFICACION, ",
        "CODIGOEXT)",
        "values (#{idinstitucion,jdbcType=DECIMAL}, #{iddictamen,jdbcType=DECIMAL}, ",
        "#{abreviatura,jdbcType=VARCHAR}, #{descripcion,jdbcType=VARCHAR}, ",
        "#{idtipodictamen,jdbcType=DECIMAL}, #{idfundamento,jdbcType=DECIMAL}, ",
        "#{fechamodificacion,jdbcType=DATE}, #{usumodificacion,jdbcType=DECIMAL}, ",
        "#{codigoext,jdbcType=VARCHAR})"
    })
    int insert(ScsDictamenejg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @InsertProvider(type=ScsDictamenejgSqlProvider.class, method="insertSelective")
    int insertSelective(ScsDictamenejg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @SelectProvider(type=ScsDictamenejgSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDDICTAMEN", property="iddictamen", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ABREVIATURA", property="abreviatura", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDTIPODICTAMEN", property="idtipodictamen", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDFUNDAMENTO", property="idfundamento", jdbcType=JdbcType.DECIMAL),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.DATE),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="CODIGOEXT", property="codigoext", jdbcType=JdbcType.VARCHAR)
    })
    List<ScsDictamenejg> selectByExample(ScsDictamenejgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @Select({
        "select",
        "IDINSTITUCION, IDDICTAMEN, ABREVIATURA, DESCRIPCION, IDTIPODICTAMEN, IDFUNDAMENTO, ",
        "FECHAMODIFICACION, USUMODIFICACION, CODIGOEXT",
        "from SCS_DICTAMENEJG",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDDICTAMEN = #{iddictamen,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDDICTAMEN", property="iddictamen", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ABREVIATURA", property="abreviatura", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDTIPODICTAMEN", property="idtipodictamen", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDFUNDAMENTO", property="idfundamento", jdbcType=JdbcType.DECIMAL),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.DATE),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="CODIGOEXT", property="codigoext", jdbcType=JdbcType.VARCHAR)
    })
    ScsDictamenejg selectByPrimaryKey(ScsDictamenejgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @UpdateProvider(type=ScsDictamenejgSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ScsDictamenejg record, @Param("example") ScsDictamenejgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @UpdateProvider(type=ScsDictamenejgSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ScsDictamenejg record, @Param("example") ScsDictamenejgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @UpdateProvider(type=ScsDictamenejgSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ScsDictamenejg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DICTAMENEJG
     *
     * @mbg.generated Mon Jul 05 19:23:10 CEST 2021
     */
    @Update({
        "update SCS_DICTAMENEJG",
        "set ABREVIATURA = #{abreviatura,jdbcType=VARCHAR},",
          "DESCRIPCION = #{descripcion,jdbcType=VARCHAR},",
          "IDTIPODICTAMEN = #{idtipodictamen,jdbcType=DECIMAL},",
          "IDFUNDAMENTO = #{idfundamento,jdbcType=DECIMAL},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=DATE},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
          "CODIGOEXT = #{codigoext,jdbcType=VARCHAR}",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDDICTAMEN = #{iddictamen,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(ScsDictamenejg record);
}