package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ScsDocumentaciondesigna;
import org.itcgae.siga.db.entities.ScsDocumentaciondesignaExample;
import org.itcgae.siga.db.entities.ScsDocumentaciondesignaKey;

public interface ScsDocumentaciondesignaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @SelectProvider(type=ScsDocumentaciondesignaSqlProvider.class, method="countByExample")
    long countByExample(ScsDocumentaciondesignaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @DeleteProvider(type=ScsDocumentaciondesignaSqlProvider.class, method="deleteByExample")
    int deleteByExample(ScsDocumentaciondesignaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @Delete({
        "delete from SCS_DOCUMENTACIONDESIGNA",
        "where IDDOCUMENTACIONDES = #{iddocumentaciondes,jdbcType=DECIMAL}",
          "and IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(ScsDocumentaciondesignaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @Insert({
        "insert into SCS_DOCUMENTACIONDESIGNA (IDDOCUMENTACIONDES, IDINSTITUCION, ",
        "IDTIPODOCUMENTO, IDFICHERO, ",
        "IDTURNO, ANIO, NUMERO, ",
        "IDACTUACION, USUMODIFICACION, ",
        "FECHAMODIFICACION, FECHAENTRADA, ",
        "OBSERVACIONES, NOMBREFICHERO)",
        "values (#{iddocumentaciondes,jdbcType=DECIMAL}, #{idinstitucion,jdbcType=DECIMAL}, ",
        "#{idtipodocumento,jdbcType=DECIMAL}, #{idfichero,jdbcType=DECIMAL}, ",
        "#{idturno,jdbcType=DECIMAL}, #{anio,jdbcType=DECIMAL}, #{numero,jdbcType=DECIMAL}, ",
        "#{idactuacion,jdbcType=DECIMAL}, #{usumodificacion,jdbcType=DECIMAL}, ",
        "#{fechamodificacion,jdbcType=TIMESTAMP}, #{fechaentrada,jdbcType=TIMESTAMP}, ",
        "#{observaciones,jdbcType=VARCHAR}, #{nombrefichero,jdbcType=VARCHAR})"
    })
    int insert(ScsDocumentaciondesigna record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @InsertProvider(type=ScsDocumentaciondesignaSqlProvider.class, method="insertSelective")
    int insertSelective(ScsDocumentaciondesigna record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @SelectProvider(type=ScsDocumentaciondesignaSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDDOCUMENTACIONDES", property="iddocumentaciondes", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDTIPODOCUMENTO", property="idtipodocumento", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDFICHERO", property="idfichero", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDTURNO", property="idturno", jdbcType=JdbcType.DECIMAL),
        @Result(column="ANIO", property="anio", jdbcType=JdbcType.DECIMAL),
        @Result(column="NUMERO", property="numero", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDACTUACION", property="idactuacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHAENTRADA", property="fechaentrada", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="OBSERVACIONES", property="observaciones", jdbcType=JdbcType.VARCHAR),
        @Result(column="NOMBREFICHERO", property="nombrefichero", jdbcType=JdbcType.VARCHAR)
    })
    List<ScsDocumentaciondesigna> selectByExample(ScsDocumentaciondesignaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @Select({
        "select",
        "IDDOCUMENTACIONDES, IDINSTITUCION, IDTIPODOCUMENTO, IDFICHERO, IDTURNO, ANIO, ",
        "NUMERO, IDACTUACION, USUMODIFICACION, FECHAMODIFICACION, FECHAENTRADA, OBSERVACIONES, ",
        "NOMBREFICHERO",
        "from SCS_DOCUMENTACIONDESIGNA",
        "where IDDOCUMENTACIONDES = #{iddocumentaciondes,jdbcType=DECIMAL}",
          "and IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDDOCUMENTACIONDES", property="iddocumentaciondes", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDTIPODOCUMENTO", property="idtipodocumento", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDFICHERO", property="idfichero", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDTURNO", property="idturno", jdbcType=JdbcType.DECIMAL),
        @Result(column="ANIO", property="anio", jdbcType=JdbcType.DECIMAL),
        @Result(column="NUMERO", property="numero", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDACTUACION", property="idactuacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHAENTRADA", property="fechaentrada", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="OBSERVACIONES", property="observaciones", jdbcType=JdbcType.VARCHAR),
        @Result(column="NOMBREFICHERO", property="nombrefichero", jdbcType=JdbcType.VARCHAR)
    })
    ScsDocumentaciondesigna selectByPrimaryKey(ScsDocumentaciondesignaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @UpdateProvider(type=ScsDocumentaciondesignaSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ScsDocumentaciondesigna record, @Param("example") ScsDocumentaciondesignaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @UpdateProvider(type=ScsDocumentaciondesignaSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ScsDocumentaciondesigna record, @Param("example") ScsDocumentaciondesignaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @UpdateProvider(type=ScsDocumentaciondesignaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ScsDocumentaciondesigna record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_DOCUMENTACIONDESIGNA
     *
     * @mbg.generated Mon May 03 17:46:48 CEST 2021
     */
    @Update({
        "update SCS_DOCUMENTACIONDESIGNA",
        "set IDTIPODOCUMENTO = #{idtipodocumento,jdbcType=DECIMAL},",
          "IDFICHERO = #{idfichero,jdbcType=DECIMAL},",
          "IDTURNO = #{idturno,jdbcType=DECIMAL},",
          "ANIO = #{anio,jdbcType=DECIMAL},",
          "NUMERO = #{numero,jdbcType=DECIMAL},",
          "IDACTUACION = #{idactuacion,jdbcType=DECIMAL},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "FECHAENTRADA = #{fechaentrada,jdbcType=TIMESTAMP},",
          "OBSERVACIONES = #{observaciones,jdbcType=VARCHAR},",
          "NOMBREFICHERO = #{nombrefichero,jdbcType=VARCHAR}",
        "where IDDOCUMENTACIONDES = #{iddocumentaciondes,jdbcType=DECIMAL}",
          "and IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(ScsDocumentaciondesigna record);
}