package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ScsDesignasletrado;
import org.itcgae.siga.db.entities.ScsDesignasletradoExample;
import org.itcgae.siga.db.entities.ScsDesignasletradoKey;

public interface ScsDesignasletradoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@SelectProvider(type = ScsDesignasletradoSqlProvider.class, method = "countByExample")
	long countByExample(ScsDesignasletradoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@DeleteProvider(type = ScsDesignasletradoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(ScsDesignasletradoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@Delete({ "delete from SCS_DESIGNASLETRADO", "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
			"and IDTURNO = #{idturno,jdbcType=DECIMAL}", "and ANIO = #{anio,jdbcType=DECIMAL}",
			"and NUMERO = #{numero,jdbcType=DECIMAL}", "and IDPERSONA = #{idpersona,jdbcType=DECIMAL}",
			"and FECHADESIGNA = #{fechadesigna,jdbcType=TIMESTAMP}" })
	int deleteByPrimaryKey(ScsDesignasletradoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@Insert({ "insert into SCS_DESIGNASLETRADO (IDINSTITUCION, IDTURNO, ", "ANIO, NUMERO, IDPERSONA, ",
			"FECHADESIGNA, MANUAL, ", "LETRADODELTURNO, FECHAMODIFICACION, ", "USUMODIFICACION, OBSERVACIONES, ",
			"FECHARENUNCIA, MOTIVOSRENUNCIA, ", "FECHARENUNCIASOLICITA, IDTIPOMOTIVO, ", "IDINSTITUCIONORIGEN)",
			"values (#{idinstitucion,jdbcType=DECIMAL}, #{idturno,jdbcType=DECIMAL}, ",
			"#{anio,jdbcType=DECIMAL}, #{numero,jdbcType=DECIMAL}, #{idpersona,jdbcType=DECIMAL}, ",
			"#{fechadesigna,jdbcType=TIMESTAMP}, #{manual,jdbcType=DECIMAL}, ",
			"#{letradodelturno,jdbcType=VARCHAR}, #{fechamodificacion,jdbcType=TIMESTAMP}, ",
			"#{usumodificacion,jdbcType=DECIMAL}, #{observaciones,jdbcType=VARCHAR}, ",
			"#{fecharenuncia,jdbcType=TIMESTAMP}, #{motivosrenuncia,jdbcType=VARCHAR}, ",
			"#{fecharenunciasolicita,jdbcType=TIMESTAMP}, #{idtipomotivo,jdbcType=DECIMAL}, ",
			"#{idinstitucionorigen,jdbcType=DECIMAL})" })
	int insert(ScsDesignasletrado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@InsertProvider(type = ScsDesignasletradoSqlProvider.class, method = "insertSelective")
	int insertSelective(ScsDesignasletrado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@SelectProvider(type = ScsDesignasletradoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDTURNO", property = "idturno", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "ANIO", property = "anio", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "NUMERO", property = "numero", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDPERSONA", property = "idpersona", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "FECHADESIGNA", property = "fechadesigna", jdbcType = JdbcType.TIMESTAMP, id = true),
			@Result(column = "MANUAL", property = "manual", jdbcType = JdbcType.DECIMAL),
			@Result(column = "LETRADODELTURNO", property = "letradodelturno", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "OBSERVACIONES", property = "observaciones", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHARENUNCIA", property = "fecharenuncia", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "MOTIVOSRENUNCIA", property = "motivosrenuncia", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHARENUNCIASOLICITA", property = "fecharenunciasolicita", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "IDTIPOMOTIVO", property = "idtipomotivo", jdbcType = JdbcType.DECIMAL),
			@Result(column = "IDINSTITUCIONORIGEN", property = "idinstitucionorigen", jdbcType = JdbcType.DECIMAL) })
	List<ScsDesignasletrado> selectByExample(ScsDesignasletradoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@Select({ "select", "IDINSTITUCION, IDTURNO, ANIO, NUMERO, IDPERSONA, FECHADESIGNA, MANUAL, LETRADODELTURNO, ",
			"FECHAMODIFICACION, USUMODIFICACION, OBSERVACIONES, FECHARENUNCIA, MOTIVOSRENUNCIA, ",
			"FECHARENUNCIASOLICITA, IDTIPOMOTIVO, IDINSTITUCIONORIGEN", "from SCS_DESIGNASLETRADO",
			"where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}", "and IDTURNO = #{idturno,jdbcType=DECIMAL}",
			"and ANIO = #{anio,jdbcType=DECIMAL}", "and NUMERO = #{numero,jdbcType=DECIMAL}",
			"and IDPERSONA = #{idpersona,jdbcType=DECIMAL}", "and FECHADESIGNA = #{fechadesigna,jdbcType=TIMESTAMP}" })
	@Results({ @Result(column = "IDINSTITUCION", property = "idinstitucion", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDTURNO", property = "idturno", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "ANIO", property = "anio", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "NUMERO", property = "numero", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "IDPERSONA", property = "idpersona", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "FECHADESIGNA", property = "fechadesigna", jdbcType = JdbcType.TIMESTAMP, id = true),
			@Result(column = "MANUAL", property = "manual", jdbcType = JdbcType.DECIMAL),
			@Result(column = "LETRADODELTURNO", property = "letradodelturno", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHAMODIFICACION", property = "fechamodificacion", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USUMODIFICACION", property = "usumodificacion", jdbcType = JdbcType.DECIMAL),
			@Result(column = "OBSERVACIONES", property = "observaciones", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHARENUNCIA", property = "fecharenuncia", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "MOTIVOSRENUNCIA", property = "motivosrenuncia", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FECHARENUNCIASOLICITA", property = "fecharenunciasolicita", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "IDTIPOMOTIVO", property = "idtipomotivo", jdbcType = JdbcType.DECIMAL),
			@Result(column = "IDINSTITUCIONORIGEN", property = "idinstitucionorigen", jdbcType = JdbcType.DECIMAL) })
	ScsDesignasletrado selectByPrimaryKey(ScsDesignasletradoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@UpdateProvider(type = ScsDesignasletradoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") ScsDesignasletrado record,
			@Param("example") ScsDesignasletradoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@UpdateProvider(type = ScsDesignasletradoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") ScsDesignasletrado record,
			@Param("example") ScsDesignasletradoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@UpdateProvider(type = ScsDesignasletradoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(ScsDesignasletrado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_DESIGNASLETRADO
	 * @mbg.generated  Tue Mar 08 12:58:20 CET 2022
	 */
	@Update({ "update SCS_DESIGNASLETRADO", "set MANUAL = #{manual,jdbcType=DECIMAL},",
			"LETRADODELTURNO = #{letradodelturno,jdbcType=VARCHAR},",
			"FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
			"USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
			"OBSERVACIONES = #{observaciones,jdbcType=VARCHAR},",
			"FECHARENUNCIA = #{fecharenuncia,jdbcType=TIMESTAMP},",
			"MOTIVOSRENUNCIA = #{motivosrenuncia,jdbcType=VARCHAR},",
			"FECHARENUNCIASOLICITA = #{fecharenunciasolicita,jdbcType=TIMESTAMP},",
			"IDTIPOMOTIVO = #{idtipomotivo,jdbcType=DECIMAL},",
			"IDINSTITUCIONORIGEN = #{idinstitucionorigen,jdbcType=DECIMAL}",
			"where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}", "and IDTURNO = #{idturno,jdbcType=DECIMAL}",
			"and ANIO = #{anio,jdbcType=DECIMAL}", "and NUMERO = #{numero,jdbcType=DECIMAL}",
			"and IDPERSONA = #{idpersona,jdbcType=DECIMAL}", "and FECHADESIGNA = #{fechadesigna,jdbcType=TIMESTAMP}" })
	int updateByPrimaryKey(ScsDesignasletrado record);
}