package org.itcgae.siga.db.mappers;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.db.entities.ScsDocumentacionsoj;
import org.itcgae.siga.db.entities.ScsDocumentacionsojExample.Criteria;
import org.itcgae.siga.db.entities.ScsDocumentacionsojExample.Criterion;
import org.itcgae.siga.db.entities.ScsDocumentacionsojExample;

public class ScsDocumentacionsojSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.SCS_DOCUMENTACIONSOJ
     *
     * @mbg.generated Tue Oct 11 12:59:09 CEST 2022
     */
    public String countByExample(ScsDocumentacionsojExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("SCS_DOCUMENTACIONSOJ");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.SCS_DOCUMENTACIONSOJ
     *
     * @mbg.generated Tue Oct 11 12:59:09 CEST 2022
     */
    public String deleteByExample(ScsDocumentacionsojExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("SCS_DOCUMENTACIONSOJ");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.SCS_DOCUMENTACIONSOJ
     *
     * @mbg.generated Tue Oct 11 12:59:09 CEST 2022
     */
    public String insertSelective(ScsDocumentacionsoj row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("SCS_DOCUMENTACIONSOJ");
        
        if (row.getIdinstitucion() != null) {
            sql.VALUES("IDINSTITUCION", "#{idinstitucion,jdbcType=NUMERIC}");
        }
        
        if (row.getIdtiposoj() != null) {
            sql.VALUES("IDTIPOSOJ", "#{idtiposoj,jdbcType=NUMERIC}");
        }
        
        if (row.getAnio() != null) {
            sql.VALUES("ANIO", "#{anio,jdbcType=NUMERIC}");
        }
        
        if (row.getNumero() != null) {
            sql.VALUES("NUMERO", "#{numero,jdbcType=NUMERIC}");
        }
        
        if (row.getIddocumentacion() != null) {
            sql.VALUES("IDDOCUMENTACION", "#{iddocumentacion,jdbcType=NUMERIC}");
        }
        
        if (row.getFechalimite() != null) {
            sql.VALUES("FECHALIMITE", "#{fechalimite,jdbcType=TIMESTAMP}");
        }
        
        if (row.getUsumodificacion() != null) {
            sql.VALUES("USUMODIFICACION", "#{usumodificacion,jdbcType=NUMERIC}");
        }
        
        if (row.getFechamodificacion() != null) {
            sql.VALUES("FECHAMODIFICACION", "#{fechamodificacion,jdbcType=TIMESTAMP}");
        }
        
        if (row.getDocumentacion() != null) {
            sql.VALUES("DOCUMENTACION", "#{documentacion,jdbcType=VARCHAR}");
        }
        
        if (row.getFechaentrega() != null) {
            sql.VALUES("FECHAENTREGA", "#{fechaentrega,jdbcType=TIMESTAMP}");
        }
        
        if (row.getRegentrada() != null) {
            sql.VALUES("REGENTRADA", "#{regentrada,jdbcType=VARCHAR}");
        }
        
        if (row.getRegsalida() != null) {
            sql.VALUES("REGSALIDA", "#{regsalida,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.SCS_DOCUMENTACIONSOJ
     *
     * @mbg.generated Tue Oct 11 12:59:09 CEST 2022
     */
    public String selectByExample(ScsDocumentacionsojExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("IDINSTITUCION");
        } else {
            sql.SELECT("IDINSTITUCION");
        }
        sql.SELECT("IDTIPOSOJ");
        sql.SELECT("ANIO");
        sql.SELECT("NUMERO");
        sql.SELECT("IDDOCUMENTACION");
        sql.SELECT("FECHALIMITE");
        sql.SELECT("USUMODIFICACION");
        sql.SELECT("FECHAMODIFICACION");
        sql.SELECT("DOCUMENTACION");
        sql.SELECT("FECHAENTREGA");
        sql.SELECT("REGENTRADA");
        sql.SELECT("REGSALIDA");
        sql.FROM("SCS_DOCUMENTACIONSOJ");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.SCS_DOCUMENTACIONSOJ
     *
     * @mbg.generated Tue Oct 11 12:59:09 CEST 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ScsDocumentacionsoj row = (ScsDocumentacionsoj) parameter.get("row");
        ScsDocumentacionsojExample example = (ScsDocumentacionsojExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("SCS_DOCUMENTACIONSOJ");
        
        if (row.getIdinstitucion() != null) {
            sql.SET("IDINSTITUCION = #{row.idinstitucion,jdbcType=NUMERIC}");
        }
        
        if (row.getIdtiposoj() != null) {
            sql.SET("IDTIPOSOJ = #{row.idtiposoj,jdbcType=NUMERIC}");
        }
        
        if (row.getAnio() != null) {
            sql.SET("ANIO = #{row.anio,jdbcType=NUMERIC}");
        }
        
        if (row.getNumero() != null) {
            sql.SET("NUMERO = #{row.numero,jdbcType=NUMERIC}");
        }
        
        if (row.getIddocumentacion() != null) {
            sql.SET("IDDOCUMENTACION = #{row.iddocumentacion,jdbcType=NUMERIC}");
        }
        
        if (row.getFechalimite() != null) {
            sql.SET("FECHALIMITE = #{row.fechalimite,jdbcType=TIMESTAMP}");
        }
        
        if (row.getUsumodificacion() != null) {
            sql.SET("USUMODIFICACION = #{row.usumodificacion,jdbcType=NUMERIC}");
        }
        
        if (row.getFechamodificacion() != null) {
            sql.SET("FECHAMODIFICACION = #{row.fechamodificacion,jdbcType=TIMESTAMP}");
        }
        
        if (row.getDocumentacion() != null) {
            sql.SET("DOCUMENTACION = #{row.documentacion,jdbcType=VARCHAR}");
        }
        
        if (row.getFechaentrega() != null) {
            sql.SET("FECHAENTREGA = #{row.fechaentrega,jdbcType=TIMESTAMP}");
        }
        
        if (row.getRegentrada() != null) {
            sql.SET("REGENTRADA = #{row.regentrada,jdbcType=VARCHAR}");
        }
        
        if (row.getRegsalida() != null) {
            sql.SET("REGSALIDA = #{row.regsalida,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.SCS_DOCUMENTACIONSOJ
     *
     * @mbg.generated Tue Oct 11 12:59:09 CEST 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("SCS_DOCUMENTACIONSOJ");
        
        sql.SET("IDINSTITUCION = #{row.idinstitucion,jdbcType=NUMERIC}");
        sql.SET("IDTIPOSOJ = #{row.idtiposoj,jdbcType=NUMERIC}");
        sql.SET("ANIO = #{row.anio,jdbcType=NUMERIC}");
        sql.SET("NUMERO = #{row.numero,jdbcType=NUMERIC}");
        sql.SET("IDDOCUMENTACION = #{row.iddocumentacion,jdbcType=NUMERIC}");
        sql.SET("FECHALIMITE = #{row.fechalimite,jdbcType=TIMESTAMP}");
        sql.SET("USUMODIFICACION = #{row.usumodificacion,jdbcType=NUMERIC}");
        sql.SET("FECHAMODIFICACION = #{row.fechamodificacion,jdbcType=TIMESTAMP}");
        sql.SET("DOCUMENTACION = #{row.documentacion,jdbcType=VARCHAR}");
        sql.SET("FECHAENTREGA = #{row.fechaentrega,jdbcType=TIMESTAMP}");
        sql.SET("REGENTRADA = #{row.regentrada,jdbcType=VARCHAR}");
        sql.SET("REGSALIDA = #{row.regsalida,jdbcType=VARCHAR}");
        
        ScsDocumentacionsojExample example = (ScsDocumentacionsojExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.SCS_DOCUMENTACIONSOJ
     *
     * @mbg.generated Tue Oct 11 12:59:09 CEST 2022
     */
    public String updateByPrimaryKeySelective(ScsDocumentacionsoj row) {
        SQL sql = new SQL();
        sql.UPDATE("SCS_DOCUMENTACIONSOJ");
        
        if (row.getFechalimite() != null) {
            sql.SET("FECHALIMITE = #{fechalimite,jdbcType=TIMESTAMP}");
        }
        
        if (row.getUsumodificacion() != null) {
            sql.SET("USUMODIFICACION = #{usumodificacion,jdbcType=NUMERIC}");
        }
        
        if (row.getFechamodificacion() != null) {
            sql.SET("FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP}");
        }
        
        if (row.getDocumentacion() != null) {
            sql.SET("DOCUMENTACION = #{documentacion,jdbcType=VARCHAR}");
        }
        
        if (row.getFechaentrega() != null) {
            sql.SET("FECHAENTREGA = #{fechaentrega,jdbcType=TIMESTAMP}");
        }
        
        if (row.getRegentrada() != null) {
            sql.SET("REGENTRADA = #{regentrada,jdbcType=VARCHAR}");
        }
        
        if (row.getRegsalida() != null) {
            sql.SET("REGSALIDA = #{regsalida,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("IDINSTITUCION = #{idinstitucion,jdbcType=NUMERIC}");
        sql.WHERE("IDTIPOSOJ = #{idtiposoj,jdbcType=NUMERIC}");
        sql.WHERE("ANIO = #{anio,jdbcType=NUMERIC}");
        sql.WHERE("NUMERO = #{numero,jdbcType=NUMERIC}");
        sql.WHERE("IDDOCUMENTACION = #{iddocumentacion,jdbcType=NUMERIC}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.SCS_DOCUMENTACIONSOJ
     *
     * @mbg.generated Tue Oct 11 12:59:09 CEST 2022
     */
    protected void applyWhere(SQL sql, ScsDocumentacionsojExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}