package org.itcgae.siga.db.mappers;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.db.entities.ScsEjgActa;
import org.itcgae.siga.db.entities.ScsEjgActaExample.Criteria;
import org.itcgae.siga.db.entities.ScsEjgActaExample.Criterion;
import org.itcgae.siga.db.entities.ScsEjgActaExample;

public class ScsEjgActaSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_EJG_ACTA
     *
     * @mbg.generated Tue Jul 20 11:38:47 CEST 2021
     */
    public String countByExample(ScsEjgActaExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("SCS_EJG_ACTA");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_EJG_ACTA
     *
     * @mbg.generated Tue Jul 20 11:38:47 CEST 2021
     */
    public String deleteByExample(ScsEjgActaExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("SCS_EJG_ACTA");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_EJG_ACTA
     *
     * @mbg.generated Tue Jul 20 11:38:47 CEST 2021
     */
    public String insertSelective(ScsEjgActa record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("SCS_EJG_ACTA");
        
        if (record.getIdacta() != null) {
            sql.VALUES("IDACTA", "#{idacta,jdbcType=DECIMAL}");
        }
        
        if (record.getIdinstitucionacta() != null) {
            sql.VALUES("IDINSTITUCIONACTA", "#{idinstitucionacta,jdbcType=DECIMAL}");
        }
        
        if (record.getAnioacta() != null) {
            sql.VALUES("ANIOACTA", "#{anioacta,jdbcType=DECIMAL}");
        }
        
        if (record.getIdinstitucionejg() != null) {
            sql.VALUES("IDINSTITUCIONEJG", "#{idinstitucionejg,jdbcType=DECIMAL}");
        }
        
        if (record.getIdtipoejg() != null) {
            sql.VALUES("IDTIPOEJG", "#{idtipoejg,jdbcType=DECIMAL}");
        }
        
        if (record.getAnioejg() != null) {
            sql.VALUES("ANIOEJG", "#{anioejg,jdbcType=DECIMAL}");
        }
        
        if (record.getNumeroejg() != null) {
            sql.VALUES("NUMEROEJG", "#{numeroejg,jdbcType=DECIMAL}");
        }
        
        if (record.getIdtiporatificacionejg() != null) {
            sql.VALUES("IDTIPORATIFICACIONEJG", "#{idtiporatificacionejg,jdbcType=DECIMAL}");
        }
        
        if (record.getIdfundamentojuridico() != null) {
            sql.VALUES("IDFUNDAMENTOJURIDICO", "#{idfundamentojuridico,jdbcType=DECIMAL}");
        }
        
        if (record.getFechamodificacion() != null) {
            sql.VALUES("FECHAMODIFICACION", "#{fechamodificacion,jdbcType=DATE}");
        }
        
        if (record.getUsumodificacion() != null) {
            sql.VALUES("USUMODIFICACION", "#{usumodificacion,jdbcType=DECIMAL}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_EJG_ACTA
     *
     * @mbg.generated Tue Jul 20 11:38:47 CEST 2021
     */
    public String selectByExample(ScsEjgActaExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("IDACTA");
        } else {
            sql.SELECT("IDACTA");
        }
        sql.SELECT("IDINSTITUCIONACTA");
        sql.SELECT("ANIOACTA");
        sql.SELECT("IDINSTITUCIONEJG");
        sql.SELECT("IDTIPOEJG");
        sql.SELECT("ANIOEJG");
        sql.SELECT("NUMEROEJG");
        sql.SELECT("IDTIPORATIFICACIONEJG");
        sql.SELECT("IDFUNDAMENTOJURIDICO");
        sql.SELECT("FECHAMODIFICACION");
        sql.SELECT("USUMODIFICACION");
        sql.FROM("SCS_EJG_ACTA");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_EJG_ACTA
     *
     * @mbg.generated Tue Jul 20 11:38:47 CEST 2021
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ScsEjgActa record = (ScsEjgActa) parameter.get("record");
        ScsEjgActaExample example = (ScsEjgActaExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("SCS_EJG_ACTA");
        
        if (record.getIdacta() != null) {
            sql.SET("IDACTA = #{record.idacta,jdbcType=DECIMAL}");
        }
        
        if (record.getIdinstitucionacta() != null) {
            sql.SET("IDINSTITUCIONACTA = #{record.idinstitucionacta,jdbcType=DECIMAL}");
        }
        
        if (record.getAnioacta() != null) {
            sql.SET("ANIOACTA = #{record.anioacta,jdbcType=DECIMAL}");
        }
        
        if (record.getIdinstitucionejg() != null) {
            sql.SET("IDINSTITUCIONEJG = #{record.idinstitucionejg,jdbcType=DECIMAL}");
        }
        
        if (record.getIdtipoejg() != null) {
            sql.SET("IDTIPOEJG = #{record.idtipoejg,jdbcType=DECIMAL}");
        }
        
        if (record.getAnioejg() != null) {
            sql.SET("ANIOEJG = #{record.anioejg,jdbcType=DECIMAL}");
        }
        
        if (record.getNumeroejg() != null) {
            sql.SET("NUMEROEJG = #{record.numeroejg,jdbcType=DECIMAL}");
        }
        
        if (record.getIdtiporatificacionejg() != null) {
            sql.SET("IDTIPORATIFICACIONEJG = #{record.idtiporatificacionejg,jdbcType=DECIMAL}");
        }
        
        if (record.getIdfundamentojuridico() != null) {
            sql.SET("IDFUNDAMENTOJURIDICO = #{record.idfundamentojuridico,jdbcType=DECIMAL}");
        }
        
        if (record.getFechamodificacion() != null) {
            sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=DATE}");
        }
        
        if (record.getUsumodificacion() != null) {
            sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=DECIMAL}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_EJG_ACTA
     *
     * @mbg.generated Tue Jul 20 11:38:47 CEST 2021
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("SCS_EJG_ACTA");
        
        sql.SET("IDACTA = #{record.idacta,jdbcType=DECIMAL}");
        sql.SET("IDINSTITUCIONACTA = #{record.idinstitucionacta,jdbcType=DECIMAL}");
        sql.SET("ANIOACTA = #{record.anioacta,jdbcType=DECIMAL}");
        sql.SET("IDINSTITUCIONEJG = #{record.idinstitucionejg,jdbcType=DECIMAL}");
        sql.SET("IDTIPOEJG = #{record.idtipoejg,jdbcType=DECIMAL}");
        sql.SET("ANIOEJG = #{record.anioejg,jdbcType=DECIMAL}");
        sql.SET("NUMEROEJG = #{record.numeroejg,jdbcType=DECIMAL}");
        sql.SET("IDTIPORATIFICACIONEJG = #{record.idtiporatificacionejg,jdbcType=DECIMAL}");
        sql.SET("IDFUNDAMENTOJURIDICO = #{record.idfundamentojuridico,jdbcType=DECIMAL}");
        sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=DATE}");
        sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=DECIMAL}");
        
        ScsEjgActaExample example = (ScsEjgActaExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_EJG_ACTA
     *
     * @mbg.generated Tue Jul 20 11:38:47 CEST 2021
     */
    public String updateByPrimaryKeySelective(ScsEjgActa record) {
        SQL sql = new SQL();
        sql.UPDATE("SCS_EJG_ACTA");
        
        if (record.getIdtiporatificacionejg() != null) {
            sql.SET("IDTIPORATIFICACIONEJG = #{idtiporatificacionejg,jdbcType=DECIMAL}");
        }
        
        if (record.getIdfundamentojuridico() != null) {
            sql.SET("IDFUNDAMENTOJURIDICO = #{idfundamentojuridico,jdbcType=DECIMAL}");
        }
        
        if (record.getFechamodificacion() != null) {
            sql.SET("FECHAMODIFICACION = #{fechamodificacion,jdbcType=DATE}");
        }
        
        if (record.getUsumodificacion() != null) {
            sql.SET("USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}");
        }
        
        sql.WHERE("IDACTA = #{idacta,jdbcType=DECIMAL}");
        sql.WHERE("IDINSTITUCIONACTA = #{idinstitucionacta,jdbcType=DECIMAL}");
        sql.WHERE("ANIOACTA = #{anioacta,jdbcType=DECIMAL}");
        sql.WHERE("IDINSTITUCIONEJG = #{idinstitucionejg,jdbcType=DECIMAL}");
        sql.WHERE("IDTIPOEJG = #{idtipoejg,jdbcType=DECIMAL}");
        sql.WHERE("ANIOEJG = #{anioejg,jdbcType=DECIMAL}");
        sql.WHERE("NUMEROEJG = #{numeroejg,jdbcType=DECIMAL}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_EJG_ACTA
     *
     * @mbg.generated Tue Jul 20 11:38:47 CEST 2021
     */
    protected void applyWhere(SQL sql, ScsEjgActaExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}