package org.itcgae.siga.db.mappers;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.db.entities.ScsJuzgadoprocedimiento;
import org.itcgae.siga.db.entities.ScsJuzgadoprocedimientoExample.Criteria;
import org.itcgae.siga.db.entities.ScsJuzgadoprocedimientoExample.Criterion;
import org.itcgae.siga.db.entities.ScsJuzgadoprocedimientoExample;

public class ScsJuzgadoprocedimientoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.SCS_JUZGADOPROCEDIMIENTO
	 * @mbg.generated  Mon Sep 09 13:43:09 CEST 2019
	 */
	public String countByExample(ScsJuzgadoprocedimientoExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("SCS_JUZGADOPROCEDIMIENTO");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.SCS_JUZGADOPROCEDIMIENTO
	 * @mbg.generated  Mon Sep 09 13:43:09 CEST 2019
	 */
	public String deleteByExample(ScsJuzgadoprocedimientoExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("SCS_JUZGADOPROCEDIMIENTO");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.SCS_JUZGADOPROCEDIMIENTO
	 * @mbg.generated  Mon Sep 09 13:43:09 CEST 2019
	 */
	public String insertSelective(ScsJuzgadoprocedimiento record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("SCS_JUZGADOPROCEDIMIENTO");
		if (record.getIdinstitucion() != null) {
			sql.VALUES("IDINSTITUCION", "#{idinstitucion,jdbcType=DECIMAL}");
		}
		if (record.getIdprocedimiento() != null) {
			sql.VALUES("IDPROCEDIMIENTO", "#{idprocedimiento,jdbcType=VARCHAR}");
		}
		if (record.getIdinstitucionJuzg() != null) {
			sql.VALUES("IDINSTITUCION_JUZG", "#{idinstitucionJuzg,jdbcType=DECIMAL}");
		}
		if (record.getIdjuzgado() != null) {
			sql.VALUES("IDJUZGADO", "#{idjuzgado,jdbcType=DECIMAL}");
		}
		if (record.getFechamodificacion() != null) {
			sql.VALUES("FECHAMODIFICACION", "#{fechamodificacion,jdbcType=TIMESTAMP}");
		}
		if (record.getUsumodificacion() != null) {
			sql.VALUES("USUMODIFICACION", "#{usumodificacion,jdbcType=DECIMAL}");
		}
		if (record.getFechabaja() != null) {
			sql.VALUES("FECHABAJA", "#{fechabaja,jdbcType=TIMESTAMP}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.SCS_JUZGADOPROCEDIMIENTO
	 * @mbg.generated  Mon Sep 09 13:43:09 CEST 2019
	 */
	public String selectByExample(ScsJuzgadoprocedimientoExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("IDINSTITUCION");
		} else {
			sql.SELECT("IDINSTITUCION");
		}
		sql.SELECT("IDPROCEDIMIENTO");
		sql.SELECT("IDINSTITUCION_JUZG");
		sql.SELECT("IDJUZGADO");
		sql.SELECT("FECHAMODIFICACION");
		sql.SELECT("USUMODIFICACION");
		sql.SELECT("FECHABAJA");
		sql.FROM("SCS_JUZGADOPROCEDIMIENTO");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.SCS_JUZGADOPROCEDIMIENTO
	 * @mbg.generated  Mon Sep 09 13:43:09 CEST 2019
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		ScsJuzgadoprocedimiento record = (ScsJuzgadoprocedimiento) parameter.get("record");
		ScsJuzgadoprocedimientoExample example = (ScsJuzgadoprocedimientoExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("SCS_JUZGADOPROCEDIMIENTO");
		if (record.getIdinstitucion() != null) {
			sql.SET("IDINSTITUCION = #{record.idinstitucion,jdbcType=DECIMAL}");
		}
		if (record.getIdprocedimiento() != null) {
			sql.SET("IDPROCEDIMIENTO = #{record.idprocedimiento,jdbcType=VARCHAR}");
		}
		if (record.getIdinstitucionJuzg() != null) {
			sql.SET("IDINSTITUCION_JUZG = #{record.idinstitucionJuzg,jdbcType=DECIMAL}");
		}
		if (record.getIdjuzgado() != null) {
			sql.SET("IDJUZGADO = #{record.idjuzgado,jdbcType=DECIMAL}");
		}
		if (record.getFechamodificacion() != null) {
			sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=TIMESTAMP}");
		}
		if (record.getUsumodificacion() != null) {
			sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=DECIMAL}");
		}
		if (record.getFechabaja() != null) {
			sql.SET("FECHABAJA = #{record.fechabaja,jdbcType=TIMESTAMP}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.SCS_JUZGADOPROCEDIMIENTO
	 * @mbg.generated  Mon Sep 09 13:43:09 CEST 2019
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("SCS_JUZGADOPROCEDIMIENTO");
		sql.SET("IDINSTITUCION = #{record.idinstitucion,jdbcType=DECIMAL}");
		sql.SET("IDPROCEDIMIENTO = #{record.idprocedimiento,jdbcType=VARCHAR}");
		sql.SET("IDINSTITUCION_JUZG = #{record.idinstitucionJuzg,jdbcType=DECIMAL}");
		sql.SET("IDJUZGADO = #{record.idjuzgado,jdbcType=DECIMAL}");
		sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=TIMESTAMP}");
		sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=DECIMAL}");
		sql.SET("FECHABAJA = #{record.fechabaja,jdbcType=TIMESTAMP}");
		ScsJuzgadoprocedimientoExample example = (ScsJuzgadoprocedimientoExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.SCS_JUZGADOPROCEDIMIENTO
	 * @mbg.generated  Mon Sep 09 13:43:09 CEST 2019
	 */
	public String updateByPrimaryKeySelective(ScsJuzgadoprocedimiento record) {
		SQL sql = new SQL();
		sql.UPDATE("SCS_JUZGADOPROCEDIMIENTO");
		if (record.getFechamodificacion() != null) {
			sql.SET("FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP}");
		}
		if (record.getUsumodificacion() != null) {
			sql.SET("USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}");
		}
		if (record.getFechabaja() != null) {
			sql.SET("FECHABAJA = #{fechabaja,jdbcType=TIMESTAMP}");
		}
		sql.WHERE("IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}");
		sql.WHERE("IDPROCEDIMIENTO = #{idprocedimiento,jdbcType=VARCHAR}");
		sql.WHERE("IDINSTITUCION_JUZG = #{idinstitucionJuzg,jdbcType=DECIMAL}");
		sql.WHERE("IDJUZGADO = #{idjuzgado,jdbcType=DECIMAL}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE.SCS_JUZGADOPROCEDIMIENTO
	 * @mbg.generated  Mon Sep 09 13:43:09 CEST 2019
	 */
	protected void applyWhere(SQL sql, ScsJuzgadoprocedimientoExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}