package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ScsProcurador;
import org.itcgae.siga.db.entities.ScsProcuradorExample;
import org.itcgae.siga.db.entities.ScsProcuradorKey;

public interface ScsProcuradorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @SelectProvider(type=ScsProcuradorSqlProvider.class, method="countByExample")
    long countByExample(ScsProcuradorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @DeleteProvider(type=ScsProcuradorSqlProvider.class, method="deleteByExample")
    int deleteByExample(ScsProcuradorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @Delete({
        "delete from SCS_PROCURADOR",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDPROCURADOR = #{idprocurador,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(ScsProcuradorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @Insert({
        "insert into SCS_PROCURADOR (IDINSTITUCION, IDPROCURADOR, ",
        "NOMBRE, DOMICILIO, ",
        "CODIGOPOSTAL, IDPROVINCIA, ",
        "IDPOBLACION, TELEFONO1, ",
        "TELEFONO2, FAX1, ",
        "FECHABAJA, FECHAMODIFICACION, ",
        "USUMODIFICACION, APELLIDOS1, ",
        "APELLIDOS2, EMAIL, ",
        "NCOLEGIADO, CODIGO, ",
        "IDCOLPROCURADOR)",
        "values (#{idinstitucion,jdbcType=DECIMAL}, #{idprocurador,jdbcType=DECIMAL}, ",
        "#{nombre,jdbcType=VARCHAR}, #{domicilio,jdbcType=VARCHAR}, ",
        "#{codigopostal,jdbcType=VARCHAR}, #{idprovincia,jdbcType=VARCHAR}, ",
        "#{idpoblacion,jdbcType=VARCHAR}, #{telefono1,jdbcType=VARCHAR}, ",
        "#{telefono2,jdbcType=VARCHAR}, #{fax1,jdbcType=VARCHAR}, ",
        "#{fechabaja,jdbcType=TIMESTAMP}, #{fechamodificacion,jdbcType=TIMESTAMP}, ",
        "#{usumodificacion,jdbcType=DECIMAL}, #{apellidos1,jdbcType=VARCHAR}, ",
        "#{apellidos2,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{ncolegiado,jdbcType=VARCHAR}, #{codigo,jdbcType=VARCHAR}, ",
        "#{idcolprocurador,jdbcType=VARCHAR})"
    })
    int insert(ScsProcurador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @InsertProvider(type=ScsProcuradorSqlProvider.class, method="insertSelective")
    int insertSelective(ScsProcurador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @SelectProvider(type=ScsProcuradorSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDPROCURADOR", property="idprocurador", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NOMBRE", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOMICILIO", property="domicilio", jdbcType=JdbcType.VARCHAR),
        @Result(column="CODIGOPOSTAL", property="codigopostal", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDPROVINCIA", property="idprovincia", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDPOBLACION", property="idpoblacion", jdbcType=JdbcType.VARCHAR),
        @Result(column="TELEFONO1", property="telefono1", jdbcType=JdbcType.VARCHAR),
        @Result(column="TELEFONO2", property="telefono2", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAX1", property="fax1", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHABAJA", property="fechabaja", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="APELLIDOS1", property="apellidos1", jdbcType=JdbcType.VARCHAR),
        @Result(column="APELLIDOS2", property="apellidos2", jdbcType=JdbcType.VARCHAR),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="NCOLEGIADO", property="ncolegiado", jdbcType=JdbcType.VARCHAR),
        @Result(column="CODIGO", property="codigo", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDCOLPROCURADOR", property="idcolprocurador", jdbcType=JdbcType.VARCHAR)
    })
    List<ScsProcurador> selectByExample(ScsProcuradorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @Select({
        "select",
        "IDINSTITUCION, IDPROCURADOR, NOMBRE, DOMICILIO, CODIGOPOSTAL, IDPROVINCIA, IDPOBLACION, ",
        "TELEFONO1, TELEFONO2, FAX1, FECHABAJA, FECHAMODIFICACION, USUMODIFICACION, APELLIDOS1, ",
        "APELLIDOS2, EMAIL, NCOLEGIADO, CODIGO, IDCOLPROCURADOR",
        "from SCS_PROCURADOR",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDPROCURADOR = #{idprocurador,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDPROCURADOR", property="idprocurador", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="NOMBRE", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOMICILIO", property="domicilio", jdbcType=JdbcType.VARCHAR),
        @Result(column="CODIGOPOSTAL", property="codigopostal", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDPROVINCIA", property="idprovincia", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDPOBLACION", property="idpoblacion", jdbcType=JdbcType.VARCHAR),
        @Result(column="TELEFONO1", property="telefono1", jdbcType=JdbcType.VARCHAR),
        @Result(column="TELEFONO2", property="telefono2", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAX1", property="fax1", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHABAJA", property="fechabaja", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="APELLIDOS1", property="apellidos1", jdbcType=JdbcType.VARCHAR),
        @Result(column="APELLIDOS2", property="apellidos2", jdbcType=JdbcType.VARCHAR),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="NCOLEGIADO", property="ncolegiado", jdbcType=JdbcType.VARCHAR),
        @Result(column="CODIGO", property="codigo", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDCOLPROCURADOR", property="idcolprocurador", jdbcType=JdbcType.VARCHAR)
    })
    ScsProcurador selectByPrimaryKey(ScsProcuradorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @UpdateProvider(type=ScsProcuradorSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ScsProcurador record, @Param("example") ScsProcuradorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @UpdateProvider(type=ScsProcuradorSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ScsProcurador record, @Param("example") ScsProcuradorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @UpdateProvider(type=ScsProcuradorSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ScsProcurador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PROCURADOR
     *
     * @mbg.generated Tue Oct 01 14:01:10 CEST 2019
     */
    @Update({
        "update SCS_PROCURADOR",
        "set NOMBRE = #{nombre,jdbcType=VARCHAR},",
          "DOMICILIO = #{domicilio,jdbcType=VARCHAR},",
          "CODIGOPOSTAL = #{codigopostal,jdbcType=VARCHAR},",
          "IDPROVINCIA = #{idprovincia,jdbcType=VARCHAR},",
          "IDPOBLACION = #{idpoblacion,jdbcType=VARCHAR},",
          "TELEFONO1 = #{telefono1,jdbcType=VARCHAR},",
          "TELEFONO2 = #{telefono2,jdbcType=VARCHAR},",
          "FAX1 = #{fax1,jdbcType=VARCHAR},",
          "FECHABAJA = #{fechabaja,jdbcType=TIMESTAMP},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
          "APELLIDOS1 = #{apellidos1,jdbcType=VARCHAR},",
          "APELLIDOS2 = #{apellidos2,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "NCOLEGIADO = #{ncolegiado,jdbcType=VARCHAR},",
          "CODIGO = #{codigo,jdbcType=VARCHAR},",
          "IDCOLPROCURADOR = #{idcolprocurador,jdbcType=VARCHAR}",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDPROCURADOR = #{idprocurador,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(ScsProcurador record);
}