package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ScsPretensionesproced;
import org.itcgae.siga.db.entities.ScsPretensionesprocedExample;
import org.itcgae.siga.db.entities.ScsPretensionesprocedKey;

public interface ScsPretensionesprocedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @SelectProvider(type=ScsPretensionesprocedSqlProvider.class, method="countByExample")
    long countByExample(ScsPretensionesprocedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @DeleteProvider(type=ScsPretensionesprocedSqlProvider.class, method="deleteByExample")
    int deleteByExample(ScsPretensionesprocedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @Delete({
        "delete from SCS_PRETENSIONESPROCED",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDPRETENSION = #{idpretension,jdbcType=DECIMAL}",
          "and IDPROCEDIMIENTO = #{idprocedimiento,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(ScsPretensionesprocedKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @Insert({
        "insert into SCS_PRETENSIONESPROCED (IDINSTITUCION, IDPRETENSION, ",
        "IDPROCEDIMIENTO, FECHAMODIFICACION, ",
        "USUMODIFICACION)",
        "values (#{idinstitucion,jdbcType=DECIMAL}, #{idpretension,jdbcType=DECIMAL}, ",
        "#{idprocedimiento,jdbcType=VARCHAR}, #{fechamodificacion,jdbcType=TIMESTAMP}, ",
        "#{usumodificacion,jdbcType=DECIMAL})"
    })
    int insert(ScsPretensionesproced record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @InsertProvider(type=ScsPretensionesprocedSqlProvider.class, method="insertSelective")
    int insertSelective(ScsPretensionesproced record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @SelectProvider(type=ScsPretensionesprocedSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDPRETENSION", property="idpretension", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDPROCEDIMIENTO", property="idprocedimiento", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)
    })
    List<ScsPretensionesproced> selectByExample(ScsPretensionesprocedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @Select({
        "select",
        "IDINSTITUCION, IDPRETENSION, IDPROCEDIMIENTO, FECHAMODIFICACION, USUMODIFICACION",
        "from SCS_PRETENSIONESPROCED",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDPRETENSION = #{idpretension,jdbcType=DECIMAL}",
          "and IDPROCEDIMIENTO = #{idprocedimiento,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDPRETENSION", property="idpretension", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IDPROCEDIMIENTO", property="idprocedimiento", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL)
    })
    ScsPretensionesproced selectByPrimaryKey(ScsPretensionesprocedKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @UpdateProvider(type=ScsPretensionesprocedSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ScsPretensionesproced record, @Param("example") ScsPretensionesprocedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @UpdateProvider(type=ScsPretensionesprocedSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ScsPretensionesproced record, @Param("example") ScsPretensionesprocedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @UpdateProvider(type=ScsPretensionesprocedSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ScsPretensionesproced record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_PRETENSIONESPROCED
     *
     * @mbg.generated Tue Oct 22 14:41:33 CEST 2019
     */
    @Update({
        "update SCS_PRETENSIONESPROCED",
        "set FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL}",
        "where IDINSTITUCION = #{idinstitucion,jdbcType=DECIMAL}",
          "and IDPRETENSION = #{idpretension,jdbcType=DECIMAL}",
          "and IDPROCEDIMIENTO = #{idprocedimiento,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ScsPretensionesproced record);
}