package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.ScsRenuncia;
import org.itcgae.siga.db.entities.ScsRenunciaExample;

public interface ScsRenunciaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @SelectProvider(type=ScsRenunciaSqlProvider.class, method="countByExample")
    long countByExample(ScsRenunciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @DeleteProvider(type=ScsRenunciaSqlProvider.class, method="deleteByExample")
    int deleteByExample(ScsRenunciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @Delete({
        "delete from SCS_RENUNCIA",
        "where IDRENUNCIA = #{idrenuncia,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Short idrenuncia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @Insert({
        "insert into SCS_RENUNCIA (IDRENUNCIA, DESCRIPCION, ",
        "FECHAMODIFICACION, USUMODIFICACION, ",
        "CODIGOEXT, BLOQUEADO, ",
        "FECHA_BAJA)",
        "values (#{idrenuncia,jdbcType=DECIMAL}, #{descripcion,jdbcType=VARCHAR}, ",
        "#{fechamodificacion,jdbcType=TIMESTAMP}, #{usumodificacion,jdbcType=DECIMAL}, ",
        "#{codigoext,jdbcType=VARCHAR}, #{bloqueado,jdbcType=CHAR}, ",
        "#{fechaBaja,jdbcType=TIMESTAMP})"
    })
    int insert(ScsRenuncia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @InsertProvider(type=ScsRenunciaSqlProvider.class, method="insertSelective")
    int insertSelective(ScsRenuncia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @SelectProvider(type=ScsRenunciaSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDRENUNCIA", property="idrenuncia", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="CODIGOEXT", property="codigoext", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOQUEADO", property="bloqueado", jdbcType=JdbcType.CHAR),
        @Result(column="FECHA_BAJA", property="fechaBaja", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ScsRenuncia> selectByExample(ScsRenunciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @Select({
        "select",
        "IDRENUNCIA, DESCRIPCION, FECHAMODIFICACION, USUMODIFICACION, CODIGOEXT, BLOQUEADO, ",
        "FECHA_BAJA",
        "from SCS_RENUNCIA",
        "where IDRENUNCIA = #{idrenuncia,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IDRENUNCIA", property="idrenuncia", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="DESCRIPCION", property="descripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="FECHAMODIFICACION", property="fechamodificacion", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="USUMODIFICACION", property="usumodificacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="CODIGOEXT", property="codigoext", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOQUEADO", property="bloqueado", jdbcType=JdbcType.CHAR),
        @Result(column="FECHA_BAJA", property="fechaBaja", jdbcType=JdbcType.TIMESTAMP)
    })
    ScsRenuncia selectByPrimaryKey(Short idrenuncia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @UpdateProvider(type=ScsRenunciaSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ScsRenuncia record, @Param("example") ScsRenunciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @UpdateProvider(type=ScsRenunciaSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ScsRenuncia record, @Param("example") ScsRenunciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @UpdateProvider(type=ScsRenunciaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ScsRenuncia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE.SCS_RENUNCIA
     *
     * @mbg.generated Tue Nov 12 18:27:20 CET 2019
     */
    @Update({
        "update SCS_RENUNCIA",
        "set DESCRIPCION = #{descripcion,jdbcType=VARCHAR},",
          "FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP},",
          "USUMODIFICACION = #{usumodificacion,jdbcType=DECIMAL},",
          "CODIGOEXT = #{codigoext,jdbcType=VARCHAR},",
          "BLOQUEADO = #{bloqueado,jdbcType=CHAR},",
          "FECHA_BAJA = #{fechaBaja,jdbcType=TIMESTAMP}",
        "where IDRENUNCIA = #{idrenuncia,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(ScsRenuncia record);
}