package org.itcgae.siga.db.mappers;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.db.entities.ScsTipoactuacion;
import org.itcgae.siga.db.entities.ScsTipoactuacionExample.Criteria;
import org.itcgae.siga.db.entities.ScsTipoactuacionExample.Criterion;
import org.itcgae.siga.db.entities.ScsTipoactuacionExample;

public class ScsTipoactuacionSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_TIPOACTUACION
	 * @mbg.generated  Tue Oct 03 11:14:56 CEST 2023
	 */
	public String countByExample(ScsTipoactuacionExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("SCS_TIPOACTUACION");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_TIPOACTUACION
	 * @mbg.generated  Tue Oct 03 11:14:56 CEST 2023
	 */
	public String deleteByExample(ScsTipoactuacionExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("SCS_TIPOACTUACION");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_TIPOACTUACION
	 * @mbg.generated  Tue Oct 03 11:14:56 CEST 2023
	 */
	public String insertSelective(ScsTipoactuacion record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("SCS_TIPOACTUACION");
		if (record.getIdinstitucion() != null) {
			sql.VALUES("IDINSTITUCION", "#{idinstitucion,jdbcType=NUMERIC}");
		}
		if (record.getIdtipoasistencia() != null) {
			sql.VALUES("IDTIPOASISTENCIA", "#{idtipoasistencia,jdbcType=NUMERIC}");
		}
		if (record.getIdtipoactuacion() != null) {
			sql.VALUES("IDTIPOACTUACION", "#{idtipoactuacion,jdbcType=NUMERIC}");
		}
		if (record.getDescripcion() != null) {
			sql.VALUES("DESCRIPCION", "#{descripcion,jdbcType=VARCHAR}");
		}
		if (record.getImporte() != null) {
			sql.VALUES("IMPORTE", "#{importe,jdbcType=NUMERIC}");
		}
		if (record.getFechamodificacion() != null) {
			sql.VALUES("FECHAMODIFICACION", "#{fechamodificacion,jdbcType=TIMESTAMP}");
		}
		if (record.getImportemaximo() != null) {
			sql.VALUES("IMPORTEMAXIMO", "#{importemaximo,jdbcType=NUMERIC}");
		}
		if (record.getUsumodificacion() != null) {
			sql.VALUES("USUMODIFICACION", "#{usumodificacion,jdbcType=NUMERIC}");
		}
		if (record.getFechabaja() != null) {
			sql.VALUES("FECHABAJA", "#{fechabaja,jdbcType=TIMESTAMP}");
		}
		if (record.getComisariajuzgadopordefecto() != null) {
			sql.VALUES("COMISARIAJUZGADOPORDEFECTO", "#{comisariajuzgadopordefecto,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_TIPOACTUACION
	 * @mbg.generated  Tue Oct 03 11:14:56 CEST 2023
	 */
	public String selectByExample(ScsTipoactuacionExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("IDINSTITUCION");
		} else {
			sql.SELECT("IDINSTITUCION");
		}
		sql.SELECT("IDTIPOASISTENCIA");
		sql.SELECT("IDTIPOACTUACION");
		sql.SELECT("DESCRIPCION");
		sql.SELECT("IMPORTE");
		sql.SELECT("FECHAMODIFICACION");
		sql.SELECT("IMPORTEMAXIMO");
		sql.SELECT("USUMODIFICACION");
		sql.SELECT("FECHABAJA");
		sql.SELECT("COMISARIAJUZGADOPORDEFECTO");
		sql.FROM("SCS_TIPOACTUACION");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_TIPOACTUACION
	 * @mbg.generated  Tue Oct 03 11:14:56 CEST 2023
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		ScsTipoactuacion record = (ScsTipoactuacion) parameter.get("record");
		ScsTipoactuacionExample example = (ScsTipoactuacionExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("SCS_TIPOACTUACION");
		if (record.getIdinstitucion() != null) {
			sql.SET("IDINSTITUCION = #{record.idinstitucion,jdbcType=NUMERIC}");
		}
		if (record.getIdtipoasistencia() != null) {
			sql.SET("IDTIPOASISTENCIA = #{record.idtipoasistencia,jdbcType=NUMERIC}");
		}
		if (record.getIdtipoactuacion() != null) {
			sql.SET("IDTIPOACTUACION = #{record.idtipoactuacion,jdbcType=NUMERIC}");
		}
		if (record.getDescripcion() != null) {
			sql.SET("DESCRIPCION = #{record.descripcion,jdbcType=VARCHAR}");
		}
		if (record.getImporte() != null) {
			sql.SET("IMPORTE = #{record.importe,jdbcType=NUMERIC}");
		}
		if (record.getFechamodificacion() != null) {
			sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=TIMESTAMP}");
		}
		if (record.getImportemaximo() != null) {
			sql.SET("IMPORTEMAXIMO = #{record.importemaximo,jdbcType=NUMERIC}");
		}
		if (record.getUsumodificacion() != null) {
			sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=NUMERIC}");
		}
		if (record.getFechabaja() != null) {
			sql.SET("FECHABAJA = #{record.fechabaja,jdbcType=TIMESTAMP}");
		}
		if (record.getComisariajuzgadopordefecto() != null) {
			sql.SET("COMISARIAJUZGADOPORDEFECTO = #{record.comisariajuzgadopordefecto,jdbcType=VARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_TIPOACTUACION
	 * @mbg.generated  Tue Oct 03 11:14:56 CEST 2023
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("SCS_TIPOACTUACION");
		sql.SET("IDINSTITUCION = #{record.idinstitucion,jdbcType=NUMERIC}");
		sql.SET("IDTIPOASISTENCIA = #{record.idtipoasistencia,jdbcType=NUMERIC}");
		sql.SET("IDTIPOACTUACION = #{record.idtipoactuacion,jdbcType=NUMERIC}");
		sql.SET("DESCRIPCION = #{record.descripcion,jdbcType=VARCHAR}");
		sql.SET("IMPORTE = #{record.importe,jdbcType=NUMERIC}");
		sql.SET("FECHAMODIFICACION = #{record.fechamodificacion,jdbcType=TIMESTAMP}");
		sql.SET("IMPORTEMAXIMO = #{record.importemaximo,jdbcType=NUMERIC}");
		sql.SET("USUMODIFICACION = #{record.usumodificacion,jdbcType=NUMERIC}");
		sql.SET("FECHABAJA = #{record.fechabaja,jdbcType=TIMESTAMP}");
		sql.SET("COMISARIAJUZGADOPORDEFECTO = #{record.comisariajuzgadopordefecto,jdbcType=VARCHAR}");
		ScsTipoactuacionExample example = (ScsTipoactuacionExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_TIPOACTUACION
	 * @mbg.generated  Tue Oct 03 11:14:56 CEST 2023
	 */
	public String updateByPrimaryKeySelective(ScsTipoactuacion record) {
		SQL sql = new SQL();
		sql.UPDATE("SCS_TIPOACTUACION");
		if (record.getDescripcion() != null) {
			sql.SET("DESCRIPCION = #{descripcion,jdbcType=VARCHAR}");
		}
		if (record.getImporte() != null) {
			sql.SET("IMPORTE = #{importe,jdbcType=NUMERIC}");
		}
		if (record.getFechamodificacion() != null) {
			sql.SET("FECHAMODIFICACION = #{fechamodificacion,jdbcType=TIMESTAMP}");
		}
		if (record.getImportemaximo() != null) {
			sql.SET("IMPORTEMAXIMO = #{importemaximo,jdbcType=NUMERIC}");
		}
		if (record.getUsumodificacion() != null) {
			sql.SET("USUMODIFICACION = #{usumodificacion,jdbcType=NUMERIC}");
		}
		if (record.getFechabaja() != null) {
			sql.SET("FECHABAJA = #{fechabaja,jdbcType=TIMESTAMP}");
		}
		if (record.getComisariajuzgadopordefecto() != null) {
			sql.SET("COMISARIAJUZGADOPORDEFECTO = #{comisariajuzgadopordefecto,jdbcType=VARCHAR}");
		}
		sql.WHERE("IDINSTITUCION = #{idinstitucion,jdbcType=NUMERIC}");
		sql.WHERE("IDTIPOASISTENCIA = #{idtipoasistencia,jdbcType=NUMERIC}");
		sql.WHERE("IDTIPOACTUACION = #{idtipoactuacion,jdbcType=NUMERIC}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_INT.SCS_TIPOACTUACION
	 * @mbg.generated  Tue Oct 03 11:14:56 CEST 2023
	 */
	protected void applyWhere(SQL sql, ScsTipoactuacionExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}