package org.itcgae.siga.db.mappers;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.itcgae.siga.db.entities.VPcajgAlcActErrorCam;
import org.itcgae.siga.db.entities.VPcajgAlcActErrorCamExample;

public interface VPcajgAlcActErrorCamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.V_PCAJG_ALC_ACT_ERROR_CAM
     *
     * @mbg.generated Mon May 16 16:04:08 CEST 2022
     */
    @SelectProvider(type=VPcajgAlcActErrorCamSqlProvider.class, method="countByExample")
    long countByExample(VPcajgAlcActErrorCamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.V_PCAJG_ALC_ACT_ERROR_CAM
     *
     * @mbg.generated Mon May 16 16:04:08 CEST 2022
     */
    @DeleteProvider(type=VPcajgAlcActErrorCamSqlProvider.class, method="deleteByExample")
    int deleteByExample(VPcajgAlcActErrorCamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.V_PCAJG_ALC_ACT_ERROR_CAM
     *
     * @mbg.generated Mon May 16 16:04:08 CEST 2022
     */
    @Insert({
        "insert into V_PCAJG_ALC_ACT_ERROR_CAM (IDINSTITUCION, IDFACTURACION, ",
        "CODIGO_ERROR, ERROR_DESCRIPCION, ",
        "CODIGO_CAMPO_ERROR, CAMPO_DESCRIPCION, ",
        "CUENTA)",
        "values (#{idinstitucion,jdbcType=DECIMAL}, #{idfacturacion,jdbcType=DECIMAL}, ",
        "#{codigoError,jdbcType=VARCHAR}, #{errorDescripcion,jdbcType=VARCHAR}, ",
        "#{codigoCampoError,jdbcType=VARCHAR}, #{campoDescripcion,jdbcType=VARCHAR}, ",
        "#{cuenta,jdbcType=DECIMAL})"
    })
    int insert(VPcajgAlcActErrorCam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.V_PCAJG_ALC_ACT_ERROR_CAM
     *
     * @mbg.generated Mon May 16 16:04:08 CEST 2022
     */
    @InsertProvider(type=VPcajgAlcActErrorCamSqlProvider.class, method="insertSelective")
    int insertSelective(VPcajgAlcActErrorCam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.V_PCAJG_ALC_ACT_ERROR_CAM
     *
     * @mbg.generated Mon May 16 16:04:08 CEST 2022
     */
    @SelectProvider(type=VPcajgAlcActErrorCamSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="IDINSTITUCION", property="idinstitucion", jdbcType=JdbcType.DECIMAL),
        @Result(column="IDFACTURACION", property="idfacturacion", jdbcType=JdbcType.DECIMAL),
        @Result(column="CODIGO_ERROR", property="codigoError", jdbcType=JdbcType.VARCHAR),
        @Result(column="ERROR_DESCRIPCION", property="errorDescripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="CODIGO_CAMPO_ERROR", property="codigoCampoError", jdbcType=JdbcType.VARCHAR),
        @Result(column="CAMPO_DESCRIPCION", property="campoDescripcion", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUENTA", property="cuenta", jdbcType=JdbcType.DECIMAL)
    })
    List<VPcajgAlcActErrorCam> selectByExample(VPcajgAlcActErrorCamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.V_PCAJG_ALC_ACT_ERROR_CAM
     *
     * @mbg.generated Mon May 16 16:04:08 CEST 2022
     */
    @UpdateProvider(type=VPcajgAlcActErrorCamSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") VPcajgAlcActErrorCam record, @Param("example") VPcajgAlcActErrorCamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USCGAE_INT.V_PCAJG_ALC_ACT_ERROR_CAM
     *
     * @mbg.generated Mon May 16 16:04:08 CEST 2022
     */
    @UpdateProvider(type=VPcajgAlcActErrorCamSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") VPcajgAlcActErrorCam record, @Param("example") VPcajgAlcActErrorCamExample example);
}