Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('message.fichaColegial.informarBajaInscripciones.cambioEstadoColegial','Si el colegiado está inscrito en turnos y/o guardias se dará de baja en todas las incripciones de forma automática. ¿Desea continuar? ','0','1',to_date('25/04/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('message.fichaColegial.informarBajaInscripciones.cambioEstadoColegial','Si el col·legiat està inscrit en torns i / o guàrdies es donarà de baixa en totes les inscripcions de forma automàtica. Voleu continuar?','0','2',to_date('25/04/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('message.fichaColegial.informarBajaInscripciones.cambioEstadoColegial','Si el colegiado está inscrito en turnos y/o guardias se dará de baja en todas las incripciones de forma automática. ¿Desea continuar? #GL','0','4',to_date('25/04/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('message.fichaColegial.informarBajaInscripciones.cambioEstadoColegial','Si el colegiado está inscrito en turnos y/o guardias se dará de baja en todas las incripciones de forma automática. ¿Desea continuar? #EU','0','3',to_date('25/04/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.fechaIncorporacionObligatorio','Para aprobar una solicitud debe rellenar la fecha de incorporación','0','1',to_date('26/04/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.fechaIncorporacionObligatorio','Per aprovar una sol·licitud ha d''omplir la data d''incorporació','0','2',to_date('26/04/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.fechaIncorporacionObligatorio','Para aprobar una solicitud debe rellenar la fecha de incorporación#EU','0','3',to_date('26/04/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.alterMutua.literal.fechaIncorporacionObligatorio','Para aprobar una solicitud debe rellenar la fecha de incorporación#GL','0','4',to_date('26/04/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.nuevaIncorporacion.literal.fechaPrimerEstado','Fecha Primer Estado','0','1',to_date('26/04/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.nuevaIncorporacion.literal.fechaPrimerEstado','Data Primer Estat','0','2',to_date('26/04/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.nuevaIncorporacion.literal.fechaPrimerEstado','Fecha Primer Estado#EU','0','3',to_date('26/04/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.nuevaIncorporacion.literal.fechaPrimerEstado','Fecha Primer Estado#GL','0','4',to_date('26/04/12','DD/MM/RR'),'0','19');


commit;