package org.itcgae.siga.db.services.cen.providers;

import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.DTOs.cen.DatosBancariosSearchDTO;
import org.itcgae.siga.db.mappers.CenGruposclienteClienteSqlProvider;

public class CenCuentasbancariasSqlExtendsProvider extends CenGruposclienteClienteSqlProvider{


	
	public String selectCuentasBancarias(DatosBancariosSearchDTO datosBancariosSearchDTO, String idInstitucion) {
		SQL sql = new SQL();
		sql.SELECT("CUENTA.TITULAR");
		sql.SELECT("CUENTA.IDCUENTA");
		sql.SELECT("CUENTA.IBAN");
		sql.SELECT("DECODE(DECODE(CUENTA.ABONOSJCS,'1',DECODE(CUENTA.ABONOCARGO,'T','ABONO/CARGO', DECODE(CUENTA.ABONOCARGO,'A','ABONO',DECODE(CUENTA.ABONOCARGO,'C','CARGO',''))) || '/SJCS',\r\n" + 
				   "DECODE(CUENTA.ABONOCARGO,'T','ABONO/CARGO', DECODE(CUENTA.ABONOCARGO,'A','ABONO',DECODE(CUENTA.ABONOCARGO,'C','CARGO','')))),'ABONO/CARGO/SJCS', 'PARA TODO',\r\n" + 
				   "DECODE(CUENTA.ABONOSJCS,'1',DECODE(CUENTA.ABONOCARGO,'T','ABONO/CARGO', DECODE(CUENTA.ABONOCARGO,'A','ABONO',DECODE(CUENTA.ABONOCARGO,'C','CARGO',''))) || '/SJCS',\r\n" + 
				   "DECODE(CUENTA.ABONOCARGO,'T','ABONO/CARGO', DECODE(CUENTA.ABONOCARGO,'A','ABONO',DECODE(CUENTA.ABONOCARGO,'C','CARGO','')))))AS USO");
		sql.SELECT("BANCO.BIC");
		sql.SELECT("MANDATOSERVICIO.FIRMA_FECHA AS FECHAFIRMASERVICIOS");
		sql.SELECT("MANDATOPRODUCTO.FIRMA_FECHA AS FECHAFIRMAPRODUCTOS");
		sql.SELECT("CUENTA.IDINSTITUCION");
		sql.SELECT("CUENTA.FECHABAJA");

		sql.FROM("CEN_PERSONA PER");
		sql.INNER_JOIN("CEN_CUENTASBANCARIAS CUENTA ON CUENTA.IDPERSONA = PER.IDPERSONA");
		sql.INNER_JOIN("CEN_BANCOS BANCO ON BANCO.CODIGO = CUENTA.CBO_CODIGO");
		sql.LEFT_OUTER_JOIN("CEN_MANDATOS_CUENTASBANCARIAS MANDATOSERVICIO ON (PER.IDPERSONA = MANDATOSERVICIO.IDPERSONA AND MANDATOSERVICIO.TIPOMANDATO = '0')");
		sql.LEFT_OUTER_JOIN("CEN_MANDATOS_CUENTASBANCARIAS MANDATOPRODUCTO ON (PER.IDPERSONA = MANDATOPRODUCTO.IDPERSONA AND MANDATOPRODUCTO.TIPOMANDATO = '1')");

		sql.WHERE("PER.IDPERSONA = '"+datosBancariosSearchDTO.getIdPersona()+"'");
		if (!datosBancariosSearchDTO.getHistorico()) {
			sql.WHERE("CUENTA.FECHABAJA is null");
		}
		
		sql.WHERE("CUENTA.IDINSTITUCION = '"+idInstitucion+"'");
		
		return sql.toString();
	}
	
	
}


