package org.itcgae.siga.db.services.cen.providers;

import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.DTOs.cen.DatosDireccionesSearchDTO;
import org.itcgae.siga.db.entities.CenDirecciones;
import org.itcgae.siga.db.mappers.CenComponentesSqlProvider;

public class CenDireccionesSqlExtendsProvider extends CenComponentesSqlProvider{
	
	public String selectDireccionesWs(String idPersona) {		
		SQL sql = new SQL();

		sql.SELECT_DISTINCT("CAT.DESCRIPCION AS TIPODIRECCION");
		sql.SELECT("DIRECCION.IDDIRECCION");
		sql.SELECT("DIRECCION.CODIGOPOSTAL");
		sql.SELECT("TO_CHAR(DIRECCION.FECHABAJA,'DD/MM/YYYY') AS FECHABAJA");
		sql.SELECT("DIRECCION.IDINSTITUCION");
		sql.SELECT("DIRECCION.DOMICILIO ");
		sql.SELECT("DIRECCION.IDPOBLACION");
		sql.SELECT("DIRECCION.IDPROVINCIA");
		sql.SELECT("DIRECCION.IDPAIS");
		sql.SELECT("DIRECCION.POBLACIONEXTRANJERA");
		sql.SELECT("DIRECCION.TELEFONO1");
		sql.SELECT("DIRECCION.FAX1");
		sql.SELECT("DIRECCION.MOVIL");
		sql.SELECT("DIRECCION.PAGINAWEB");
		sql.SELECT("DIRECCION.CORREOELECTRONICO");
		sql.SELECT("PAIS.CODIGOEXT AS IDEXTERNOPAIS");
		sql.SELECT("CATPAIS.DESCRIPCION AS NOMBREPAIS");
		sql.SELECT("POBLACION.CODIGOEXT AS IDEXTERNOPOBLACION");
		sql.SELECT("POBLACION.NOMBRE AS NOMBREPOBLACION");
		sql.SELECT("PROVINCIAS.CODIGOEXT AS IDEXTERNOPROVINCIA");
		sql.SELECT("PROVINCIAS.NOMBRE AS NOMBREPROVINCIA");
		sql.FROM("CEN_DIRECCIONES DIRECCION");
		sql.INNER_JOIN(" CEN_DIRECCION_TIPODIRECCION TIPODIRECCION ON (TIPODIRECCION.IDDIRECCION = DIRECCION.IDDIRECCION AND TIPODIRECCION.IDPERSONA = DIRECCION.IDPERSONA AND  TIPODIRECCION.IDINSTITUCION = DIRECCION.IDINSTITUCION) ");
		sql.INNER_JOIN(" CEN_TIPODIRECCION TIPO ON TIPO.IDTIPODIRECCION = TIPODIRECCION.IDTIPODIRECCION");
		sql.INNER_JOIN(" GEN_RECURSOS_CATALOGOS  CAT ON (CAT.IDRECURSO = TIPO.DESCRIPCION AND CAT.IDLENGUAJE = '1')");
		sql.LEFT_OUTER_JOIN("CEN_PAIS PAIS ON PAIS.IDPAIS = DIRECCION.IDPAIS");
		sql.LEFT_OUTER_JOIN("GEN_RECURSOS_CATALOGOS  CATPAIS ON (CATPAIS.IDRECURSO = PAIS.NOMBRE AND CATPAIS.IDLENGUAJE = '1')");
		sql.LEFT_OUTER_JOIN("CEN_PROVINCIAS PROVINCIAS ON PROVINCIAS.IDPROVINCIA = DIRECCION.IDPROVINCIA");
		sql.LEFT_OUTER_JOIN("CEN_POBLACIONES POBLACION ON POBLACION.IDPOBLACION = DIRECCION.IDPOBLACION");
		sql.WHERE("DIRECCION.IDPERSONA = '"+idPersona+"'");
		sql.WHERE("DIRECCION.FECHABAJA is null");
		sql.WHERE("TIPO.IDTIPODIRECCION = '3'");
		sql.ORDER_BY("FECHABAJA DESC");
		return sql.toString();
	}

	public String selectPartidoJudicial(String idPersona, String idInstitucion) {		
		SQL sql = new SQL();

		sql.SELECT("PARTIDO.NOMBRE AS NOMBREPARTIDO");
		sql.FROM("CEN_DIRECCIONES DIR");
		sql.INNER_JOIN(" CEN_POBLACIONES POB ON DIR.IDPOBLACION = POB.IDPOBLACION ");
		sql.INNER_JOIN(" CEN_DIRECCION_TIPODIRECCION TP ON DIR.IDDIRECCION = TP.IDDIRECCION AND DIR.IDPERSONA = TP.IDPERSONA AND TP.IDINSTITUCION = DIR.IDINSTITUCION AND TP.IDTIPODIRECCION = '2'");
		sql.INNER_JOIN(" CEN_PARTIDOJUDICIAL PARTIDO ON POB.IDPARTIDO = PARTIDO.IDPARTIDO");
		sql.WHERE(" dir.idpersona = '"+idPersona+"' and dir.idinstitucion = '"+idInstitucion+"' and dir.fechabaja is null");
		
		return sql.toString();
	}
	
	public String selectDirecciones(DatosDireccionesSearchDTO datosDireccionesSearchDTO,String idInstitucion) {
		
		SQL sqlPrincipal = new SQL();
		SQL sql = new SQL();
		
		
		sql.SELECT_DISTINCT(" CAT.DESCRIPCION");
		sql.SELECT_DISTINCT("DECODE(tipo.idtipodireccion,2,1,3,2,9,3,4) AS orden");
		sql.SELECT("DIRECCION.IDDIRECCION");
		sql.SELECT("TIPO.IDTIPODIRECCION");
		sql.SELECT("DIRECCION.CODIGOPOSTAL");
		sql.SELECT("TO_CHAR(DIRECCION.FECHABAJA,'DD/MM/YYYY') AS FECHABAJA");
		sql.SELECT("DIRECCION.IDINSTITUCION");
		sql.SELECT("DIRECCION.DOMICILIO ");
//		sql.SELECT("(DIRECCION.DOMICILIO || ' ' || DIRECCION.CODIGOPOSTAL || ' ' || NVL(POBLACION.NOMBRE,DIRECCION.POBLACIONEXTRANJERA) || ' ' ||PROVINCIAS.NOMBRE || ' ' || DECODE(DIRECCION.IDPAIS,191,'',CATPAIS.DESCRIPCION) ) AS DOMICILIOLISTA");
		sql.SELECT("(DIRECCION.DOMICILIO ) AS DOMICILIOLISTA");
		sql.SELECT("DIRECCION.IDPOBLACION");
		sql.SELECT("DIRECCION.IDPROVINCIA");
		sql.SELECT("DIRECCION.IDPAIS");
		sql.SELECT("DIRECCION.OTRAPROVINCIA");
		sql.SELECT("DIRECCION.TELEFONO1");
		sql.SELECT("DIRECCION.FAX1");
		sql.SELECT("DIRECCION.POBLACIONEXTRANJERA");
		sql.SELECT("DIRECCION.MOVIL");
		sql.SELECT("DIRECCION.FECHAMODIFICACION");
		sql.SELECT("DIRECCION.PAGINAWEB");
		sql.SELECT("DIRECCION.CORREOELECTRONICO");
		sql.SELECT("DIRECCION.PREFERENTE");
		sql.SELECT("PAIS.CODIGOEXT AS IDEXTERNOPAIS");
		sql.SELECT("CATPAIS.DESCRIPCION AS NOMBREPAIS");
		sql.SELECT("POBLACION.CODIGOEXT AS IDEXTERNOPOBLACION");
		sql.SELECT("NVL(POBLACION.NOMBRE,DIRECCION.POBLACIONEXTRANJERA) AS NOMBREPOBLACION");
		sql.SELECT("PROVINCIAS.CODIGOEXT AS IDEXTERNOPROVINCIA");
		sql.SELECT("PROVINCIAS.NOMBRE AS NOMBREPROVINCIA");
		sql.SELECT("DIRECCION.IDPERSONA AS IDPERSONA");
		sql.FROM("CEN_DIRECCIONES DIRECCION");
		sql.LEFT_OUTER_JOIN(" CEN_DIRECCION_TIPODIRECCION TIPODIRECCION ON (TIPODIRECCION.IDDIRECCION = DIRECCION.IDDIRECCION AND TIPODIRECCION.IDPERSONA = DIRECCION.IDPERSONA AND  TIPODIRECCION.IDINSTITUCION = DIRECCION.IDINSTITUCION) ");
		sql.LEFT_OUTER_JOIN(" CEN_TIPODIRECCION TIPO ON TIPO.IDTIPODIRECCION = TIPODIRECCION.IDTIPODIRECCION");
		sql.LEFT_OUTER_JOIN(" GEN_RECURSOS_CATALOGOS  CAT ON (CAT.IDRECURSO = TIPO.DESCRIPCION AND CAT.IDLENGUAJE = '1')");
		sql.LEFT_OUTER_JOIN("CEN_PAIS PAIS ON PAIS.IDPAIS = DIRECCION.IDPAIS");
		sql.LEFT_OUTER_JOIN("GEN_RECURSOS_CATALOGOS  CATPAIS ON (CATPAIS.IDRECURSO = PAIS.NOMBRE AND CATPAIS.IDLENGUAJE = '1')");
		sql.LEFT_OUTER_JOIN("CEN_PROVINCIAS PROVINCIAS ON PROVINCIAS.IDPROVINCIA = DIRECCION.IDPROVINCIA");
		sql.LEFT_OUTER_JOIN("CEN_POBLACIONES POBLACION ON POBLACION.IDPOBLACION = DIRECCION.IDPOBLACION");
		sql.WHERE("DIRECCION.IDPERSONA = '"+datosDireccionesSearchDTO.getIdPersona()+"'");
		if (!datosDireccionesSearchDTO.getHistorico()) {
			sql.WHERE("DIRECCION.FECHABAJA is null");
		}
		if (null != datosDireccionesSearchDTO.getIdTipo()) {
			sql.WHERE("TIPODIRECCION.IDTIPODIRECCION = '"+datosDireccionesSearchDTO.getIdTipo()+ "'");
		}
		sql.WHERE("DIRECCION.IDINSTITUCION = '"+idInstitucion+"'");
		sql.ORDER_BY("orden asc, DIRECCION.FECHAMODIFICACION desc");
	
		sqlPrincipal.SELECT_DISTINCT("LISTAGG(DIRECCIONES.DESCRIPCION, ';') WITHIN GROUP (ORDER BY DIRECCIONES.orden)  OVER (PARTITION BY DIRECCIONES.IDDIRECCION) AS TIPODIRECCION");
		sqlPrincipal.SELECT_DISTINCT("LISTAGG(DIRECCIONES.IDTIPODIRECCION, ';') WITHIN GROUP (ORDER BY DIRECCIONES.orden)  OVER (PARTITION BY DIRECCIONES.IDDIRECCION) AS IDTIPODIRECCIONLIST");
		sqlPrincipal.SELECT_DISTINCT("LISTAGG(DIRECCIONES.orden, ';') WITHIN GROUP (ORDER BY DIRECCIONES.orden)  OVER (PARTITION BY DIRECCIONES.IDDIRECCION) AS ordenlist");
		sqlPrincipal.SELECT("IDDIRECCION");
		sqlPrincipal.SELECT("CODIGOPOSTAL");
		sqlPrincipal.SELECT("FECHABAJA");
		sqlPrincipal.SELECT("IDINSTITUCION");
		sqlPrincipal.SELECT("DOMICILIOLISTA");
		sqlPrincipal.SELECT("DOMICILIO ");
		sqlPrincipal.SELECT("IDPOBLACION");
		sqlPrincipal.SELECT("IDPROVINCIA");
		sqlPrincipal.SELECT("IDPAIS");
		sqlPrincipal.SELECT("TELEFONO1");
		sqlPrincipal.SELECT("FAX1");
		sqlPrincipal.SELECT("MOVIL");
		sqlPrincipal.SELECT("POBLACIONEXTRANJERA");
		sqlPrincipal.SELECT("OTRAPROVINCIA");
		sqlPrincipal.SELECT("FECHAMODIFICACION");
		sqlPrincipal.SELECT("PAGINAWEB");
		sqlPrincipal.SELECT("CORREOELECTRONICO");
		sqlPrincipal.SELECT("IDEXTERNOPAIS");
		sqlPrincipal.SELECT("NOMBREPAIS");
		sqlPrincipal.SELECT("IDEXTERNOPOBLACION");
		sqlPrincipal.SELECT("NOMBREPOBLACION");
		sqlPrincipal.SELECT("IDEXTERNOPROVINCIA");
		sqlPrincipal.SELECT("NOMBREPROVINCIA");
		sqlPrincipal.SELECT("PREFERENTE");
		sqlPrincipal.SELECT("IDPERSONA");

		//sqlPrincipal.FROM(sql.toString());
		
		sqlPrincipal.FROM( "(" + sql.toString() + ") DIRECCIONES");
		sqlPrincipal.ORDER_BY("ordenlist");
		
		
		return sqlPrincipal.toString();
	}
	
	public String selectNewIdDireccion(String idPersona, String idInstitucion) {
		SQL sql = new SQL();
		sql.SELECT("NVL(MAX(DIRECCION.IDDIRECCION) + 1,1) AS IDDIRECCION");
		sql.FROM("CEN_DIRECCIONES DIRECCION");
		sql.WHERE("DIRECCION.IDPERSONA = '"+idPersona+"'");
		sql.WHERE("DIRECCION.IDINSTITUCION = '"+idInstitucion+"'");
		
		return sql.toString();
	}
	
	public String selectMaxIdDireccion() {
		SQL sql = new SQL();
		
		sql.SELECT("MAX(IDDIRECCION) +1 AS IDDIRECCION");
		sql.FROM("CEN_DIRECCIONES");
		return sql.toString();
	}

public String selectDireccionesSolEsp(String idPersona, String idDireccion,String idInstitucion) {
		
		SQL sqlPrincipal = new SQL();
		SQL sql = new SQL();
		
		
		sql.SELECT_DISTINCT(" CAT.DESCRIPCION");
		sql.SELECT("DIRECCION.IDDIRECCION");
		sql.SELECT("TIPO.IDTIPODIRECCION");
		sql.SELECT("DIRECCION.CODIGOPOSTAL");
		sql.SELECT("TO_CHAR(DIRECCION.FECHABAJA,'DD/MM/YYYY') AS FECHABAJA");
		sql.SELECT("DIRECCION.IDINSTITUCION");
		sql.SELECT("DIRECCION.DOMICILIO ");
//		sql.SELECT("(DIRECCION.DOMICILIO || ' ' || DIRECCION.CODIGOPOSTAL || ' ' || NVL(POBLACION.NOMBRE,DIRECCION.POBLACIONEXTRANJERA) || ' ' ||PROVINCIAS.NOMBRE || ' ' || DECODE(DIRECCION.IDPAIS,191,'',CATPAIS.DESCRIPCION) ) AS DOMICILIOLISTA");
		sql.SELECT("(DIRECCION.DOMICILIO ) AS DOMICILIOLISTA");
		sql.SELECT("DIRECCION.IDPOBLACION");
		sql.SELECT("DIRECCION.IDPROVINCIA");
		sql.SELECT("DIRECCION.IDPAIS");
		sql.SELECT("DIRECCION.OTRAPROVINCIA");
		sql.SELECT("DIRECCION.TELEFONO1");
		sql.SELECT("DIRECCION.FAX1");
		sql.SELECT("DIRECCION.POBLACIONEXTRANJERA");
		sql.SELECT("DIRECCION.MOVIL");
		sql.SELECT("DIRECCION.FECHAMODIFICACION");
		sql.SELECT("DIRECCION.PAGINAWEB");
		sql.SELECT("DIRECCION.CORREOELECTRONICO");
		sql.SELECT("PAIS.CODIGOEXT AS IDEXTERNOPAIS");
		sql.SELECT("CATPAIS.DESCRIPCION AS NOMBREPAIS");
		sql.SELECT("POBLACION.CODIGOEXT AS IDEXTERNOPOBLACION");
		sql.SELECT("NVL(POBLACION.NOMBRE,DIRECCION.POBLACIONEXTRANJERA) AS NOMBREPOBLACION");
		sql.SELECT("PROVINCIAS.CODIGOEXT AS IDEXTERNOPROVINCIA");
		sql.SELECT("PROVINCIAS.NOMBRE AS NOMBREPROVINCIA");
		sql.FROM("CEN_DIRECCIONES DIRECCION");
		sql.INNER_JOIN(" CEN_DIRECCION_TIPODIRECCION TIPODIRECCION ON (TIPODIRECCION.IDDIRECCION = DIRECCION.IDDIRECCION AND TIPODIRECCION.IDPERSONA = DIRECCION.IDPERSONA AND  TIPODIRECCION.IDINSTITUCION = DIRECCION.IDINSTITUCION) ");
		sql.INNER_JOIN(" CEN_TIPODIRECCION TIPO ON TIPO.IDTIPODIRECCION = TIPODIRECCION.IDTIPODIRECCION");
		sql.INNER_JOIN(" GEN_RECURSOS_CATALOGOS  CAT ON (CAT.IDRECURSO = TIPO.DESCRIPCION AND CAT.IDLENGUAJE = '1')");
		sql.LEFT_OUTER_JOIN("CEN_PAIS PAIS ON PAIS.IDPAIS = DIRECCION.IDPAIS");
		sql.LEFT_OUTER_JOIN("GEN_RECURSOS_CATALOGOS  CATPAIS ON (CATPAIS.IDRECURSO = PAIS.NOMBRE AND CATPAIS.IDLENGUAJE = '1')");
		sql.LEFT_OUTER_JOIN("CEN_PROVINCIAS PROVINCIAS ON PROVINCIAS.IDPROVINCIA = DIRECCION.IDPROVINCIA");
		sql.LEFT_OUTER_JOIN("CEN_POBLACIONES POBLACION ON POBLACION.IDPOBLACION = DIRECCION.IDPOBLACION");
		sql.WHERE("DIRECCION.IDPERSONA = '"+idPersona+"'");
		sql.WHERE("DIRECCION.FECHABAJA is null");
		sql.WHERE("DIRECCION.IDINSTITUCION = '"+idInstitucion+"'");
		sql.WHERE("DIRECCION.IDDIRECCION = '"+idDireccion+"'");
		sql.ORDER_BY("CAT.DESCRIPCION, DIRECCION.IDDIRECCION  ");

		sqlPrincipal.SELECT_DISTINCT("LISTAGG(DIRECCIONES.DESCRIPCION, ';') WITHIN GROUP (ORDER BY DIRECCIONES.DESCRIPCION)  OVER (PARTITION BY DIRECCIONES.IDDIRECCION) AS TIPODIRECCION");
		sqlPrincipal.SELECT_DISTINCT("LISTAGG(DIRECCIONES.IDTIPODIRECCION, ';') WITHIN GROUP (ORDER BY DIRECCIONES.IDTIPODIRECCION)  OVER (PARTITION BY DIRECCIONES.IDDIRECCION) AS IDTIPODIRECCIONLIST");
		sqlPrincipal.SELECT("IDDIRECCION");
		sqlPrincipal.SELECT("CODIGOPOSTAL");
		sqlPrincipal.SELECT("FECHABAJA");
		sqlPrincipal.SELECT("IDINSTITUCION");
		sqlPrincipal.SELECT("DOMICILIOLISTA");
		sqlPrincipal.SELECT("DOMICILIO ");
		sqlPrincipal.SELECT("IDPOBLACION");
		sqlPrincipal.SELECT("IDPROVINCIA");
		sqlPrincipal.SELECT("IDPAIS");
		sqlPrincipal.SELECT("TELEFONO1");
		sqlPrincipal.SELECT("FAX1");
		sqlPrincipal.SELECT("MOVIL");
		sqlPrincipal.SELECT("POBLACIONEXTRANJERA");
		sqlPrincipal.SELECT("OTRAPROVINCIA");

		sqlPrincipal.SELECT("FECHAMODIFICACION");
		sqlPrincipal.SELECT("PAGINAWEB");
		sqlPrincipal.SELECT("CORREOELECTRONICO");
		sqlPrincipal.SELECT("IDEXTERNOPAIS");
		sqlPrincipal.SELECT("NOMBREPAIS");
		sqlPrincipal.SELECT("IDEXTERNOPOBLACION");
		sqlPrincipal.SELECT("NOMBREPOBLACION");
		sqlPrincipal.SELECT("IDEXTERNOPROVINCIA");
		sqlPrincipal.SELECT("NOMBREPROVINCIA");
		//sqlPrincipal.FROM(sql.toString());
		
		sqlPrincipal.FROM( "(" + sql.toString() + ") DIRECCIONES");
		
		return sqlPrincipal.toString();
	}


	public String getNumDirecciones(CenDirecciones beanDir, int tipoDireccionFacturacion) {
		SQL sql = new SQL();
		sql.SELECT("SELECT COUNT(1) AS IDDIRECCION");
		sql.FROM("CEN_DIRECCIONES DIRECCION");
		sql.JOIN(" CEN_DIRECCION_TIPODIRECCION TIPODIRECCION ON (TIPODIRECCION.IDDIRECCION = DIRECCION.IDDIRECCION AND TIPODIRECCION.IDPERSONA = DIRECCION.IDPERSONA AND  TIPODIRECCION.IDINSTITUCION = DIRECCION.IDINSTITUCION) ");
		sql.WHERE("DIRECCION.IDINSTITUCION = '"+beanDir.getIdinstitucion()+"'");
		sql.WHERE("DIRECCION.IDPERSONA = '"+beanDir.getIdpersona()+"'");
		sql.WHERE("DIRECCION.FECHABAJA IS NULLL");
		sql.WHERE("TIPODIRECCION.IDTIPODIRECCION = '"+tipoDireccionFacturacion+"'");
		
		
		return sql.toString();
	}
	
	
	
	public String getTiposDireccion(Short idinstitucion, Long idPersona, Long idDireccion,	String idioma) {
		SQL sql = new SQL();
		
		sql.SELECT("f_siga_gettiposdireccion("+idinstitucion+", "+idPersona+", "+idDireccion+", "+ idioma +") as DESCRIPCION");
		sql.FROM("DUAL");
		return sql.toString();
	}
	
	
	
	public String getDireccionLetradoSalidaOficio(String idPersona, String idInstitucion) {
		
		SQL sql = new SQL();
		SQL sql2 = new SQL();
		
		sql2.SELECT(" DIR.domicilio DOMICILIO_DESPACHO_LETRADO ");
		sql2.SELECT(" DIR.codigopostal CP_DESPACHO_LETRADO ");
		sql2.SELECT(" DIR.idpoblacion IDPOBLACION_DESPACHO_LETRADO ");
		sql2.SELECT(" DIR.poblacionextranjera POBLACION_DESPACHO_LETRADO ");					
		sql2.SELECT(" DIR.idprovincia IDPROVINCIA_DESPACHO_LETRADO ");
		sql2.SELECT(" DIR.telefono1 TELEFONO1_DESPACHO_LETRADO ");
		sql2.SELECT(" DIR.telefono2 TELEFONO2_DESPACHO_LETRADO ");
		sql2.SELECT(" DIR.fax1 FAX1_DESPACHO_LETRADO ");
		sql2.SELECT(" DIR.fax2 FAX2_DESPACHO_LETRADO ");
		sql2.SELECT(" DIR.correoelectronico EMAIL_DESPACHO_LETRADO ");
		sql2.SELECT(" DIR.movil MOVIL_DESPACHO_LETRADO");
		sql2.SELECT(" (SELECT NOMBRE FROM CEN_PROVINCIAS WHERE IDPROVINCIA = DIR.idprovincia) PROVINCIA_DESPACHO_LETRADO");
		sql2.FROM(" CEN_DIRECCIONES DIR, " +
				" CEN_DIRECCION_TIPODIRECCION TIP ");
		sql2.WHERE("dir.idinstitucion = tip.idinstitucion ");
		sql2.WHERE("dir.idpersona = tip.idpersona  ");
		sql2.WHERE("dir.iddireccion = tip.iddireccion ");
		sql2.WHERE("tip.idtipodireccion = 2 ");
		sql2.WHERE("dir.fechabaja is null ");
		sql2.WHERE("dir.idinstitucion = " + idInstitucion );
		sql2.WHERE("dir.idpersona = " + idPersona);
		sql2.ORDER_BY("dir.fechamodificacion DESC ");
		sql.SELECT("* FROM ("+ sql2 + ")" );
		
		sql.WHERE(" ROWNUM = 1 "); 
		
		return sql.toString();
	}
	
	public String getDireccionPersonalSalidaOficio(String idPersona, String idInstitucion) {
		
		SQL sql = new SQL();
		SQL sql2 = new SQL();
		
		sql2.SELECT(" DIR.domicilio DOMICILIO_GUARDIA_LETRADO ");
		sql2.SELECT(" DIR.codigopostal CP_GUARDIA_LETRADO ");
		sql2.SELECT(" DIR.idpoblacion IDPOBLACION_GUARDIA_LETRADO ");
		sql2.SELECT(" DIR.poblacionextranjera POBLACION_GUARDIA_LETRADO ");					
		sql2.SELECT(" DIR.idprovincia IDPROVINCIA_GUARDIA_LETRADO ");
		sql2.SELECT(" DIR.telefono1 TELEFONO1_GUARDIA_LETRADO "); 
		sql2.SELECT(" DIR.telefono2 TELEFONO2_GUARDIA_LETRADO ");
		sql2.SELECT(" DIR.fax1 FAX1_GUARDIA_LETRADO ");
		sql2.SELECT(" DIR.fax2 FAX2_GUARDIA_LETRADO "); 
		sql2.SELECT(" DIR.correoelectronico EMAIL_GUARDIA_LETRADO "); 
		sql2.SELECT(" DIR.movil MOVIL_GUARDIA_LETRADO");
		sql2.SELECT(" (SELECT NOMBRE FROM CEN_PROVINCIAS WHERE IDPROVINCIA = DIR.idprovincia) PROVINCIA_GUARDIA_LETRADO");
		sql2.FROM(" CEN_DIRECCIONES DIR, " +
				" CEN_DIRECCION_TIPODIRECCION TIP ");
		sql2.WHERE("dir.idinstitucion = tip.idinstitucion ");
		sql2.WHERE("dir.idpersona = tip.idpersona  ");
		sql2.WHERE("dir.iddireccion = tip.iddireccion ");
		sql2.WHERE("tip.idtipodireccion = 2 ");
		sql2.WHERE("dir.fechabaja is null ");
		sql2.WHERE("dir.idinstitucion = " + idInstitucion );
		sql2.WHERE("dir.idpersona = " + idPersona);
		sql2.ORDER_BY("dir.fechamodificacion DESC ");
		
		sql.SELECT("* FROM ("+ sql2 + ")" );
		
		sql.WHERE("  ROWNUM = 1 "); 
		
		return sql.toString();
	}
	
	public String getIdProvinciaImpreso190(String idPersona, String idinstitucion, int tipoDireccionFac ) {
		SQL sql = new SQL();
		sql.SELECT("IDPROVINCIA");
		sql.FROM("CEN_DIRECCIONES");
		sql.WHERE("IDINSTITUCION = "+idinstitucion);
		sql.WHERE("IDPERSONA = "+idPersona);
		sql.WHERE("IDDIRECCION = F_SIGA_GETIDDIRECCION_TIPOPREF(" + idinstitucion +","+idPersona+","+ tipoDireccionFac +")");
		
		
		return sql.toString();
	}

	public String getEntradaDireccionEspecifica(String idPersona, String idInstitucion, String idDireccion) {
		SQL subQueryPoblacion = new SQL();
		subQueryPoblacion.SELECT("PO.NOMBRE");
		subQueryPoblacion.FROM("CEN_POBLACIONES PO");
		subQueryPoblacion.WHERE("PO.IDPOBLACION = D.IDPOBLACION");

		SQL subQueryProvincia = new SQL();
		subQueryProvincia.SELECT("PRO.NOMBRE");
		subQueryProvincia.FROM("CEN_PROVINCIAS PRO");
		subQueryProvincia.WHERE("PRO.IDPROVINCIA = D.IDPROVINCIA");

		SQL sql = new SQL();
		sql.SELECT("D.IDPERSONA");
		sql.SELECT("D.IDINSTITUCION");
		sql.SELECT("D.IDDIRECCION");
		sql.SELECT("NVL(D.DOMICILIO, '-') DOMICILIO");
		sql.SELECT("NVL(D.CODIGOPOSTAL, '-') CODIGOPOSTAL");
		sql.SELECT("NVL(D.TELEFONO1, '-') TELEFONO1");
		sql.SELECT("D.TELEFONO2 TELEFONO2");
		sql.SELECT("D.MOVIL MOVIL");
		sql.SELECT("D.FAX1");
		sql.SELECT("D.FAX2");
		sql.SELECT("NVL(D.CORREOELECTRONICO, '-') CORREOELECTRONICO");
		sql.SELECT("D.PAGINAWEB");
		sql.SELECT("D.FECHABAJA");
		sql.SELECT("D.PREFERENTE");
		sql.SELECT("D.IDPAIS");
		sql.SELECT("D.IDPROVINCIA");
		sql.SELECT("D.IDPOBLACION");
		sql.SELECT("D.POBLACIONEXTRANJERA");
		sql.SELECT("D.FECHAMODIFICACION");
		sql.SELECT("D.USUMODIFICACION");
		sql.SELECT("(" + subQueryPoblacion + ") POBLACION");
		sql.SELECT("(" + subQueryProvincia + ") PROVINCIA");
		sql.FROM("CEN_DIRECCIONES D");

		String innerJoin = "CEN_DIRECCION_TIPODIRECCION TD ON TD.IDINSTITUCION = D.IDINSTITUCION AND TD.IDPERSONA = D.IDPERSONA AND TD.IDDIRECCION = D.IDDIRECCION";

		if (idDireccion != null && !idDireccion.equals("")) {
			if (new Integer(idDireccion) != null) {
				innerJoin += " AND TD.IDTIPODIRECCION = " + idDireccion;
			} else {
				innerJoin += " UPPER(D.PREFERENTE) LIKE UPPER('%" + idDireccion + "%')";
			}
		}

		sql.INNER_JOIN(innerJoin);
		sql.WHERE("D.IDINSTITUCION = " + idInstitucion);
		sql.WHERE("D.IDPERSONA = " + idPersona);
		sql.WHERE("D.FECHABAJA IS NULL");
		sql.WHERE("ROWNUM < 2");

		return sql.toString();
	}

	public String getDirecciones(Long idPersona, Integer idInstitucion, boolean bIncluirRegistrosConBajaLogica) {
		SQL sql = new SQL();

		sql.SELECT("CEN_DIRECCIONES.IDINSTITUCION");
		sql.SELECT("CEN_DIRECCIONES.IDPERSONA");
		sql.SELECT("CEN_DIRECCIONES.IDDIRECCION");
		sql.SELECT("CEN_DIRECCIONES.DOMICILIO");
		sql.SELECT("CEN_DIRECCIONES.CODIGOPOSTAL");
		sql.SELECT("CEN_DIRECCIONES.TELEFONO1");
		sql.SELECT("CEN_DIRECCIONES.TELEFONO2");
		sql.SELECT("CEN_DIRECCIONES.MOVIL");
		sql.SELECT("CEN_DIRECCIONES.FAX1");
		sql.SELECT("CEN_DIRECCIONES.FAX2");
		sql.SELECT("CEN_DIRECCIONES.CORREOELECTRONICO");
		sql.SELECT("CEN_DIRECCIONES.PAGINAWEB");
		sql.SELECT("CEN_DIRECCIONES.FECHABAJA");
		sql.SELECT("CEN_DIRECCIONES.PREFERENTE");
		sql.SELECT("CEN_DIRECCIONES.IDPAIS AS IDPAISDIREC");
		sql.SELECT("CEN_DIRECCIONES.IDPROVINCIA");
		sql.SELECT("CEN_DIRECCIONES.IDPOBLACION");
		sql.SELECT("CEN_DIRECCIONES.POBLACIONEXTRANJERA");
		sql.SELECT("CEN_DIRECCIONES.FECHAMODIFICACION");
		sql.SELECT("CEN_DIRECCIONES.USUMODIFICACION");
		sql.SELECT("CEN_DIRECCIONES.OTRAPROVINCIA");
		sql.SELECT("CEN_POBLACIONES.NOMBRE AS POBLACION");
		sql.SELECT("CEN_PROVINCIAS.NOMBRE AS PROVINCIA");
		sql.SELECT("F_SIGA_GETRECURSO(CEN_PAIS.NOMBRE, 1) AS NOMBREPAIS");
		sql.SELECT("CEN_PAIS.IDPAIS AS IDPAIS");
		sql.SELECT("F_SIGA_GETTIPOSDIRECCION(CEN_DIRECCIONES.IDINSTITUCION, CEN_DIRECCIONES.IDPERSONA, CEN_DIRECCIONES.IDDIRECCION, 1) AS DESCRIPCIONTIPODIRECCION");
		sql.SELECT("F_SIGA_GET_IDTIPOSDIRECCION(CEN_DIRECCIONES.IDINSTITUCION, CEN_DIRECCIONES.IDPERSONA, CEN_DIRECCIONES.IDDIRECCION) AS IDTIPODIRECCION");
		sql.SELECT("NVL((SELECT INS.ABREVIATURA FROM CEN_INSTITUCION INS WHERE INS.IDINSTITUCION = CEN_DIRECCIONES.IDINSTITUCIONALTA), '') AS COLEGIOORIGEN");

		sql.FROM("CEN_DIRECCIONES " +
				"LEFT JOIN CEN_POBLACIONES ON CEN_DIRECCIONES.IDPOBLACION = CEN_POBLACIONES.IDPOBLACION " +
				"LEFT JOIN CEN_PROVINCIAS ON CEN_DIRECCIONES.IDPROVINCIA = CEN_PROVINCIAS.IDPROVINCIA " +
				"LEFT JOIN CEN_PAIS ON CEN_DIRECCIONES.IDPAIS = CEN_PAIS.IDPAIS");

		sql.WHERE("CEN_DIRECCIONES.IDPERSONA = " + idPersona);
		sql.WHERE("CEN_DIRECCIONES.IDINSTITUCION = " + idInstitucion);

		if (!bIncluirRegistrosConBajaLogica) {
			sql.WHERE("CEN_DIRECCIONES.FECHABAJA IS NULL");
		}

		sql.ORDER_BY("CEN_DIRECCIONES.IDINSTITUCION");
		sql.ORDER_BY("CEN_DIRECCIONES.IDPERSONA");
		sql.ORDER_BY("CEN_DIRECCIONES.IDDIRECCION");

		return sql.toString();
	}
}
