package org.itcgae.siga.db.services.cen.providers;

import org.apache.ibatis.jdbc.SQL;
import org.itcgae.siga.db.mappers.CenNocolegiadoSqlProvider;

public class CenNocolegiadoSqlExtendsProvider extends CenNocolegiadoSqlProvider{


//	SELECT COL.IDINSTITUCION AS IDINSTITUCION
//	, COL.IDPERSONA AS IDPERSONA
//	,PER.NIFCIF AS NIF
//	,CONCAT(PER.NOMBRE ||' ',CONCAT(PER.APELLIDOS1 || ' ',PER.APELLIDOS2)) AS DENOMINACION
//	, I.ABREVIATURA AS ABREVIATURA 
//	,PER.FECHANACIMIENTO AS FECHACONSTITUCION
//	,COL.SOCIEDADPROFESIONAL AS SOCIEDADPROFESIONAL
//	,CA.DESCRIPCION AS TIPO
//	, COL.FECHA_BAJA AS FECHA_BAJA
//	,NVL(COUNT(DISTINCT PER2.IDPERSONA),0) AS NUMEROINTEGRANTES
//	,LISTAGG(CONCAT(PER2.NOMBRE ||' ',CONCAT(PER2.APELLIDOS1 || ' ',PER2.APELLIDOS2)), '; ') WITHIN GROUP (ORDER BY PER2.NOMBRE) NOMBRESINTEGRANTES
//	FROM CEN_NOCOLEGIADO COL
//	INNER JOIN CEN_PERSONA PER ON PER.IDPERSONA = COL.IDPERSONA
//	INNER JOIN CEN_INSTITUCION I ON COL.IDINSTITUCION = I.IDINSTITUCION 
//	LEFT JOIN CEN_TIPOSOCIEDAD  TIPOSOCIEDAD ON TIPOSOCIEDAD.LETRACIF = COL.TIPO
//	LEFT JOIN  GEN_RECURSOS_CATALOGOS CA ON (TIPOSOCIEDAD.DESCRIPCION = CA.IDRECURSO  AND CA.IDLENGUAJE = '1')
//	LEFT JOIN CEN_GRUPOSCLIENTE_CLIENTE GRUPOS_CLIENTE ON (GRUPOS_CLIENTE.IDINSTITUCION = I.IDINSTITUCION AND COL.IDPERSONA = GRUPOS_CLIENTE.IDPERSONA)
//	LEFT JOIN CEN_COMPONENTES COM ON (COM.IDPERSONA = COL.IDPERSONA AND COL.IDINSTITUCION = COM.IDINSTITUCION )
//	LEFT JOIN CEN_CLIENTE CLI ON (COM.CEN_CLIENTE_IDPERSONA = CLI.IDPERSONA AND CLI.IDINSTITUCION = COM.IDINSTITUCION )
//	LEFT JOIN CEN_PERSONA PER2 ON PER2.IDPERSONA = CLI.IDPERSONA
//	WHERE 
//	I.IDINSTITUCION = :IdInstitucion
//	AND PER.NIFCIF LIKE :NIF
//	AND GRUPOS_CLIENTE.IDGRUPO IN (:grupos)
//	AND COL.TIPO = :TIPO
//	AND UPPER(CAMPO DENOMINACION DE LA SELECT)) LIKE UPPER(‘%:DENOMINACION%’)
//	AND UPPER(CAMPO INTEGRANTE DE LA SELECT)) LIKE UPPER(‘%:INTEGRANTE %’)
//
//	GROUP BY COL.IDINSTITUCION, COL.IDPERSONA,PER.NIFCIF, PER.NOMBRE,PER.APELLIDOS1, PER.APELLIDOS2, I.ABREVIATURA, GRUPOS_CLIENTE.IDGRUPO,
//	PER.FECHANACIMIENTO,COL.SOCIEDADPROFESIONAL,COL.TIPO,CA.DESCRIPCION ;

	
	public String searchLegalPersons() {
		SQL sql = new SQL();
		
		sql.SELECT("COL.IDINSTITUCION AS IDINSTITUCION");
		sql.SELECT("COL.IDPERSONA AS IDPERSONA");
		sql.SELECT("PER.NIFCIF AS NIF");
		sql.SELECT("CONCAT(PER.NOMBRE ||' ',CONCAT(PER.APELLIDOS1 || ' ',PER.APELLIDOS2)) AS DENOMINACION");
		sql.SELECT("I.ABREVIATURA AS ABREVIATURA");
		sql.SELECT("PER.FECHANACIMIENTO AS FECHACONSTITUCION");
		sql.SELECT("COL.SOCIEDADPROFESIONAL AS SOCIEDADPROFESIONAL");
		sql.SELECT("CA.DESCRIPCION AS TIPO");
		sql.SELECT("COL.FECHA_BAJA AS FECHA_BAJA");
		sql.SELECT("NVL(COUNT(DISTINCT PER2.IDPERSONA),0) AS NUMEROINTEGRANTES");
		sql.SELECT("LISTAGG(CONCAT(PER2.NOMBRE ||' ',CONCAT(PER2.APELLIDOS1 || ' ',PER2.APELLIDOS2)), '; ') WITHIN GROUP (ORDER BY PER2.NOMBRE) NOMBRESINTEGRANTES");
		
		sql.FROM("CEN_NOCOLEGIADO COL");
		
		sql.INNER_JOIN("CEN_PERSONA PER ON PER.IDPERSONA = COL.IDPERSONA");
		sql.INNER_JOIN("CEN_INSTITUCION I ON COL.IDINSTITUCION = I.IDINSTITUCION "
				+ "LEFT JOIN CEN_TIPOSOCIEDAD  TIPOSOCIEDAD ON TIPOSOCIEDAD.LETRACIF = COL.TIPO "
				+ "LEFT JOIN  GEN_RECURSOS_CATALOGOS CA ON (TIPOSOCIEDAD.DESCRIPCION = CA.IDRECURSO  AND CA.IDLENGUAJE = '1')"
				+ "LEFT JOIN CEN_GRUPOSCLIENTE_CLIENTE GRUPOS_CLIENTE ON (GRUPOS_CLIENTE.IDINSTITUCION = I.IDINSTITUCION AND COL.IDPERSONA = GRUPOS_CLIENTE.IDPERSONA)"
				+ "LEFT JOIN CEN_COMPONENTES COM ON (COM.IDPERSONA = COL.IDPERSONA AND COL.IDINSTITUCION = COM.IDINSTITUCION )"
				+ "LEFT JOIN CEN_CLIENTE CLI ON (COM.CEN_CLIENTE_IDPERSONA = CLI.IDPERSONA AND CLI.IDINSTITUCION = COM.IDINSTITUCION )"
				+ "LEFT JOIN CEN_PERSONA PER2 ON PER2.IDPERSONA = CLI.IDPERSONA ");
		sql.WHERE("I.IDINSTITUCION = :IdInstitucion");
		sql.WHERE("PER.NIFCIF LIKE :NIF");
		sql.WHERE("GRUPOS_CLIENTE.IDGRUPO IN (:grupos)");
		sql.WHERE("COL.TIPO = :TIPO");
		sql.WHERE("UPPER(CAMPO DENOMINACION DE LA SELECT) LIKE UPPER('%:DENOMINACION%')");
		sql.WHERE("UPPER(CAMPO INTEGRANTE DE LA SELECT)) LIKE UPPER('%:INTEGRANTE %')");
		sql.WHERE("");
		
		sql.GROUP_BY("COL.IDINSTITUCION");
		sql.GROUP_BY("COL.IDPERSONA");
		sql.GROUP_BY("PER.NIFCIF");
		sql.GROUP_BY("PER.NOMBRE");
		sql.GROUP_BY("PER.APELLIDOS1");
		sql.GROUP_BY("PER.APELLIDOS2");
		sql.GROUP_BY("I.ABREVIATURA");
		sql.GROUP_BY("GRUPOS_CLIENTE.IDGRUPO");
		sql.GROUP_BY("PER.FECHANACIMIENTO");
		sql.GROUP_BY("COL.SOCIEDADPROFESIONAL");
		sql.GROUP_BY("COL.TIPO");
		sql.GROUP_BY("CA.DESCRIPCION");
		sql.GROUP_BY("COL.FECHA_BAJA");
		
		return sql.toString();
	}
	
}
