ALTER TABLE ADM_ROL ADD TIPOACCESO varchar(255);

UPDATE ADM_ROL SET TIPOACCESO = 'USER' WHERE IDROL = '1';
UPDATE ADM_ROL SET TIPOACCESO = 'USER' WHERE IDROL = '2';
UPDATE ADM_ROL SET TIPOACCESO = 'USER' WHERE IDROL = '3';
UPDATE ADM_ROL SET TIPOACCESO = 'USER' WHERE IDROL = '4';
UPDATE ADM_ROL SET TIPOACCESO = 'USER' WHERE IDROL = '5';
UPDATE ADM_ROL SET TIPOACCESO = 'USER' WHERE IDROL = '6';
UPDATE ADM_ROL SET TIPOACCESO = 'ADMIN' WHERE IDROL = '7';
UPDATE ADM_ROL SET TIPOACCESO = 'USER' WHERE IDROL = '8';
UPDATE ADM_ROL SET TIPOACCESO = 'USER' WHERE IDROL = '9';

commit;

ALTER TABLE ADM_ROL ADD LETRADO varchar(255);

UPDATE ADM_ROL SET LETRADO = 1 WHERE IDROL = '1';
UPDATE ADM_ROL SET LETRADO = 1 WHERE IDROL = '2';
UPDATE ADM_ROL SET LETRADO = 0 WHERE IDROL = '3';
UPDATE ADM_ROL SET LETRADO = 0 WHERE IDROL = '4';
UPDATE ADM_ROL SET LETRADO = 0 WHERE IDROL = '5';
UPDATE ADM_ROL SET LETRADO = 0 WHERE IDROL = '6';
UPDATE ADM_ROL SET LETRADO = 0 WHERE IDROL = '7';
UPDATE ADM_ROL SET LETRADO = 1 WHERE IDROL = '8';
UPDATE ADM_ROL SET LETRADO = 1 WHERE IDROL = '9';

commit;

-- INSERTAR UN NUEVO PUNTO DE MENU EN EL MENU PRINCIPAL

-- Primero insertamos los puntos de menu en la tabla procesos

Insert into GEN_PROCESOS 
(IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values 
('020','GEN','1','Y',to_date('10/10/18','DD/MM/RR'),'0','Desplegar Menú Formación',null,'0','10');

Insert into GEN_PROCESOS 
(IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values 
('021','GEN','1','Y',to_date('10/10/18','DD/MM/RR'),'0','Desplegar Menú Agenda',null,'0','10');

-- Luego insertamos los items de cada punto de menu en la tabla proceso

Insert into GEN_PROCESOS 
(IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values 
('20A','FOR','1','Y',to_date('10/10/18','DD/MM/RR'),'0','Buscar Cursos',null,'020','10');

Insert into GEN_PROCESOS 
(IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values 
('20B','FOR','1','Y',to_date('10/10/18','DD/MM/RR'),'0','Buscar Inscripciones',null,'020','10');

Insert into GEN_PROCESOS 
(IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values 
('21A','AGE','1','Y',to_date('10/10/18','DD/MM/RR'),'0','Agenda',null,'021','10');

-- Insertamos traducciones de los puntos de menu

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion','Formación','0','1',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion','Formacion#GL','0','4',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion','Formació','0','2',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion','Formacion#EU','0','3',to_date('10/10/18','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.agenda','Agenda','0','1',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.agenda','Agenda#GL','0','4',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.agenda','Agenda','0','2',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.agenda','Agenda#EU','0','3',to_date('10/10/18','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarCursos','Buscar Cursos','0','1',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarCursos','Buscar Cursos#GL','0','4',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarCursos','Cerca cursos','0','2',to_date('10/10/18','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarInscripciones','Buscar Inscripciones','0','1',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarInscripciones','Buscar Inscripciones#GL','0','4',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarInscripciones','Cerca Inscripcions','0','2',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarInscripciones','Buscar Inscripciones#EU','0','3',to_date('10/10/18','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion','Formación','0','1',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion','Formación#GL','0','4',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion','Formació','0','2',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion','Formación#EU','0','3',to_date('10/10/18','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.agenda','Agenda','0','1',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.agenda','Agenda#GL','0','4',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.agenda','Agenda','0','2',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.agenda','Agenda#EU','0','3',to_date('10/10/18','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarCursos','Buscar Cursos','0','1',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarCursos','Buscar Cursos#GL','0','4',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarCursos','Cerca cursos','0','2',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarCursos','Buscar Cursos#EU','0','3',to_date('10/10/18','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarInscripciones','Buscar Inscripciones','0','1',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarInscripciones','Buscar Inscripciones#GL','0','4',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarInscripciones','Buscar Inscripcions','0','2',to_date('10/10/18','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('menu.formacion.buscarInscripciones','Buscar Inscripciones#EU','0','3',to_date('10/10/18','DD/MM/RR'),'0','19');

-- Insertamos puntos de menu en la tabla menu

Insert into GEN_MENU 
(IDMENU,ORDEN,TAGWIDTH,IDPARENT,FECHAMODIFICACION,USUMODIFICACION,URI_IMAGEN,IDRECURSO,GEN_MENU_IDMENU,IDPROCESO,IDLENGUAJE,PATH,FECHA_BAJA,IDCLASS) values
('020','30500','80',' ',to_date('10/10/18','DD/MM/RR'),'0',null,'menu.formacion',null,'020','1','opcionMenu',null,null);

Insert into GEN_MENU 
(IDMENU,ORDEN,TAGWIDTH,IDPARENT,FECHAMODIFICACION,USUMODIFICACION,URI_IMAGEN,IDRECURSO,GEN_MENU_IDMENU,IDPROCESO,IDLENGUAJE,PATH,FECHA_BAJA,IDCLASS) values
('021','30700','80',' ',to_date('10/10/18','DD/MM/RR'),'0',null,'menu.agenda',null,'021','1','opcionMenu',null,null);

Insert into GEN_MENU 
(IDMENU,ORDEN,TAGWIDTH,IDPARENT,FECHAMODIFICACION,USUMODIFICACION,URI_IMAGEN,IDRECURSO,GEN_MENU_IDMENU,IDPROCESO,IDLENGUAJE,PATH,FECHA_BAJA,IDCLASS) values
('20A','30501','80','020',to_date('10/10/18','DD/MM/RR'),'0',null,'menu.formacion.buscarCursos',null,'20A','1','buscarCursos',null,null);

Insert into GEN_MENU 
(IDMENU,ORDEN,TAGWIDTH,IDPARENT,FECHAMODIFICACION,USUMODIFICACION,URI_IMAGEN,IDRECURSO,GEN_MENU_IDMENU,IDPROCESO,IDLENGUAJE,PATH,FECHA_BAJA,IDCLASS) values
('20B','30502','80','020',to_date('10/10/18','DD/MM/RR'),'0',null,'menu.formacion.buscarInscripciones',null,'20B','1','buscarInscripciones',null,null);

Insert into GEN_MENU 
(IDMENU,ORDEN,TAGWIDTH,IDPARENT,FECHAMODIFICACION,USUMODIFICACION,URI_IMAGEN,IDRECURSO,GEN_MENU_IDMENU,IDPROCESO,IDLENGUAJE,PATH,FECHA_BAJA,IDCLASS) values
('21A','30701','80','021',to_date('10/10/18','DD/MM/RR'),'0',null,'menu.agenda',null,'21A','1','agenda',null,null);


commit;





