
CREATE SEQUENCE  "USCGAE"."SEQ_AGEREPETICIONEVENTO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE ; 

CREATE SEQUENCE  "USCGAE"."SEQ_AGEFESTIVOS"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE ; 

CREATE SEQUENCE  "USCGAE"."SEQ_AGENOTIFICACIONESEVENTO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE ; 

CREATE SEQUENCE  "USCGAE"."SEQ_AGEEVENTO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE; 

CREATE SEQUENCE  "USCGAE"."SEQ_AGECALENDARIO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE; 

CREATE SEQUENCE  "USCGAE"."SEQ_AGEPERMISOSCALENDARIO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE; 

CREATE SEQUENCE  "USCGAE"."SEQ_FORCURSO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE; 

CREATE SEQUENCE  "USCGAE"."SEQ_FORPERSONACURSO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE; 

CREATE SEQUENCE  "USCGAE"."SEQ_FORINSCRIPCION"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE; 

CREATE SEQUENCE  "USCGAE"."SEQ_FOR_INSCRIPCIONESMASIVAS"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE; 

CREATE SEQUENCE  "USCGAE"."SEQ_FOR_CERTIFICADOSCURSO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE; 

CREATE SEQUENCE  "USCGAE"."SEQ_AGEASISTENCIAEVENTO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE; 


COMMIT;