Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2000','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2000','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2000','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2001','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2001','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2001','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2002','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2002','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2002','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2003','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2003','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2003','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2004','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2004','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2004','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2005','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2005','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2005','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2006','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2006','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2006','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2007','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2007','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2007','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2008','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2008','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2008','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2009','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2009','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2009','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2010','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2010','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2010','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2011','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2011','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2011','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2012','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2012','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2012','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2013','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2013','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2013','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2014','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2014','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2014','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2015','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2015','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2015','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2016','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2016','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2016','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2018','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2018','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2018','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2020','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2020','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2020','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2022','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2022','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2022','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2024','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2024','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2024','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2027','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2027','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2027','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2029','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2029','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2029','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2032','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2032','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2032','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2033','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2033','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2033','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2034','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2034','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2034','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2036','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2036','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2036','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2038','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2038','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2038','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2041','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2041','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2041','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2043','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2043','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2043','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2045','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2045','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2045','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2047','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2047','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2047','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2048','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2048','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2048','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2051','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2051','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2051','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2054','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2054','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2054','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2055','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2055','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2055','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2057','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2057','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2057','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2059','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2059','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2059','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2060','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2060','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2060','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2063','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2063','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2063','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2065','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2065','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2065','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2069','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2069','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'2069','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3000','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3000','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3000','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3001','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3001','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3001','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3002','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3002','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3002','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3003','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3003','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3003','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3004','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3004','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3004','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3005','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3005','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3005','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3006','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3006','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3006','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3007','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3007','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3007','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3008','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3008','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3008','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3009','Calendario General','0',to_date('28/01/2018','DD/MM/RR'),null,'1','#53ddec');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3009','Calendario Laboral','0',to_date('28/01/2018','DD/MM/RR'),null,'2','#f7af08');
Insert into AGE_CALENDARIO (IDCALENDARIO,IDINSTITUCION,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA,IDTIPOCALENDARIO,COLOR) values (SEQ_AGECALENDARIO.NEXTVAL,'3009','Calendario Formación','0',to_date('28/01/2018','DD/MM/RR'),null,'3','#c3ef44');

commit;
