Insert into GEN_PROPERTIES (FICHERO,PARAMETRO,VALOR) values ('SIGA','scs.ficheros.inscripciones','inscripciones');

ALTER TABLE FOR_INSCRIPCIONESMASIVAS ADD IDFICHEROLOG NUMBER(10,0);
ALTER TABLE FOR_INSCRIPCIONESMASIVAS ADD IDFICHERO NUMBER(10,0);
commit;