Insert into AGE_TIPONOTIFICACIONEVENTO (IDTIPONOTIFICACIONEVENTO,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA) values ('1','87120834857','0',to_date('29/11/18','DD/MM/RR'),null);
Insert into AGE_TIPONOTIFICACIONEVENTO (IDTIPONOTIFICACIONEVENTO,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA) values ('2','87120834858','0',to_date('29/11/18','DD/MM/RR'),null);
Insert into AGE_TIPONOTIFICACIONEVENTO (IDTIPONOTIFICACIONEVENTO,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA) values ('3','87120834859','0',to_date('29/11/18','DD/MM/RR'),null);
Insert into AGE_TIPONOTIFICACIONEVENTO (IDTIPONOTIFICACIONEVENTO,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA) values ('4','87120834860','0',to_date('29/11/18','DD/MM/RR'),null);
Insert into AGE_TIPONOTIFICACIONEVENTO (IDTIPONOTIFICACIONEVENTO,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA) values ('5','87120834861','0',to_date('29/11/18','DD/MM/RR'),null);
Insert into AGE_TIPONOTIFICACIONEVENTO (IDTIPONOTIFICACIONEVENTO,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA) values ('6','87120834862','0',to_date('29/11/18','DD/MM/RR'),null);
Insert into AGE_TIPONOTIFICACIONEVENTO (IDTIPONOTIFICACIONEVENTO,DESCRIPCION,USUMODIFICACION,FECHAMODIFICACION,FECHABAJA) values ('7','87120834863','0',to_date('29/11/18','DD/MM/RR'),null);
