ALTER TABLE MOD_PLANTILLADOC_CONSULTA
DROP CONSTRAINT FK_PLANTILLADOCCONSULTA;

ALTER TABLE MOD_PLANTILLADOC_CONSULTA
ADD (IDINSTITUCION_CONSULTA NUMBER(4) );

ALTER TABLE MOD_PLANTILLADOC_CONSULTA
ADD CONSTRAINT FK_PLANTILLADOCCONSULTA FOREIGN KEY
(
  IDINSTITUCION_CONSULTA
, IDCONSULTA
)
REFERENCES CON_CONSULTA
(
  IDINSTITUCION
, IDCONSULTA
)
ENABLE;


UPDATE mod_plantilladoc_consulta set idinstitucion_consulta = idinstitucion;

ALTER TABLE MOD_PLANTILLADOC_CONSULTA  
MODIFY (IDINSTITUCION_CONSULTA NOT NULL);


ALTER TABLE MOD_PLANTILLAENVIO_CONSULTA
DROP CONSTRAINT FK_CONSULTA;

ALTER TABLE MOD_PLANTILLAENVIO_CONSULTA
ADD (IDINSTITUCION_CONSULTA NUMBER(4) );

ALTER TABLE MOD_PLANTILLAENVIO_CONSULTA
ADD CONSTRAINT FK_CONSULTA FOREIGN KEY
(
  IDINSTITUCION_CONSULTA
, IDCONSULTA
)
REFERENCES CON_CONSULTA
(
  IDINSTITUCION
, IDCONSULTA
)
ENABLE;

UPDATE MOD_PLANTILLAENVIO_CONSULTA set idinstitucion_consulta = idinstitucion;

ALTER TABLE MOD_PLANTILLAENVIO_CONSULTA
MODIFY (IDINSTITUCION_CONSULTA NOT NULL);


ALTER TABLE MOD_CLASECOMUNICACIONES 
ADD (RUTAPLANTILLA VARCHAR2(100));

COMMIT;


