ALTER TABLE MOD_MODELOCOMUNICACION 
ADD (IDPLANTILLAENVIOS NUMBER(10) );
COMMENT ON COLUMN MOD_MODELOCOMUNICACION.IDPLANTILLAENVIOS IS 'Identificador de la plantilla de envio por defecto del modelo';

ALTER TABLE MOD_MODELOCOMUNICACION 
ADD (IDTIPOENVIOS NUMBER(3) );
COMMENT ON COLUMN MOD_MODELOCOMUNICACION.IDTIPOENVIOS IS 'Identificador del tipo de envío de la plantilla de envio por defecto del modelo';

ALTER TABLE MOD_MODELOCOMUNICACION
ADD CONSTRAINT FK_MODELOPLANTILLAENVIOS FOREIGN KEY
(
  IDINSTITUCION 
, IDTIPOENVIOS 
, IDPLANTILLAENVIOS 
)
REFERENCES ENV_PLANTILLASENVIOS
(
  IDINSTITUCION 
, IDTIPOENVIOS 
, IDPLANTILLAENVIOS 
)
ENABLE;

COMMIT;