UPDATE MOD_CLASECOMUNICACIONES SET RUTAPLANTILLA = 'informes_genericos/%%IDINSTITUCION%%/generico_censo' WHERE IDCLASECOMUNICACION = 1;
UPDATE MOD_CLASECOMUNICACIONES SET RUTAPLANTILLA = 'informes_genericos/%%IDINSTITUCION%%/informe_sanciones' WHERE IDCLASECOMUNICACION = 2;
UPDATE MOD_CLASECOMUNICACIONES SET RUTAPLANTILLA = 'informes_genericos/%%IDINSTITUCION%%/mandato_orden' WHERE IDCLASECOMUNICACION = 3;
UPDATE MOD_CLASECOMUNICACIONES SET RUTAPLANTILLA = 'informes_genericos/%%IDINSTITUCION%%/mandato_anexo' WHERE IDCLASECOMUNICACION = 4;