UPDATE MOD_CLASECOMUNICACIONES SET RUTAPLANTILLA = 'generico_censo' WHERE IDCLASECOMUNICACION = 1;
UPDATE MOD_CLASECOMUNICACIONES SET RUTAPLANTILLA = 'informe_sanciones' WHERE IDCLASECOMUNICACION = 2;
UPDATE MOD_CLASECOMUNICACIONES SET RUTAPLANTILLA = 'mandato_orden' WHERE IDCLASECOMUNICACION = 3;
UPDATE MOD_CLASECOMUNICACIONES SET RUTAPLANTILLA = 'mandato_anexo' WHERE IDCLASECOMUNICACION = 4;