ALTER TABLE MOD_MODELO_PLANTILLADOCUMENTO 
ADD (GENERACIONEXCEL NUMBER(1) );

COMMENT ON COLUMN MOD_MODELO_PLANTILLADOCUMENTO.GENERACIONEXCEL IS 'Indica si la plantilla es la de ejecución de la consulta';
