-----------------METER EL IDDIRECCION EN LA PLANTILLAENVIO-----------------------
SET AUTOPRINT ON;
SET SERVEROUTPUT ON;

DECLARE

idinstitucion NUMBER(4,0);
idpersona NUMBER(10,0);
idtipoenvios NUMBER(2,0);
idplantillaenvios NUMBER(5,0);
contador NUMBER(10):= 0;

CURSOR cursorDireccion is 
    SELECT REMITENTE.IDINSTITUCION, REMITENTE.IDTIPOENVIOS, REMITENTE.IDPLANTILLAENVIOS ,DIR.IDDIRECCION, REMITENTE.IDPERSONA
    FROM ENV_PLANTILLASENVIOS PLANTILLA
    JOIN ENV_PLANTILLAREMITENTES REMITENTE ON remitente.idtipoenvios = plantilla.idtipoenvios AND remitente.idplantillaenvios = PLANTILLA.idplantillaenvios 
    AND REMITENTE.IDINSTITUCION = plantilla.idinstitucion and remitente.idpersona = plantilla.idpersona 
    JOIN CEN_DIRECCIONES DIR ON DIR.IDPERSONA = REMITENTE.IDPERSONA AND DIR.DOMICILIO = REMITENTE.DOMICILIO AND REMITENTE.IDINSTITUCION = DIR.IDINSTITUCION;

BEGIN
    DBMS_OUTPUT.ENABLE(1000000);
    DBMS_OUTPUT.PUT_LINE('Script iddireccion empieza: '|| to_char(sysdate, 'DD-MM-YYYY HH24:MI:SS'));
    
    FOR REMITENTE IN cursorDireccion
    LOOP
    UPDATE ENV_PLANTILLASENVIOS SET IDDIRECCION = REMITENTE.IDDIRECCION WHERE IDPLANTILLAENVIOS = REMITENTE.IDPLANTILLAENVIOS AND IDTIPOENVIOS = REMITENTE.IDTIPOENVIOS AND 
    IDINSTITUCION = REMITENTE.IDINSTITUCION AND IDPERSONA = REMITENTE.IDPERSONA;
    contador := contador +1;
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Script iddireccion acaba: '|| to_char(sysdate, 'DD-MM-YYYY HH24:MI:SS'));
    DBMS_OUTPUT.PUT_LINE(' Se han actualizado ' || contador || ' filas.');
END;
