<wsdl:definitions xmlns:tns="urn:registroSociedades.ws.sspp.itcgae.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:registroSociedades.ws.sspp.itcgae.org">
	<wsdl:documentation>
		Servicio para la actualizacion de los registros de sociedades profesionales
	</wsdl:documentation>
	<wsdl:types>
		<xs:schema targetNamespace="urn:registroSociedades.ws.sspp.itcgae.org">
			<xs:include schemaLocation="RegistroSociedadesServer.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="getListaSociedadesMessage">
		<wsdl:part name="parameters" element="tns:getListaSociedadesRequest"/>
	</wsdl:message>
	<wsdl:message name="getListaSociedadesResponseMessage">
		<wsdl:part name="parameters" element="tns:getListaSociedadesResponse"/>
	</wsdl:message>
	<wsdl:portType name="SociedadesServerPortType">
		<wsdl:operation name="getListaSociedades">
			<wsdl:input message="tns:getListaSociedadesMessage"/>
			<wsdl:output message="tns:getListaSociedadesResponseMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SociedadesServerSoapBinding" type="tns:SociedadesServerPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getListaSociedades">
			<soap:operation soapAction="urn:registroSociedades.ws.sspp.itcgae.org/getListaSociedades" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="SociedadesServerService">
		<wsdl:port name="SociedadesServerPort" binding="tns:SociedadesServerSoapBinding">
			<soap:address location="https://sociedades.abogacia.es/registro/SociedadesServerService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>

