spool TRADUCCIONES MENSAJES VALIDACIONES.log
prompt TRADUCCIONES MENSAJES VALIDACIONES.log
select to_char(sysdate, 'hh24:mi:ss') as "Inicio" from dual;
prompt .

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.parentesco','Es necesario que rellene el campo Parentesco para guardar el registro','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.parentesco','Cal que ompli el camp Parentiu per guardar el registre','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.parentesco','Es necesario que rellene el campo Parentesco para guardar el registro#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.parentesco','Es necesario que rellene el campo Parentesco para guardar el registro#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.sex.estcivil.regconyugal','Es necesario que rellene los siguientes campos: Dirección, Sexo, Estado Civil y Regimen Conyugal para guardar el registro','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.sex.estcivil.regconyugal','Cal que ompli les següents camps: Direcció, Sexe, Estat Civil i Regimen Conjugal per guardar el registre','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.sex.estcivil.regconyugal','Es necesario que rellene los siguientes campos: Dirección, Sexo, Estado Civil y Regimen Conyugal para guardar el registro#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.sex.estcivil.regconyugal','Es necesario que rellene los siguientes campos: Dirección, Sexo, Estado Civil y Regimen Conyugal para guardar el registro#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.sex.estcivil.regconyugal','Es necesario que rellene los siguientes campos: Sexo, Estado Civil y Regimen Conyugal para guardar el registro','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.sex.estcivil.regconyugal','Cal que ompli les següents camps: Sexe, Estat Civil i Regimen Conjugal per guardar el registre','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.sex.estcivil.regconyugal','Es necesario que rellene los siguientes campos: Sexo, Estado Civil y Regimen Conyugal para guardar el registro#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.sex.estcivil.regconyugal','Es necesario que rellene los siguientes campos: Sexo, Estado Civil y Regimen Conyugal para guardar el registro#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.nacionalidad','Es necesario que rellene el campo Nacionalidad para guardar el registro','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.nacionalidad','Cal que ompli el camp Nacionalitat per guardar el registre','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.nacionalidad','Es necesario que rellene el campo Nacionalidad para guardar el registro#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.nacionalidad','Es necesario que rellene el campo Nacionalidad para guardar el registro#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.nacionalidad.parentesco','Es necesario que rellene los siguientes campos: Direccion, Nacionalidad y Parentesco para guardar el registro','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.nacionalidad.parentesco','Cal que ompli les següents camps: Direccion, Nacionalitat i Parentiu per guardar el registre','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.nacionalidad.parentesco','EEs necesario que rellene los siguientes campos: Direccion, Nacionalidad y Parentesco para guardar el registro#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.nacionalidad.parentesco','Es necesario que rellene los siguientes campos: Direccion, Nacionalidad y Parentesco para guardar el registro#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.nacionalidad.parentesco','Es necesario que rellene los siguientes campos: Nacionalidad y Parentesco para guardar el registro','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.nacionalidad.parentesco','Cal que ompli les següents camps: Nacionalitat i Parentiu per guardar el registre','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.nacionalidad.parentesco','EEs necesario que rellene los siguientes campos: Nacionalidad y Parentesco para guardar el registro#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.nacionalidad.parentesco','Es necesario que rellene los siguientes campos: Nacionalidad y Parentesco para guardar el registro#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.fechaNac.parentesco','Es necesario que rellene los siguientes campos: Dirección, Fecha Nacimiento y Parentesco para guardar el registro','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.fechaNac.parentesco','Cal que ompli les següents camps: Direcció, Data Naixement i Parentiu per guardar el registre','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.fechaNac.parentesco','Es necesario que rellene los siguientes campos: Dirección, Fecha Nacimiento y Parentesco para guardar el registro#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.dir.fechaNac.parentesco','Es necesario que rellene los siguientes campos: Dirección, Fecha Nacimiento y Parentesco para guardar el registro#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.fechaNac.parentesco','Es necesario que rellene los siguientes campos: Fecha Nacimiento y Parentesco para guardar el registro','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.fechaNac.parentesco','Cal que ompli les següents camps: Data Naixement i Parentiu per guardar el registre','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.fechaNac.parentesco','Es necesario que rellene los siguientes campos: Fecha Nacimiento y Parentesco para guardar el registro#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.fechaNac.parentesco','Es necesario que rellene los siguientes campos: Fecha Nacimiento y Parentesco para guardar el registro#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.sexo','Es necesario que rellene el campo Sexo para guardar el registro','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.sexo','Cal que ompli el camp Sexe per guardar el registre','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.sexo','Es necesario que rellene el campo Sexo para guardar el registro#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.validacion.tipoPcajg.sexo','Es necesario que rellene el campo Sexo para guardar el registro#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.asociarRepresentante.menorJusticiable','El justiciable es menor. Es obligatorio introducir su representante legal. Si no dispone del dato no introduzca fecha de nacimiento hasta que disponga de esa información','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.asociarRepresentante.menorJusticiable','El justiciable és menor. És obligatori introduir el seu representant legal. Si no disposa de la dada no introdueixi data de naixement fins que disposi d''aquesta informació','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.asociarRepresentante.menorJusticiable','El justiciable es menor. Es obligatorio introducir su representante legal. Si no dispone del dato no introduzca fecha de nacimiento hasta que disponga de esa información#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.asociarRepresentante.menorJusticiable','El justiciable es menor. Es obligatorio introducir su representante legal. Si no dispone del dato no introduzca fecha de nacimiento hasta que disponga de esa información#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.representanteNoPuedeSerPropioJusticiable','El representante no puede ser el propio justiciable','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.representanteNoPuedeSerPropioJusticiable','El representant no pot ser el propi justiciable','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.representanteNoPuedeSerPropioJusticiable','El representante no puede ser el propio justiciable#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.representanteNoPuedeSerPropioJusticiable','El representante no puede ser el propio justiciable#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.necesarioCorreoElectronico.recibirNotificaciones','Es necesario tener un correo electronico para poder recibir notificaciones','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.necesarioCorreoElectronico.recibirNotificaciones','Cal tenir un correu electrònic per poder rebre notificacions','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.necesarioCorreoElectronico.recibirNotificaciones','Es necesario tener un correo electronico para poder recibir notificaciones#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.necesarioCorreoElectronico.recibirNotificaciones','Es necesario tener un correo electronico para poder recibir notificaciones#GL','0','4',sysdate,'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.noExisteNifSistema','No esta registrado ese NIF en el sistema','0','1',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.noExisteNifSistema','No està registrat aquest NIF en el sistema','0','2',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.noExisteNifSistema','No esta registrado ese NIF en el sistema#EU','0','3',sysdate,'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('justiciaGratuita.justiciables.message.noExisteNifSistema','No esta registrado ese NIF en el sistema#GL','0','4',sysdate,'0','19');

commit;
prompt .
select to_char(sysdate, 'hh24:mi:ss') as "Fin" from dual;
spool off