package org.itcgae.siga.db.entities;

import java.util.Date;

public class AdmGestorinterfaz {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_GESTORINTERFAZ.ADM_GESTORINTERFAZ_ID
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Long admGestorinterfazId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_GESTORINTERFAZ.COLOR
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String color;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_GESTORINTERFAZ.TIPOLETRA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String tipoletra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_GESTORINTERFAZ.LOGO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String logo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_GESTORINTERFAZ.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Date fechamodificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_GESTORINTERFAZ.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Integer usumodificacion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.ADM_GESTORINTERFAZ_ID
	 * @return  the value of USCGAE_DESA.ADM_GESTORINTERFAZ.ADM_GESTORINTERFAZ_ID
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Long getAdmGestorinterfazId() {
		return admGestorinterfazId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.ADM_GESTORINTERFAZ_ID
	 * @param admGestorinterfazId  the value for USCGAE_DESA.ADM_GESTORINTERFAZ.ADM_GESTORINTERFAZ_ID
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setAdmGestorinterfazId(Long admGestorinterfazId) {
		this.admGestorinterfazId = admGestorinterfazId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.COLOR
	 * @return  the value of USCGAE_DESA.ADM_GESTORINTERFAZ.COLOR
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getColor() {
		return color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.COLOR
	 * @param color  the value for USCGAE_DESA.ADM_GESTORINTERFAZ.COLOR
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setColor(String color) {
		this.color = color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.TIPOLETRA
	 * @return  the value of USCGAE_DESA.ADM_GESTORINTERFAZ.TIPOLETRA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getTipoletra() {
		return tipoletra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.TIPOLETRA
	 * @param tipoletra  the value for USCGAE_DESA.ADM_GESTORINTERFAZ.TIPOLETRA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setTipoletra(String tipoletra) {
		this.tipoletra = tipoletra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.LOGO
	 * @return  the value of USCGAE_DESA.ADM_GESTORINTERFAZ.LOGO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getLogo() {
		return logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.LOGO
	 * @param logo  the value for USCGAE_DESA.ADM_GESTORINTERFAZ.LOGO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setLogo(String logo) {
		this.logo = logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.FECHAMODIFICACION
	 * @return  the value of USCGAE_DESA.ADM_GESTORINTERFAZ.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.FECHAMODIFICACION
	 * @param fechamodificacion  the value for USCGAE_DESA.ADM_GESTORINTERFAZ.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.USUMODIFICACION
	 * @return  the value of USCGAE_DESA.ADM_GESTORINTERFAZ.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Integer getUsumodificacion() {
		return usumodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_GESTORINTERFAZ.USUMODIFICACION
	 * @param usumodificacion  the value for USCGAE_DESA.ADM_GESTORINTERFAZ.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setUsumodificacion(Integer usumodificacion) {
		this.usumodificacion = usumodificacion;
	}
}