package org.itcgae.siga.db.entities;

public class AdmModoContador {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_MODO_CONTADOR.IDMODO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Short idmodo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_MODO_CONTADOR.NOMBRE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_MODO_CONTADOR.DESCRIPCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String descripcion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_MODO_CONTADOR.IDMODO
	 * @return  the value of USCGAE_DESA.ADM_MODO_CONTADOR.IDMODO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Short getIdmodo() {
		return idmodo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_MODO_CONTADOR.IDMODO
	 * @param idmodo  the value for USCGAE_DESA.ADM_MODO_CONTADOR.IDMODO
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setIdmodo(Short idmodo) {
		this.idmodo = idmodo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_MODO_CONTADOR.NOMBRE
	 * @return  the value of USCGAE_DESA.ADM_MODO_CONTADOR.NOMBRE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_MODO_CONTADOR.NOMBRE
	 * @param nombre  the value for USCGAE_DESA.ADM_MODO_CONTADOR.NOMBRE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_MODO_CONTADOR.DESCRIPCION
	 * @return  the value of USCGAE_DESA.ADM_MODO_CONTADOR.DESCRIPCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_MODO_CONTADOR.DESCRIPCION
	 * @param descripcion  the value for USCGAE_DESA.ADM_MODO_CONTADOR.DESCRIPCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}