package org.itcgae.siga.db.entities;

public class AdmPerfilRolKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_PERFIL_ROL.IDINSTITUCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Short idinstitucion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_PERFIL_ROL.IDROL
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String idrol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.ADM_PERFIL_ROL.IDPERFIL
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String idperfil;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_PERFIL_ROL.IDINSTITUCION
	 * @return  the value of USCGAE_DESA.ADM_PERFIL_ROL.IDINSTITUCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Short getIdinstitucion() {
		return idinstitucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_PERFIL_ROL.IDINSTITUCION
	 * @param idinstitucion  the value for USCGAE_DESA.ADM_PERFIL_ROL.IDINSTITUCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setIdinstitucion(Short idinstitucion) {
		this.idinstitucion = idinstitucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_PERFIL_ROL.IDROL
	 * @return  the value of USCGAE_DESA.ADM_PERFIL_ROL.IDROL
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getIdrol() {
		return idrol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_PERFIL_ROL.IDROL
	 * @param idrol  the value for USCGAE_DESA.ADM_PERFIL_ROL.IDROL
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setIdrol(String idrol) {
		this.idrol = idrol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.ADM_PERFIL_ROL.IDPERFIL
	 * @return  the value of USCGAE_DESA.ADM_PERFIL_ROL.IDPERFIL
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getIdperfil() {
		return idperfil;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.ADM_PERFIL_ROL.IDPERFIL
	 * @param idperfil  the value for USCGAE_DESA.ADM_PERFIL_ROL.IDPERFIL
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setIdperfil(String idperfil) {
		this.idperfil = idperfil;
	}
}