package org.itcgae.siga.db.entities;

import java.util.Date;

public class AgeTipocuando {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE.AGE_TIPOCUANDO.IDTIPOCUANDO
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	private Long idtipocuando;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE.AGE_TIPOCUANDO.DESCRIPCION
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	private String descripcion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE.AGE_TIPOCUANDO.USUMODIFICACION
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	private Long usumodificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE.AGE_TIPOCUANDO.FECHAMODIFICACION
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	private Date fechamodificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE.AGE_TIPOCUANDO.FECHABAJA
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	private Date fechabaja;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE.AGE_TIPOCUANDO.IDTIPOCUANDO
	 * @return  the value of USCGAE.AGE_TIPOCUANDO.IDTIPOCUANDO
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	public Long getIdtipocuando() {
		return idtipocuando;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE.AGE_TIPOCUANDO.IDTIPOCUANDO
	 * @param idtipocuando  the value for USCGAE.AGE_TIPOCUANDO.IDTIPOCUANDO
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	public void setIdtipocuando(Long idtipocuando) {
		this.idtipocuando = idtipocuando;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE.AGE_TIPOCUANDO.DESCRIPCION
	 * @return  the value of USCGAE.AGE_TIPOCUANDO.DESCRIPCION
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE.AGE_TIPOCUANDO.DESCRIPCION
	 * @param descripcion  the value for USCGAE.AGE_TIPOCUANDO.DESCRIPCION
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE.AGE_TIPOCUANDO.USUMODIFICACION
	 * @return  the value of USCGAE.AGE_TIPOCUANDO.USUMODIFICACION
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	public Long getUsumodificacion() {
		return usumodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE.AGE_TIPOCUANDO.USUMODIFICACION
	 * @param usumodificacion  the value for USCGAE.AGE_TIPOCUANDO.USUMODIFICACION
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	public void setUsumodificacion(Long usumodificacion) {
		this.usumodificacion = usumodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE.AGE_TIPOCUANDO.FECHAMODIFICACION
	 * @return  the value of USCGAE.AGE_TIPOCUANDO.FECHAMODIFICACION
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE.AGE_TIPOCUANDO.FECHAMODIFICACION
	 * @param fechamodificacion  the value for USCGAE.AGE_TIPOCUANDO.FECHAMODIFICACION
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE.AGE_TIPOCUANDO.FECHABAJA
	 * @return  the value of USCGAE.AGE_TIPOCUANDO.FECHABAJA
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	public Date getFechabaja() {
		return fechabaja;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE.AGE_TIPOCUANDO.FECHABAJA
	 * @param fechabaja  the value for USCGAE.AGE_TIPOCUANDO.FECHABAJA
	 * @mbg.generated  Mon Oct 22 08:52:58 CEST 2018
	 */
	public void setFechabaja(Date fechabaja) {
		this.fechabaja = fechabaja;
	}
}