package org.itcgae.siga.db.entities;

public class CajgProcedimientoremesaresol {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDPROCRESOLUCION
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    private Short idprocresolucion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDINSTITUCION
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    private Short idinstitucion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.CONSULTA
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    private String consulta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.CABECERA
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    private Short cabecera;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.DELIMITADOR
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    private String delimitador;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDTIPOREMESA
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    private Short idtiporemesa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDPROCRESOLUCION
     *
     * @return the value of USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDPROCRESOLUCION
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public Short getIdprocresolucion() {
        return idprocresolucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDPROCRESOLUCION
     *
     * @param idprocresolucion the value for USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDPROCRESOLUCION
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public void setIdprocresolucion(Short idprocresolucion) {
        this.idprocresolucion = idprocresolucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDINSTITUCION
     *
     * @return the value of USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDINSTITUCION
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public Short getIdinstitucion() {
        return idinstitucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDINSTITUCION
     *
     * @param idinstitucion the value for USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDINSTITUCION
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public void setIdinstitucion(Short idinstitucion) {
        this.idinstitucion = idinstitucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.CONSULTA
     *
     * @return the value of USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.CONSULTA
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public String getConsulta() {
        return consulta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.CONSULTA
     *
     * @param consulta the value for USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.CONSULTA
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public void setConsulta(String consulta) {
        this.consulta = consulta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.CABECERA
     *
     * @return the value of USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.CABECERA
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public Short getCabecera() {
        return cabecera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.CABECERA
     *
     * @param cabecera the value for USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.CABECERA
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public void setCabecera(Short cabecera) {
        this.cabecera = cabecera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.DELIMITADOR
     *
     * @return the value of USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.DELIMITADOR
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public String getDelimitador() {
        return delimitador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.DELIMITADOR
     *
     * @param delimitador the value for USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.DELIMITADOR
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public void setDelimitador(String delimitador) {
        this.delimitador = delimitador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDTIPOREMESA
     *
     * @return the value of USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDTIPOREMESA
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public Short getIdtiporemesa() {
        return idtiporemesa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDTIPOREMESA
     *
     * @param idtiporemesa the value for USCGAE.CAJG_PROCEDIMIENTOREMESARESOL.IDTIPOREMESA
     *
     * @mbg.generated Thu Oct 07 13:18:08 CEST 2021
     */
    public void setIdtiporemesa(Short idtiporemesa) {
        this.idtiporemesa = idtiporemesa;
    }
}