package org.itcgae.siga.db.entities;

import java.util.Date;

public class CenAccesodatos {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_ACCESODATOS.CARACTER
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String caracter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_ACCESODATOS.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Date fechamodificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_ACCESODATOS.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Integer usumodificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_ACCESODATOS.DESCRIPCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String descripcion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_ACCESODATOS.CARACTER
	 * @return  the value of USCGAE_DESA.CEN_ACCESODATOS.CARACTER
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getCaracter() {
		return caracter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_ACCESODATOS.CARACTER
	 * @param caracter  the value for USCGAE_DESA.CEN_ACCESODATOS.CARACTER
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setCaracter(String caracter) {
		this.caracter = caracter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_ACCESODATOS.FECHAMODIFICACION
	 * @return  the value of USCGAE_DESA.CEN_ACCESODATOS.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_ACCESODATOS.FECHAMODIFICACION
	 * @param fechamodificacion  the value for USCGAE_DESA.CEN_ACCESODATOS.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_ACCESODATOS.USUMODIFICACION
	 * @return  the value of USCGAE_DESA.CEN_ACCESODATOS.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Integer getUsumodificacion() {
		return usumodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_ACCESODATOS.USUMODIFICACION
	 * @param usumodificacion  the value for USCGAE_DESA.CEN_ACCESODATOS.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setUsumodificacion(Integer usumodificacion) {
		this.usumodificacion = usumodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_ACCESODATOS.DESCRIPCION
	 * @return  the value of USCGAE_DESA.CEN_ACCESODATOS.DESCRIPCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_ACCESODATOS.DESCRIPCION
	 * @param descripcion  the value for USCGAE_DESA.CEN_ACCESODATOS.DESCRIPCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}