package org.itcgae.siga.db.entities;

import java.util.Date;

public class CenContacto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_CONTACTO.FECHA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Integer fecha;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_CONTACTO.DESCRIPCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Integer descripcion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_CONTACTO.CEN_INSTITUCION_ID
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Long cenInstitucionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_CONTACTO.CEN_CLIENTE_CEN_INSTITUCION_ID
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Short cenClienteCenInstitucionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_CONTACTO.COL_3
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Long col3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_CONTACTO.IDPERSONA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Long idpersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_CONTACTO.CEN_CLIENTE_IDPERSONA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Long cenClienteIdpersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_CONTACTO.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Date fechamodificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_CONTACTO.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Integer usumodificacion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_CONTACTO.FECHA
	 * @return  the value of USCGAE_DESA.CEN_CONTACTO.FECHA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Integer getFecha() {
		return fecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_CONTACTO.FECHA
	 * @param fecha  the value for USCGAE_DESA.CEN_CONTACTO.FECHA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setFecha(Integer fecha) {
		this.fecha = fecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_CONTACTO.DESCRIPCION
	 * @return  the value of USCGAE_DESA.CEN_CONTACTO.DESCRIPCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Integer getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_CONTACTO.DESCRIPCION
	 * @param descripcion  the value for USCGAE_DESA.CEN_CONTACTO.DESCRIPCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setDescripcion(Integer descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_CONTACTO.CEN_INSTITUCION_ID
	 * @return  the value of USCGAE_DESA.CEN_CONTACTO.CEN_INSTITUCION_ID
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Long getCenInstitucionId() {
		return cenInstitucionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_CONTACTO.CEN_INSTITUCION_ID
	 * @param cenInstitucionId  the value for USCGAE_DESA.CEN_CONTACTO.CEN_INSTITUCION_ID
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setCenInstitucionId(Long cenInstitucionId) {
		this.cenInstitucionId = cenInstitucionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_CONTACTO.CEN_CLIENTE_CEN_INSTITUCION_ID
	 * @return  the value of USCGAE_DESA.CEN_CONTACTO.CEN_CLIENTE_CEN_INSTITUCION_ID
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Short getCenClienteCenInstitucionId() {
		return cenClienteCenInstitucionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_CONTACTO.CEN_CLIENTE_CEN_INSTITUCION_ID
	 * @param cenClienteCenInstitucionId  the value for USCGAE_DESA.CEN_CONTACTO.CEN_CLIENTE_CEN_INSTITUCION_ID
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setCenClienteCenInstitucionId(Short cenClienteCenInstitucionId) {
		this.cenClienteCenInstitucionId = cenClienteCenInstitucionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_CONTACTO.COL_3
	 * @return  the value of USCGAE_DESA.CEN_CONTACTO.COL_3
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Long getCol3() {
		return col3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_CONTACTO.COL_3
	 * @param col3  the value for USCGAE_DESA.CEN_CONTACTO.COL_3
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setCol3(Long col3) {
		this.col3 = col3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_CONTACTO.IDPERSONA
	 * @return  the value of USCGAE_DESA.CEN_CONTACTO.IDPERSONA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Long getIdpersona() {
		return idpersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_CONTACTO.IDPERSONA
	 * @param idpersona  the value for USCGAE_DESA.CEN_CONTACTO.IDPERSONA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setIdpersona(Long idpersona) {
		this.idpersona = idpersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_CONTACTO.CEN_CLIENTE_IDPERSONA
	 * @return  the value of USCGAE_DESA.CEN_CONTACTO.CEN_CLIENTE_IDPERSONA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Long getCenClienteIdpersona() {
		return cenClienteIdpersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_CONTACTO.CEN_CLIENTE_IDPERSONA
	 * @param cenClienteIdpersona  the value for USCGAE_DESA.CEN_CONTACTO.CEN_CLIENTE_IDPERSONA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setCenClienteIdpersona(Long cenClienteIdpersona) {
		this.cenClienteIdpersona = cenClienteIdpersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_CONTACTO.FECHAMODIFICACION
	 * @return  the value of USCGAE_DESA.CEN_CONTACTO.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_CONTACTO.FECHAMODIFICACION
	 * @param fechamodificacion  the value for USCGAE_DESA.CEN_CONTACTO.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_CONTACTO.USUMODIFICACION
	 * @return  the value of USCGAE_DESA.CEN_CONTACTO.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Integer getUsumodificacion() {
		return usumodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_CONTACTO.USUMODIFICACION
	 * @param usumodificacion  the value for USCGAE_DESA.CEN_CONTACTO.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setUsumodificacion(Integer usumodificacion) {
		this.usumodificacion = usumodificacion;
	}
}