package org.itcgae.siga.db.entities;

public class CenDocumentacionpresentadaKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDSOLICITUD
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	private Long idsolicitud;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDDOCUMENTACION
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	private Short iddocumentacion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDSOLICITUD
	 * @return  the value of USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDSOLICITUD
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public Long getIdsolicitud() {
		return idsolicitud;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDSOLICITUD
	 * @param idsolicitud  the value for USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDSOLICITUD
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public void setIdsolicitud(Long idsolicitud) {
		this.idsolicitud = idsolicitud;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDDOCUMENTACION
	 * @return  the value of USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDDOCUMENTACION
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public Short getIddocumentacion() {
		return iddocumentacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDDOCUMENTACION
	 * @param iddocumentacion  the value for USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDDOCUMENTACION
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public void setIddocumentacion(Short iddocumentacion) {
		this.iddocumentacion = iddocumentacion;
	}
}