package org.itcgae.siga.db.entities;

import java.util.Date;

public class CenDocumentacionpresentada extends CenDocumentacionpresentadaKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.FECHAMODIFICACION
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	private Date fechamodificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.USUMODIFICACION
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	private Integer usumodificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDFICHERO
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	private Long idfichero;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.NOMBREFICHERO
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	private String nombrefichero;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.FECHAMODIFICACION
	 * @return  the value of USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.FECHAMODIFICACION
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.FECHAMODIFICACION
	 * @param fechamodificacion  the value for USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.FECHAMODIFICACION
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.USUMODIFICACION
	 * @return  the value of USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.USUMODIFICACION
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public Integer getUsumodificacion() {
		return usumodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.USUMODIFICACION
	 * @param usumodificacion  the value for USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.USUMODIFICACION
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public void setUsumodificacion(Integer usumodificacion) {
		this.usumodificacion = usumodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDFICHERO
	 * @return  the value of USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDFICHERO
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public Long getIdfichero() {
		return idfichero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDFICHERO
	 * @param idfichero  the value for USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.IDFICHERO
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public void setIdfichero(Long idfichero) {
		this.idfichero = idfichero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.NOMBREFICHERO
	 * @return  the value of USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.NOMBREFICHERO
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public String getNombrefichero() {
		return nombrefichero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.NOMBREFICHERO
	 * @param nombrefichero  the value for USCGAE_INT.CEN_DOCUMENTACIONPRESENTADA.NOMBREFICHERO
	 * @mbg.generated  Tue Jan 11 10:51:45 CET 2022
	 */
	public void setNombrefichero(String nombrefichero) {
		this.nombrefichero = nombrefichero;
	}
}