package org.itcgae.siga.db.entities;

import java.util.Date;

public class CenInstitucion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.IDINSTITUCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Short idinstitucion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.NOMBRE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.BBDDCPD
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String bbddcpd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.IDLENGUAJE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String idlenguaje;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Date fechamodificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Integer usumodificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.IDPERSONA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Long idpersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.CUENTACONTABLECAJA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String cuentacontablecaja;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.CEN_INST_IDINSTITUCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Short cenInstIdinstitucion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.ABREVIATURA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String abreviatura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.FECHAENPRODUCCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private Date fechaenproduccion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.CODIGOEXT
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String codigoext;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE_DESA.CEN_INSTITUCION.IDCOMISION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	private String idcomision;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.IDINSTITUCION
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.IDINSTITUCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Short getIdinstitucion() {
		return idinstitucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.IDINSTITUCION
	 * @param idinstitucion  the value for USCGAE_DESA.CEN_INSTITUCION.IDINSTITUCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setIdinstitucion(Short idinstitucion) {
		this.idinstitucion = idinstitucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.NOMBRE
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.NOMBRE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.NOMBRE
	 * @param nombre  the value for USCGAE_DESA.CEN_INSTITUCION.NOMBRE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.BBDDCPD
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.BBDDCPD
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getBbddcpd() {
		return bbddcpd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.BBDDCPD
	 * @param bbddcpd  the value for USCGAE_DESA.CEN_INSTITUCION.BBDDCPD
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setBbddcpd(String bbddcpd) {
		this.bbddcpd = bbddcpd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.IDLENGUAJE
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.IDLENGUAJE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getIdlenguaje() {
		return idlenguaje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.IDLENGUAJE
	 * @param idlenguaje  the value for USCGAE_DESA.CEN_INSTITUCION.IDLENGUAJE
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setIdlenguaje(String idlenguaje) {
		this.idlenguaje = idlenguaje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.FECHAMODIFICACION
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.FECHAMODIFICACION
	 * @param fechamodificacion  the value for USCGAE_DESA.CEN_INSTITUCION.FECHAMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.USUMODIFICACION
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Integer getUsumodificacion() {
		return usumodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.USUMODIFICACION
	 * @param usumodificacion  the value for USCGAE_DESA.CEN_INSTITUCION.USUMODIFICACION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setUsumodificacion(Integer usumodificacion) {
		this.usumodificacion = usumodificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.IDPERSONA
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.IDPERSONA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Long getIdpersona() {
		return idpersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.IDPERSONA
	 * @param idpersona  the value for USCGAE_DESA.CEN_INSTITUCION.IDPERSONA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setIdpersona(Long idpersona) {
		this.idpersona = idpersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.CUENTACONTABLECAJA
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.CUENTACONTABLECAJA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getCuentacontablecaja() {
		return cuentacontablecaja;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.CUENTACONTABLECAJA
	 * @param cuentacontablecaja  the value for USCGAE_DESA.CEN_INSTITUCION.CUENTACONTABLECAJA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setCuentacontablecaja(String cuentacontablecaja) {
		this.cuentacontablecaja = cuentacontablecaja;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.CEN_INST_IDINSTITUCION
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.CEN_INST_IDINSTITUCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Short getCenInstIdinstitucion() {
		return cenInstIdinstitucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.CEN_INST_IDINSTITUCION
	 * @param cenInstIdinstitucion  the value for USCGAE_DESA.CEN_INSTITUCION.CEN_INST_IDINSTITUCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setCenInstIdinstitucion(Short cenInstIdinstitucion) {
		this.cenInstIdinstitucion = cenInstIdinstitucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.ABREVIATURA
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.ABREVIATURA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getAbreviatura() {
		return abreviatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.ABREVIATURA
	 * @param abreviatura  the value for USCGAE_DESA.CEN_INSTITUCION.ABREVIATURA
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.FECHAENPRODUCCION
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.FECHAENPRODUCCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Date getFechaenproduccion() {
		return fechaenproduccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.FECHAENPRODUCCION
	 * @param fechaenproduccion  the value for USCGAE_DESA.CEN_INSTITUCION.FECHAENPRODUCCION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setFechaenproduccion(Date fechaenproduccion) {
		this.fechaenproduccion = fechaenproduccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.CODIGOEXT
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.CODIGOEXT
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getCodigoext() {
		return codigoext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.CODIGOEXT
	 * @param codigoext  the value for USCGAE_DESA.CEN_INSTITUCION.CODIGOEXT
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setCodigoext(String codigoext) {
		this.codigoext = codigoext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE_DESA.CEN_INSTITUCION.IDCOMISION
	 * @return  the value of USCGAE_DESA.CEN_INSTITUCION.IDCOMISION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getIdcomision() {
		return idcomision;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE_DESA.CEN_INSTITUCION.IDCOMISION
	 * @param idcomision  the value for USCGAE_DESA.CEN_INSTITUCION.IDCOMISION
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setIdcomision(String idcomision) {
		this.idcomision = idcomision;
	}
}