package org.itcgae.siga.db.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CenSucursalesExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public CenSucursalesExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBancosCodigoIsNull() {
			addCriterion("BANCOS_CODIGO is null");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoIsNotNull() {
			addCriterion("BANCOS_CODIGO is not null");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoEqualTo(String value) {
			addCriterion("BANCOS_CODIGO =", value, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoNotEqualTo(String value) {
			addCriterion("BANCOS_CODIGO <>", value, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoGreaterThan(String value) {
			addCriterion("BANCOS_CODIGO >", value, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoGreaterThanOrEqualTo(String value) {
			addCriterion("BANCOS_CODIGO >=", value, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoLessThan(String value) {
			addCriterion("BANCOS_CODIGO <", value, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoLessThanOrEqualTo(String value) {
			addCriterion("BANCOS_CODIGO <=", value, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoLike(String value) {
			addCriterion("BANCOS_CODIGO like", value, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoNotLike(String value) {
			addCriterion("BANCOS_CODIGO not like", value, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoIn(List<String> values) {
			addCriterion("BANCOS_CODIGO in", values, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoNotIn(List<String> values) {
			addCriterion("BANCOS_CODIGO not in", values, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoBetween(String value1, String value2) {
			addCriterion("BANCOS_CODIGO between", value1, value2, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andBancosCodigoNotBetween(String value1, String value2) {
			addCriterion("BANCOS_CODIGO not between", value1, value2, "bancosCodigo");
			return (Criteria) this;
		}

		public Criteria andCodSucursalIsNull() {
			addCriterion("COD_SUCURSAL is null");
			return (Criteria) this;
		}

		public Criteria andCodSucursalIsNotNull() {
			addCriterion("COD_SUCURSAL is not null");
			return (Criteria) this;
		}

		public Criteria andCodSucursalEqualTo(String value) {
			addCriterion("COD_SUCURSAL =", value, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalNotEqualTo(String value) {
			addCriterion("COD_SUCURSAL <>", value, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalGreaterThan(String value) {
			addCriterion("COD_SUCURSAL >", value, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalGreaterThanOrEqualTo(String value) {
			addCriterion("COD_SUCURSAL >=", value, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalLessThan(String value) {
			addCriterion("COD_SUCURSAL <", value, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalLessThanOrEqualTo(String value) {
			addCriterion("COD_SUCURSAL <=", value, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalLike(String value) {
			addCriterion("COD_SUCURSAL like", value, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalNotLike(String value) {
			addCriterion("COD_SUCURSAL not like", value, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalIn(List<String> values) {
			addCriterion("COD_SUCURSAL in", values, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalNotIn(List<String> values) {
			addCriterion("COD_SUCURSAL not in", values, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalBetween(String value1, String value2) {
			addCriterion("COD_SUCURSAL between", value1, value2, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andCodSucursalNotBetween(String value1, String value2) {
			addCriterion("COD_SUCURSAL not between", value1, value2, "codSucursal");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("NOMBRE is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("NOMBRE is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("NOMBRE =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("NOMBRE <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("NOMBRE >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("NOMBRE <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("NOMBRE like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("NOMBRE not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("NOMBRE in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("NOMBRE not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("NOMBRE between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("NOMBRE not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andDomicilioIsNull() {
			addCriterion("DOMICILIO is null");
			return (Criteria) this;
		}

		public Criteria andDomicilioIsNotNull() {
			addCriterion("DOMICILIO is not null");
			return (Criteria) this;
		}

		public Criteria andDomicilioEqualTo(String value) {
			addCriterion("DOMICILIO =", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotEqualTo(String value) {
			addCriterion("DOMICILIO <>", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioGreaterThan(String value) {
			addCriterion("DOMICILIO >", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioGreaterThanOrEqualTo(String value) {
			addCriterion("DOMICILIO >=", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioLessThan(String value) {
			addCriterion("DOMICILIO <", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioLessThanOrEqualTo(String value) {
			addCriterion("DOMICILIO <=", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioLike(String value) {
			addCriterion("DOMICILIO like", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotLike(String value) {
			addCriterion("DOMICILIO not like", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioIn(List<String> values) {
			addCriterion("DOMICILIO in", values, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotIn(List<String> values) {
			addCriterion("DOMICILIO not in", values, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioBetween(String value1, String value2) {
			addCriterion("DOMICILIO between", value1, value2, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotBetween(String value1, String value2) {
			addCriterion("DOMICILIO not between", value1, value2, "domicilio");
			return (Criteria) this;
		}

		public Criteria andCodigopostalIsNull() {
			addCriterion("CODIGOPOSTAL is null");
			return (Criteria) this;
		}

		public Criteria andCodigopostalIsNotNull() {
			addCriterion("CODIGOPOSTAL is not null");
			return (Criteria) this;
		}

		public Criteria andCodigopostalEqualTo(String value) {
			addCriterion("CODIGOPOSTAL =", value, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalNotEqualTo(String value) {
			addCriterion("CODIGOPOSTAL <>", value, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalGreaterThan(String value) {
			addCriterion("CODIGOPOSTAL >", value, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalGreaterThanOrEqualTo(String value) {
			addCriterion("CODIGOPOSTAL >=", value, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalLessThan(String value) {
			addCriterion("CODIGOPOSTAL <", value, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalLessThanOrEqualTo(String value) {
			addCriterion("CODIGOPOSTAL <=", value, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalLike(String value) {
			addCriterion("CODIGOPOSTAL like", value, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalNotLike(String value) {
			addCriterion("CODIGOPOSTAL not like", value, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalIn(List<String> values) {
			addCriterion("CODIGOPOSTAL in", values, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalNotIn(List<String> values) {
			addCriterion("CODIGOPOSTAL not in", values, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalBetween(String value1, String value2) {
			addCriterion("CODIGOPOSTAL between", value1, value2, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodigopostalNotBetween(String value1, String value2) {
			addCriterion("CODIGOPOSTAL not between", value1, value2, "codigopostal");
			return (Criteria) this;
		}

		public Criteria andCodPlazaIsNull() {
			addCriterion("COD_PLAZA is null");
			return (Criteria) this;
		}

		public Criteria andCodPlazaIsNotNull() {
			addCriterion("COD_PLAZA is not null");
			return (Criteria) this;
		}

		public Criteria andCodPlazaEqualTo(String value) {
			addCriterion("COD_PLAZA =", value, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaNotEqualTo(String value) {
			addCriterion("COD_PLAZA <>", value, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaGreaterThan(String value) {
			addCriterion("COD_PLAZA >", value, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaGreaterThanOrEqualTo(String value) {
			addCriterion("COD_PLAZA >=", value, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaLessThan(String value) {
			addCriterion("COD_PLAZA <", value, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaLessThanOrEqualTo(String value) {
			addCriterion("COD_PLAZA <=", value, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaLike(String value) {
			addCriterion("COD_PLAZA like", value, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaNotLike(String value) {
			addCriterion("COD_PLAZA not like", value, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaIn(List<String> values) {
			addCriterion("COD_PLAZA in", values, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaNotIn(List<String> values) {
			addCriterion("COD_PLAZA not in", values, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaBetween(String value1, String value2) {
			addCriterion("COD_PLAZA between", value1, value2, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andCodPlazaNotBetween(String value1, String value2) {
			addCriterion("COD_PLAZA not between", value1, value2, "codPlaza");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionIsNull() {
			addCriterion("FECHAMODIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionIsNotNull() {
			addCriterion("FECHAMODIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionEqualTo(Date value) {
			addCriterion("FECHAMODIFICACION =", value, "fechamodificacion");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionNotEqualTo(Date value) {
			addCriterion("FECHAMODIFICACION <>", value, "fechamodificacion");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionGreaterThan(Date value) {
			addCriterion("FECHAMODIFICACION >", value, "fechamodificacion");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionGreaterThanOrEqualTo(Date value) {
			addCriterion("FECHAMODIFICACION >=", value, "fechamodificacion");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionLessThan(Date value) {
			addCriterion("FECHAMODIFICACION <", value, "fechamodificacion");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionLessThanOrEqualTo(Date value) {
			addCriterion("FECHAMODIFICACION <=", value, "fechamodificacion");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionIn(List<Date> values) {
			addCriterion("FECHAMODIFICACION in", values, "fechamodificacion");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionNotIn(List<Date> values) {
			addCriterion("FECHAMODIFICACION not in", values, "fechamodificacion");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionBetween(Date value1, Date value2) {
			addCriterion("FECHAMODIFICACION between", value1, value2, "fechamodificacion");
			return (Criteria) this;
		}

		public Criteria andFechamodificacionNotBetween(Date value1, Date value2) {
			addCriterion("FECHAMODIFICACION not between", value1, value2, "fechamodificacion");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionIsNull() {
			addCriterion("USUMODIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionIsNotNull() {
			addCriterion("USUMODIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionEqualTo(Integer value) {
			addCriterion("USUMODIFICACION =", value, "usumodificacion");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionNotEqualTo(Integer value) {
			addCriterion("USUMODIFICACION <>", value, "usumodificacion");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionGreaterThan(Integer value) {
			addCriterion("USUMODIFICACION >", value, "usumodificacion");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionGreaterThanOrEqualTo(Integer value) {
			addCriterion("USUMODIFICACION >=", value, "usumodificacion");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionLessThan(Integer value) {
			addCriterion("USUMODIFICACION <", value, "usumodificacion");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionLessThanOrEqualTo(Integer value) {
			addCriterion("USUMODIFICACION <=", value, "usumodificacion");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionIn(List<Integer> values) {
			addCriterion("USUMODIFICACION in", values, "usumodificacion");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionNotIn(List<Integer> values) {
			addCriterion("USUMODIFICACION not in", values, "usumodificacion");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionBetween(Integer value1, Integer value2) {
			addCriterion("USUMODIFICACION between", value1, value2, "usumodificacion");
			return (Criteria) this;
		}

		public Criteria andUsumodificacionNotBetween(Integer value1, Integer value2) {
			addCriterion("USUMODIFICACION not between", value1, value2, "usumodificacion");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
	 * @mbg.generated  Wed Mar 14 18:23:45 CET 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USCGAE_DESA.CEN_SUCURSALES
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 07 17:49:31 CET 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}