package org.itcgae.siga.db.entities;

import java.util.Date;

public class EcomGuardiacolegiado {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDECOMGUARDIACOLEGIADO
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private Integer idecomguardiacolegiado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDINSTITUCION
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private Short idinstitucion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private Integer idguardia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.FECHAGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private Date fechaguardia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.NOMBREGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private String nombreguardia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.ORDENGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private Short ordenguardia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.NUMEROCOLEGIADO
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private String numerocolegiado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.NOMBRECOLEGIADO
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private String nombrecolegiado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONO1
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private String telefono1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONO2
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private String telefono2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONOMOVIL
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private String telefonomovil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.EMAIL
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.ACCION
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private Short accion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDECOMCOLA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    private Long idecomcola;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDECOMGUARDIACOLEGIADO
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDECOMGUARDIACOLEGIADO
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public Integer getIdecomguardiacolegiado() {
        return idecomguardiacolegiado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDECOMGUARDIACOLEGIADO
     *
     * @param idecomguardiacolegiado the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDECOMGUARDIACOLEGIADO
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setIdecomguardiacolegiado(Integer idecomguardiacolegiado) {
        this.idecomguardiacolegiado = idecomguardiacolegiado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDINSTITUCION
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDINSTITUCION
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public Short getIdinstitucion() {
        return idinstitucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDINSTITUCION
     *
     * @param idinstitucion the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDINSTITUCION
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setIdinstitucion(Short idinstitucion) {
        this.idinstitucion = idinstitucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDGUARDIA
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public Integer getIdguardia() {
        return idguardia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDGUARDIA
     *
     * @param idguardia the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setIdguardia(Integer idguardia) {
        this.idguardia = idguardia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.FECHAGUARDIA
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.FECHAGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public Date getFechaguardia() {
        return fechaguardia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.FECHAGUARDIA
     *
     * @param fechaguardia the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.FECHAGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setFechaguardia(Date fechaguardia) {
        this.fechaguardia = fechaguardia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.NOMBREGUARDIA
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.NOMBREGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public String getNombreguardia() {
        return nombreguardia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.NOMBREGUARDIA
     *
     * @param nombreguardia the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.NOMBREGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setNombreguardia(String nombreguardia) {
        this.nombreguardia = nombreguardia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.ORDENGUARDIA
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.ORDENGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public Short getOrdenguardia() {
        return ordenguardia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.ORDENGUARDIA
     *
     * @param ordenguardia the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.ORDENGUARDIA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setOrdenguardia(Short ordenguardia) {
        this.ordenguardia = ordenguardia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.NUMEROCOLEGIADO
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.NUMEROCOLEGIADO
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public String getNumerocolegiado() {
        return numerocolegiado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.NUMEROCOLEGIADO
     *
     * @param numerocolegiado the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.NUMEROCOLEGIADO
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setNumerocolegiado(String numerocolegiado) {
        this.numerocolegiado = numerocolegiado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.NOMBRECOLEGIADO
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.NOMBRECOLEGIADO
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public String getNombrecolegiado() {
        return nombrecolegiado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.NOMBRECOLEGIADO
     *
     * @param nombrecolegiado the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.NOMBRECOLEGIADO
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setNombrecolegiado(String nombrecolegiado) {
        this.nombrecolegiado = nombrecolegiado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONO1
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONO1
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public String getTelefono1() {
        return telefono1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONO1
     *
     * @param telefono1 the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONO1
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONO2
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONO2
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public String getTelefono2() {
        return telefono2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONO2
     *
     * @param telefono2 the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONO2
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONOMOVIL
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONOMOVIL
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public String getTelefonomovil() {
        return telefonomovil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONOMOVIL
     *
     * @param telefonomovil the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.TELEFONOMOVIL
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setTelefonomovil(String telefonomovil) {
        this.telefonomovil = telefonomovil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.EMAIL
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.EMAIL
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.EMAIL
     *
     * @param email the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.EMAIL
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.ACCION
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.ACCION
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public Short getAccion() {
        return accion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.ACCION
     *
     * @param accion the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.ACCION
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setAccion(Short accion) {
        this.accion = accion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDECOMCOLA
     *
     * @return the value of USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDECOMCOLA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public Long getIdecomcola() {
        return idecomcola;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDECOMCOLA
     *
     * @param idecomcola the value for USCGAE_INT.ECOM_GUARDIACOLEGIADO.IDECOMCOLA
     *
     * @mbg.generated Wed Sep 06 15:38:18 CEST 2023
     */
    public void setIdecomcola(Long idecomcola) {
        this.idecomcola = idecomcola;
    }
}