package org.itcgae.siga.db.entities;

public class FcsHistoricoHitofactKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE.FCS_HISTORICO_HITOFACT.IDINSTITUCION
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	private Short idinstitucion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE.FCS_HISTORICO_HITOFACT.IDFACTURACION
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	private Integer idfacturacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE.FCS_HISTORICO_HITOFACT.IDTURNO
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	private Integer idturno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE.FCS_HISTORICO_HITOFACT.IDGUARDIA
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	private Integer idguardia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USCGAE.FCS_HISTORICO_HITOFACT.IDHITO
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	private Long idhito;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE.FCS_HISTORICO_HITOFACT.IDINSTITUCION
	 * @return  the value of USCGAE.FCS_HISTORICO_HITOFACT.IDINSTITUCION
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	public Short getIdinstitucion() {
		return idinstitucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE.FCS_HISTORICO_HITOFACT.IDINSTITUCION
	 * @param idinstitucion  the value for USCGAE.FCS_HISTORICO_HITOFACT.IDINSTITUCION
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	public void setIdinstitucion(Short idinstitucion) {
		this.idinstitucion = idinstitucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE.FCS_HISTORICO_HITOFACT.IDFACTURACION
	 * @return  the value of USCGAE.FCS_HISTORICO_HITOFACT.IDFACTURACION
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	public Integer getIdfacturacion() {
		return idfacturacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE.FCS_HISTORICO_HITOFACT.IDFACTURACION
	 * @param idfacturacion  the value for USCGAE.FCS_HISTORICO_HITOFACT.IDFACTURACION
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	public void setIdfacturacion(Integer idfacturacion) {
		this.idfacturacion = idfacturacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE.FCS_HISTORICO_HITOFACT.IDTURNO
	 * @return  the value of USCGAE.FCS_HISTORICO_HITOFACT.IDTURNO
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	public Integer getIdturno() {
		return idturno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE.FCS_HISTORICO_HITOFACT.IDTURNO
	 * @param idturno  the value for USCGAE.FCS_HISTORICO_HITOFACT.IDTURNO
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	public void setIdturno(Integer idturno) {
		this.idturno = idturno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE.FCS_HISTORICO_HITOFACT.IDGUARDIA
	 * @return  the value of USCGAE.FCS_HISTORICO_HITOFACT.IDGUARDIA
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	public Integer getIdguardia() {
		return idguardia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE.FCS_HISTORICO_HITOFACT.IDGUARDIA
	 * @param idguardia  the value for USCGAE.FCS_HISTORICO_HITOFACT.IDGUARDIA
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	public void setIdguardia(Integer idguardia) {
		this.idguardia = idguardia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USCGAE.FCS_HISTORICO_HITOFACT.IDHITO
	 * @return  the value of USCGAE.FCS_HISTORICO_HITOFACT.IDHITO
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	public Long getIdhito() {
		return idhito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USCGAE.FCS_HISTORICO_HITOFACT.IDHITO
	 * @param idhito  the value for USCGAE.FCS_HISTORICO_HITOFACT.IDHITO
	 * @mbg.generated  Thu Dec 19 19:42:15 CET 2019
	 */
	public void setIdhito(Long idhito) {
		this.idhito = idhito;
	}
}