package org.itcgae.siga.db.entities;

import java.util.Date;

public class ForRoles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.FOR_ROLES.IDROL
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    private Short idrol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.FOR_ROLES.DESCRIPCION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.FOR_ROLES.USUMODIFICACION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    private Long usumodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.FOR_ROLES.FECHABAJA
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    private Date fechabaja;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.FOR_ROLES.FECHAMODIFICACION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    private Date fechamodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.FOR_ROLES.IDINSTITUCION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    private Short idinstitucion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.FOR_ROLES.IDROL
     *
     * @return the value of USCGAE.FOR_ROLES.IDROL
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public Short getIdrol() {
        return idrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.FOR_ROLES.IDROL
     *
     * @param idrol the value for USCGAE.FOR_ROLES.IDROL
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public void setIdrol(Short idrol) {
        this.idrol = idrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.FOR_ROLES.DESCRIPCION
     *
     * @return the value of USCGAE.FOR_ROLES.DESCRIPCION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.FOR_ROLES.DESCRIPCION
     *
     * @param descripcion the value for USCGAE.FOR_ROLES.DESCRIPCION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.FOR_ROLES.USUMODIFICACION
     *
     * @return the value of USCGAE.FOR_ROLES.USUMODIFICACION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public Long getUsumodificacion() {
        return usumodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.FOR_ROLES.USUMODIFICACION
     *
     * @param usumodificacion the value for USCGAE.FOR_ROLES.USUMODIFICACION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public void setUsumodificacion(Long usumodificacion) {
        this.usumodificacion = usumodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.FOR_ROLES.FECHABAJA
     *
     * @return the value of USCGAE.FOR_ROLES.FECHABAJA
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public Date getFechabaja() {
        return fechabaja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.FOR_ROLES.FECHABAJA
     *
     * @param fechabaja the value for USCGAE.FOR_ROLES.FECHABAJA
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.FOR_ROLES.FECHAMODIFICACION
     *
     * @return the value of USCGAE.FOR_ROLES.FECHAMODIFICACION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public Date getFechamodificacion() {
        return fechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.FOR_ROLES.FECHAMODIFICACION
     *
     * @param fechamodificacion the value for USCGAE.FOR_ROLES.FECHAMODIFICACION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public void setFechamodificacion(Date fechamodificacion) {
        this.fechamodificacion = fechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.FOR_ROLES.IDINSTITUCION
     *
     * @return the value of USCGAE.FOR_ROLES.IDINSTITUCION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public Short getIdinstitucion() {
        return idinstitucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.FOR_ROLES.IDINSTITUCION
     *
     * @param idinstitucion the value for USCGAE.FOR_ROLES.IDINSTITUCION
     *
     * @mbg.generated Mon Nov 05 12:56:59 CET 2018
     */
    public void setIdinstitucion(Short idinstitucion) {
        this.idinstitucion = idinstitucion;
    }
}