package org.itcgae.siga.db.entities;

import java.math.BigDecimal;
import java.util.Date;

public class PysAnticipoletrado extends PysAnticipoletradoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.PYS_ANTICIPOLETRADO.DESCRIPCION
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.PYS_ANTICIPOLETRADO.FECHA
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    private Date fecha;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.PYS_ANTICIPOLETRADO.IMPORTEINICIAL
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    private BigDecimal importeinicial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.PYS_ANTICIPOLETRADO.USUMODIFICACION
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    private Integer usumodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.PYS_ANTICIPOLETRADO.FECHAMODIFICACION
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    private Date fechamodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.PYS_ANTICIPOLETRADO.CTACONTABLE
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    private String ctacontable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.PYS_ANTICIPOLETRADO.CONTABILIZADO
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    private String contabilizado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.PYS_ANTICIPOLETRADO.DESCRIPCION
     *
     * @return the value of USCGAE.PYS_ANTICIPOLETRADO.DESCRIPCION
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.PYS_ANTICIPOLETRADO.DESCRIPCION
     *
     * @param descripcion the value for USCGAE.PYS_ANTICIPOLETRADO.DESCRIPCION
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.PYS_ANTICIPOLETRADO.FECHA
     *
     * @return the value of USCGAE.PYS_ANTICIPOLETRADO.FECHA
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.PYS_ANTICIPOLETRADO.FECHA
     *
     * @param fecha the value for USCGAE.PYS_ANTICIPOLETRADO.FECHA
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.PYS_ANTICIPOLETRADO.IMPORTEINICIAL
     *
     * @return the value of USCGAE.PYS_ANTICIPOLETRADO.IMPORTEINICIAL
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public BigDecimal getImporteinicial() {
        return importeinicial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.PYS_ANTICIPOLETRADO.IMPORTEINICIAL
     *
     * @param importeinicial the value for USCGAE.PYS_ANTICIPOLETRADO.IMPORTEINICIAL
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public void setImporteinicial(BigDecimal importeinicial) {
        this.importeinicial = importeinicial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.PYS_ANTICIPOLETRADO.USUMODIFICACION
     *
     * @return the value of USCGAE.PYS_ANTICIPOLETRADO.USUMODIFICACION
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public Integer getUsumodificacion() {
        return usumodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.PYS_ANTICIPOLETRADO.USUMODIFICACION
     *
     * @param usumodificacion the value for USCGAE.PYS_ANTICIPOLETRADO.USUMODIFICACION
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public void setUsumodificacion(Integer usumodificacion) {
        this.usumodificacion = usumodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.PYS_ANTICIPOLETRADO.FECHAMODIFICACION
     *
     * @return the value of USCGAE.PYS_ANTICIPOLETRADO.FECHAMODIFICACION
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public Date getFechamodificacion() {
        return fechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.PYS_ANTICIPOLETRADO.FECHAMODIFICACION
     *
     * @param fechamodificacion the value for USCGAE.PYS_ANTICIPOLETRADO.FECHAMODIFICACION
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public void setFechamodificacion(Date fechamodificacion) {
        this.fechamodificacion = fechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.PYS_ANTICIPOLETRADO.CTACONTABLE
     *
     * @return the value of USCGAE.PYS_ANTICIPOLETRADO.CTACONTABLE
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public String getCtacontable() {
        return ctacontable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.PYS_ANTICIPOLETRADO.CTACONTABLE
     *
     * @param ctacontable the value for USCGAE.PYS_ANTICIPOLETRADO.CTACONTABLE
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public void setCtacontable(String ctacontable) {
        this.ctacontable = ctacontable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.PYS_ANTICIPOLETRADO.CONTABILIZADO
     *
     * @return the value of USCGAE.PYS_ANTICIPOLETRADO.CONTABILIZADO
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public String getContabilizado() {
        return contabilizado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.PYS_ANTICIPOLETRADO.CONTABILIZADO
     *
     * @param contabilizado the value for USCGAE.PYS_ANTICIPOLETRADO.CONTABILIZADO
     *
     * @mbg.generated Thu Oct 28 12:58:33 CEST 2021
     */
    public void setContabilizado(String contabilizado) {
        this.contabilizado = contabilizado;
    }
}