package org.itcgae.siga.db.entities;

import java.util.Date;

public class ScsTipoencalidad extends ScsTipoencalidadKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.SCS_TIPOENCALIDAD.CODIGO
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    private String codigo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.SCS_TIPOENCALIDAD.DESCRIPCION
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.SCS_TIPOENCALIDAD.FECHAMODIFICACION
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    private Date fechamodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.SCS_TIPOENCALIDAD.USUMODIFICACION
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    private Integer usumodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.SCS_TIPOENCALIDAD.BLOQUEADO
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    private String bloqueado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.SCS_TIPOENCALIDAD.CODIGOEJIS
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    private String codigoejis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USCGAE.SCS_TIPOENCALIDAD.FECHA_BAJA
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    private Date fechaBaja;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.SCS_TIPOENCALIDAD.CODIGO
     *
     * @return the value of USCGAE.SCS_TIPOENCALIDAD.CODIGO
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.SCS_TIPOENCALIDAD.CODIGO
     *
     * @param codigo the value for USCGAE.SCS_TIPOENCALIDAD.CODIGO
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.SCS_TIPOENCALIDAD.DESCRIPCION
     *
     * @return the value of USCGAE.SCS_TIPOENCALIDAD.DESCRIPCION
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.SCS_TIPOENCALIDAD.DESCRIPCION
     *
     * @param descripcion the value for USCGAE.SCS_TIPOENCALIDAD.DESCRIPCION
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.SCS_TIPOENCALIDAD.FECHAMODIFICACION
     *
     * @return the value of USCGAE.SCS_TIPOENCALIDAD.FECHAMODIFICACION
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public Date getFechamodificacion() {
        return fechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.SCS_TIPOENCALIDAD.FECHAMODIFICACION
     *
     * @param fechamodificacion the value for USCGAE.SCS_TIPOENCALIDAD.FECHAMODIFICACION
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public void setFechamodificacion(Date fechamodificacion) {
        this.fechamodificacion = fechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.SCS_TIPOENCALIDAD.USUMODIFICACION
     *
     * @return the value of USCGAE.SCS_TIPOENCALIDAD.USUMODIFICACION
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public Integer getUsumodificacion() {
        return usumodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.SCS_TIPOENCALIDAD.USUMODIFICACION
     *
     * @param usumodificacion the value for USCGAE.SCS_TIPOENCALIDAD.USUMODIFICACION
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public void setUsumodificacion(Integer usumodificacion) {
        this.usumodificacion = usumodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.SCS_TIPOENCALIDAD.BLOQUEADO
     *
     * @return the value of USCGAE.SCS_TIPOENCALIDAD.BLOQUEADO
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public String getBloqueado() {
        return bloqueado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.SCS_TIPOENCALIDAD.BLOQUEADO
     *
     * @param bloqueado the value for USCGAE.SCS_TIPOENCALIDAD.BLOQUEADO
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public void setBloqueado(String bloqueado) {
        this.bloqueado = bloqueado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.SCS_TIPOENCALIDAD.CODIGOEJIS
     *
     * @return the value of USCGAE.SCS_TIPOENCALIDAD.CODIGOEJIS
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public String getCodigoejis() {
        return codigoejis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.SCS_TIPOENCALIDAD.CODIGOEJIS
     *
     * @param codigoejis the value for USCGAE.SCS_TIPOENCALIDAD.CODIGOEJIS
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public void setCodigoejis(String codigoejis) {
        this.codigoejis = codigoejis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USCGAE.SCS_TIPOENCALIDAD.FECHA_BAJA
     *
     * @return the value of USCGAE.SCS_TIPOENCALIDAD.FECHA_BAJA
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public Date getFechaBaja() {
        return fechaBaja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USCGAE.SCS_TIPOENCALIDAD.FECHA_BAJA
     *
     * @param fechaBaja the value for USCGAE.SCS_TIPOENCALIDAD.FECHA_BAJA
     *
     * @mbg.generated Tue Jun 08 14:25:54 CEST 2021
     */
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
}