Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCurso.tarjetaPrecios.importeMaximo','Importe Máximo','0','1',to_date('01/10/19','DD/MM/RR'),'0','19'); 
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCurso.tarjetaPrecios.importeMaximo','Import Màxim','0','2',to_date('01/10/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCurso.tarjetaPrecios.importeMaximo','Importe Máximo#EU','0','3',to_date('01/10/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCurso.tarjetaPrecios.importeMaximo','Importe Máximo#GL','0','4',to_date('01/10/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('maestros.tiposasistencia.tipoGuardia','Tipos de Guardia','0','1',to_date('01/10/19','DD/MM/RR'),'0','19'); 
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('maestros.tiposasistencia.tipoGuardia','Tipus de Guàrdia','0','2',to_date('01/10/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('maestros.tiposasistencia.tipoGuardia','Tipos de Guardia#EU','0','3',to_date('01/10/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('maestros.tiposasistencia.tipoGuardia','Tipos de Guardia#GL','0','4',to_date('01/10/19','DD/MM/RR'),'0','19');


Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('administracion.informes.literal.visibleMovil','Visible Móvil','0','1',to_date('01/10/19','DD/MM/RR'),'0','19'); 
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('administracion.informes.literal.visibleMovil','Visible Mòbil','0','2',to_date('01/10/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('administracion.informes.literal.visibleMovil','Visible Móvil#EU','0','3',to_date('01/10/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('administracion.informes.literal.visibleMovil','Visible Móvil#GL','0','4',to_date('01/10/19','DD/MM/RR'),'0','19');