Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pestana.fichaCliente.alterMutua.oferta','Ofertas','0','1',to_date('16/05/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pestana.fichaCliente.alterMutua.oferta','Ofertes','0','2',to_date('16/05/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pestana.fichaCliente.alterMutua.oferta','Ofertas#EU','0','3',to_date('16/05/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pestana.fichaCliente.alterMutua.oferta','Ofertas#GL','0','4',to_date('16/05/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pestana.fichaCliente.alterMutua.alternativa','Alternativa al RETA','0','1',to_date('16/05/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pestana.fichaCliente.alterMutua.alternativa','Alternativa al RETA','0','2',to_date('16/05/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pestana.fichaCliente.alterMutua.alternativa','Alternativa al RETA#EU','0','3',to_date('16/05/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pestana.fichaCliente.alterMutua.alternativa','Alternativa al RETA#GL','0','4',to_date('16/05/12','DD/MM/RR'),'0','19');
