ALTER TABLE ADM_ROL ADD LETRADO NUMBER(2);

UPDATE ADM_ROL SET LETRADO = '1' WHERE CODIGOEXT IN ('ABO','CNE','INS','CCB');
UPDATE ADM_ROL SET LETRADO = '0' WHERE CODIGOEXT NOT IN ('ABO','CNE','INS','CCB');

COMMIT;