
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.consultaDatosGenerales.literal.comisionesCargos','Comisiones y Cargos','0','1',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.consultaDatosGenerales.literal.comisionesCargos','Comissions i Càrrecs','0','2',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.consultaDatosGenerales.literal.comisionesCargos','Comisiones y Cargos#GL','0','4',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.consultaDatosGenerales.literal.comisionesCargos','Comisiones y Cargos#EU','0','3',to_date('25/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente.sistema','Se han cargado los datos públicos de la persona existente en el sistema','0','1',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente.sistema','S''han carregat les dades públiques de la persona existent en el sistema','0','2',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente.sistema','Se han cargado los datos públicos de la persona existente en el sistema#GL','0','4',to_date('25/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente.sistema','Se han cargado los datos públicos de la persona existente en el sistema#EU','0','3',to_date('25/03/19','DD/MM/RR'),'0','19');