update GEN_TABLAS_MAESTRAS set FLAGBORRADOLOGICO = '1' where IDTABLAMAESTRA = 'SCS_COSTEFIJO'; 
update GEN_TABLAS_MAESTRAS set FLAGBORRADOLOGICO = '1' where IDTABLAMAESTRA = 'SCS_TIPOASISTENCIA'; 
update GEN_TABLAS_MAESTRAS set FLAGBORRADOLOGICO = '1' where IDTABLAMAESTRA = 'SCS_TIPOFUNDAMENTOCALIF'; 
update GEN_TABLAS_MAESTRAS set FLAGBORRADOLOGICO = '1' where IDTABLAMAESTRA = 'SCS_TIPORESOLUCION';  
