Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.numDocumentoExistente','Ya existe un usuario con el mismo NIF / Pasaporte','0','1',to_date('09/06/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.numDocumentoExistente','Ja existeix un usuari amb el mateix NIF / Passaport','0','2',to_date('09/06/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.numDocumentoExistente','Ya existe un usuario con el mismo NIF / Pasaporte#EU','0','3',to_date('09/06/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.numDocumentoExistente','Ya existe un usuario con el mismo NIF / Pasaporte#GL','0','4',to_date('09/06/10','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('busquedaSanciones.tipoFecha.literal','Tipo Fecha','0','1',to_date('18/12/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('busquedaSanciones.tipoFecha.literal','Tipo Fecha#GL','0','4',to_date('18/12/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('busquedaSanciones.tipoFecha.literal','Tipus Data#CA','0','2',to_date('18/12/18','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('busquedaSanciones.tipoFecha.literal','Tipo Fecha#EU','0','3',to_date('18/12/18','DD/MM/RR'),'0','19');
