create or replace FUNCTION F_SIGA_GETINTEGRANTES(P_INSTITUCION IN NUMBER, P_IDPERSONA  IN NUMBER) RETURN VARCHAR2 IS

    V_RESULT          VARCHAR2(2000);

    CURSOR INTEGRANTES IS    
     SELECT         
        CONCAT(PER2.NOMBRE ||' ',CONCAT(DECODE(PER2.APELLIDOS1,'#NA','',PER2.APELLIDOS1) || ' ',PER2.APELLIDOS2)) AS INTEGRANTE
     FROM CEN_NOCOLEGIADO COL 
     LEFT OUTER JOIN CEN_COMPONENTES COM ON (COM.IDPERSONA = COL.IDPERSONA AND COL.IDINSTITUCION = COM.IDINSTITUCION AND COM.FECHABAJA IS NULL) 
     LEFT OUTER JOIN CEN_CLIENTE CLI ON (COM.CEN_CLIENTE_IDPERSONA = CLI.IDPERSONA AND CLI.IDINSTITUCION = COM.IDINSTITUCION ) 
     left outer JOIN cen_persona per2 ON per2.idpersona = com.cen_cliente_idpersona
     WHERE
        COL.idinstitucion = P_INSTITUCION
        AND COL.IDPERSONA = P_IDPERSONA
        AND col.fecha_baja IS NULL
        AND ROWNUM <= 10        ;

BEGIN
    FOR I IN INTEGRANTES LOOP
        IF(V_RESULT IS NULL) THEN
                V_RESULT := I.INTEGRANTE;
        ELSE
                V_RESULT := V_RESULT || '; ' || I.INTEGRANTE;
        END IF;
  END LOOP;

  RETURN(V_RESULT);
END F_SIGA_GETINTEGRANTES;