Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente','Se han cargado los datos públicos de la persona existente en el Censo General','0','1',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente','S''han carregat les dades públiques de la persona que hi ha al Cens General','0','2',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente','Se han cargado los datos públicos de la persona existente en el Censo General#EU','0','3',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente','Se han cargado los datos públicos de la persona existente en el Censo General#GL','0','4',to_date('10/01/04','DD/MM/RR'),'0','3');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.periodicidadPago','Periodicidad de pago','0','1',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.periodicidadPago','Periodicitat de pagament','0','2',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.periodicidadPago','Periodicidad de pago#EU','0','3',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.periodicidadPago','Periodicidad de pago#GL','0','4',to_date('18/01/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.opcionCobertura','Opcion de Cobertura','0','1',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.opcionCobertura','Opció de Cobertura','0','2',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.opcionCobertura','Opcion de Cobertura#EU','0','3',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.opcionCobertura','Opcion de Cobertura#GL','0','4',to_date('18/01/12','DD/MM/RR'),'0','19');
