Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente','Se han cargado los datos públicos de la persona existente en el Censo General','0','1',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente','S''han carregat les dades públiques de la persona que hi ha al Cens General','0','2',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente','Se han cargado los datos públicos de la persona existente en el Censo General#EU','0','3',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.cargaPersonaExistente','Se han cargado los datos públicos de la persona existente en el Censo General#GL','0','4',to_date('10/01/04','DD/MM/RR'),'0','3');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.periodicidadPago','Periodicidad de pago','0','1',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.periodicidadPago','Periodicitat de pagament','0','2',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.periodicidadPago','Periodicidad de pago#EU','0','3',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.periodicidadPago','Periodicidad de pago#GL','0','4',to_date('18/01/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.opcionCobertura','Opcion de Cobertura','0','1',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.opcionCobertura','Opció de Cobertura','0','2',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.opcionCobertura','Opcion de Cobertura#EU','0','3',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.opcionCobertura','Opcion de Cobertura#GL','0','4',to_date('18/01/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.cuotaMensual','Cuota Mensual','0','1',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.cuotaMensual','Quota Mensual','0','2',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.cuotaMensual','Cuota Mensual#EU','0','3',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.cuotaMensual','Cuota Mensual#GL','0','4',to_date('18/01/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.capitalObjetivo','Capital objetivo estimado a los 65 años','0','1',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.capitalObjetivo','Capital objectiu estimat als 65 anys','0','2',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.capitalObjetivo','Capital objetivo estimado a los 65 años#EU','0','3',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.capitalObjetivo','Capital objetivo estimado a los 65 años#GL','0','4',to_date('18/01/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.consultaDatosRegistrales.literal.DatosPoliza','Datos Póliza','0','1',to_date('12/05/08','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.consultaDatosRegistrales.literal.DatosPoliza','Dades Pòlissa','0','2',to_date('12/05/08','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.consultaDatosRegistrales.literal.DatosPoliza','Datos Póliza#EU','0','3',to_date('12/05/08','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.consultaDatosRegistrales.literal.DatosPoliza','Datos Póliza#GL','0','4',to_date('12/05/08','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.beneficiarios','Beneficiarios','0','1',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.beneficiarios','Beneficiaris','0','2',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.beneficiarios','Beneficiarios#EU','0','3',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.beneficiarios','Beneficiarios#GL','0','4',to_date('18/01/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.asistenciaSanitaria','Asistencia Sanitaria','0','1',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.asistenciaSanitaria','Assistència Sanitària','0','2',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.asistenciaSanitaria','Asistencia Sanitaria#EU','0','3',to_date('18/01/12','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.mutualidad.literal.asistenciaSanitaria','Asistencia Sanitaria#GL','0','4',to_date('18/01/12','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.unidadFamiliar','Unidad familiar','0','1',to_date('10/12/05','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.unidadFamiliar','Unitat familiar','0','2',to_date('10/12/05','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.unidadFamiliar','Unidad familiar#EU','0','3',to_date('10/12/05','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.unidadFamiliar','Unidad familiar#GL','0','4',to_date('10/12/05','DD/MM/RR'),'0','19');
