UPDATE AGE_TIPONOTIFICACIONEVENTO
SET DESCRIPCION = 
(SELECT tipoevento.DESCRIPCION 
FROM AGE_TIPOEVENTOS tipoevento 
INNER JOIN GEN_RECURSOS_CATALOGOS REC ON (REC.IDRECURSO = tipoevento.DESCRIPCION AND REC.IDLENGUAJE = '1' and REC.DESCRIPCION like 'Inicio Curso'))
WHERE IDTIPONOTIFICACIONEVENTO = 1;

UPDATE AGE_TIPONOTIFICACIONEVENTO
SET DESCRIPCION = 
(SELECT tipoevento.DESCRIPCION 
FROM AGE_TIPOEVENTOS tipoevento 
INNER JOIN GEN_RECURSOS_CATALOGOS REC ON (REC.IDRECURSO = tipoevento.DESCRIPCION AND REC.IDLENGUAJE = '1' and REC.DESCRIPCION like 'Fin Curso'))
WHERE IDTIPONOTIFICACIONEVENTO = 2;

UPDATE AGE_TIPONOTIFICACIONEVENTO
SET DESCRIPCION = 
(SELECT tipoevento.DESCRIPCION 
FROM AGE_TIPOEVENTOS tipoevento 
INNER JOIN GEN_RECURSOS_CATALOGOS REC ON (REC.IDRECURSO = tipoevento.DESCRIPCION AND REC.IDLENGUAJE = '1' and REC.DESCRIPCION like 'Inicio Inscripción'))
WHERE IDTIPONOTIFICACIONEVENTO = 3;

UPDATE AGE_TIPONOTIFICACIONEVENTO
SET DESCRIPCION = 
(SELECT tipoevento.DESCRIPCION 
FROM AGE_TIPOEVENTOS tipoevento 
INNER JOIN GEN_RECURSOS_CATALOGOS REC ON (REC.IDRECURSO = tipoevento.DESCRIPCION AND REC.IDLENGUAJE = '1' and REC.DESCRIPCION like 'Fin Inscripción'))
WHERE IDTIPONOTIFICACIONEVENTO = 4;

UPDATE AGE_TIPONOTIFICACIONEVENTO
SET DESCRIPCION = 
(SELECT tipoevento.DESCRIPCION 
FROM AGE_TIPOEVENTOS tipoevento 
INNER JOIN GEN_RECURSOS_CATALOGOS REC ON (REC.IDRECURSO = tipoevento.DESCRIPCION AND REC.IDLENGUAJE = '1' and REC.DESCRIPCION like 'Aprobación Inscripción'))
WHERE IDTIPONOTIFICACIONEVENTO = 5;

UPDATE AGE_TIPONOTIFICACIONEVENTO
SET DESCRIPCION = 
(SELECT tipoevento.DESCRIPCION 
FROM AGE_TIPOEVENTOS tipoevento 
INNER JOIN GEN_RECURSOS_CATALOGOS REC ON (REC.IDRECURSO = tipoevento.DESCRIPCION AND REC.IDLENGUAJE = '1' and REC.DESCRIPCION like 'Inscripción Rechazada'))
WHERE IDTIPONOTIFICACIONEVENTO = 6;

UPDATE AGE_TIPONOTIFICACIONEVENTO
SET DESCRIPCION = 
(SELECT tipoevento.DESCRIPCION 
FROM AGE_TIPOEVENTOS tipoevento 
INNER JOIN GEN_RECURSOS_CATALOGOS REC ON (REC.IDRECURSO = tipoevento.DESCRIPCION AND REC.IDLENGUAJE = '1' and REC.DESCRIPCION like 'Sesión'))
WHERE IDTIPONOTIFICACIONEVENTO = 7;
commit;