DECLARE

BEGIN

UPDATE CON_CONSULTA
   SET CON_CONSULTA.IDOBJETIVO = 4
 WHERE CON_CONSULTA.TIPOCONSULTA IN ('I', 'C');

--NOS TIENEN QUE COMUNICAR SI PONEMOS LA F O NO
UPDATE CON_CONSULTA
   SET CON_CONSULTA.IDOBJETIVO = 1
 WHERE CON_CONSULTA.TIPOCONSULTA IN ('E', 'F'); 


UPDATE CON_CONSULTA
   SET CON_CONSULTA.IDOBJETIVO = 3
 WHERE CON_CONSULTA.TIPOCONSULTA IN ('W');


UPDATE CON_CONSULTA
   SET CON_CONSULTA.IDOBJETIVO = 2
 WHERE CON_CONSULTA.TIPOCONSULTA IN ('M');
 
COMMIT;
 
 END;
 