spool AÑADIDA FECHABAJA TURNOS.log
prompt AÑADIDA FECHABAJA TURNOS.log
select to_char(sysdate, 'hh24:mi:ss') as "Inicio" from dual;
prompt .

CREATE TABLE SCS_REQUISITOSGUARDIAS
( IDREQUISITOSGUARDIAS NUMBER(3,0) NOT NULL,
  DESCRIPCION VARCHAR2(100 BYTE) NOT NULL,
  FECHAMODIFICACION DATE NOT NULL , 
    USUMODIFICACION NUMBER(5,0) NOT NULL,
    PRIMARY KEY(IDREQUISITOSGUARDIAS)
);

Insert into SCS_REQUISITOSGUARDIAS (IDREQUISITOSGUARDIAS,DESCRIPCION,FECHAMODIFICACION,USUMODIFICACION) values (0,'Obligatorias',to_date('13/11/19','DD/MM/RR'),'0');
Insert into SCS_REQUISITOSGUARDIAS (IDREQUISITOSGUARDIAS,DESCRIPCION,FECHAMODIFICACION,USUMODIFICACION) values (1,'Todas o ninguna',to_date('13/11/19','DD/MM/RR'),'0');
Insert into SCS_REQUISITOSGUARDIAS (IDREQUISITOSGUARDIAS,DESCRIPCION,FECHAMODIFICACION,USUMODIFICACION) values (2,'A elegir',to_date('13/11/19','DD/MM/RR'),'0');

commit;
prompt .
select to_char(sysdate, 'hh24:mi:ss') as "Fin" from dual;
spool off