spool 09_PROCESOS-Inscripciones.log
prompt 09_PROCESOS-Inscripciones.log
select to_char(sysdate, 'hh24:mi:ss') as "Inicio" from dual;
prompt .

Insert into GEN_PROCESOS 
(IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values 
('99P','JGR','1','Y',SYSDATE,'0','Tarjeta Resumen Inscripciones','JGR_TarjetaResumenInscripciones','96M','10');

Insert into GEN_PROCESOS 
(IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values 
('93P','JGR','1','Y',SYSDATE,'0','Tarjeta Resumen Cola','JGR_TarjetaResumenCola','96M','10');

INSERT INTO ADM_TIPOSACCESO (IDPROCESO,IDPERFIL,FECHAMODIFICACION,USUMODIFICACION,DERECHOACCESO,IDINSTITUCION) 
values ('99P','ADG',SYSDATE,'0','3','2005');

INSERT INTO ADM_TIPOSACCESO (IDPROCESO,IDPERFIL,FECHAMODIFICACION,USUMODIFICACION,DERECHOACCESO,IDINSTITUCION) 
values ('93P','ADG',SYSDATE,'0','3','2005');

commit;
prompt .
select to_char(sysdate, 'hh24:mi:ss') as "Fin" from dual;
spool off