spool 08_PROCESOS-Inscripciones.log
prompt 08_PROCESOS-Inscripciones.log
select to_char(sysdate, 'hh24:mi:ss') as "Inicio" from dual;
prompt .

Insert into GEN_PROCESOS 
(IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values 
('96P','JGR','1','Y',SYSDATE,'0','Tarjeta Letrado','JGR_TarjetaLetrado','96M','10');

Insert into GEN_PROCESOS 
(IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values 
('97P','JGR','1','Y',SYSDATE,'0','Tarjeta Inscripcion','JGR_TarjetaInscripcion','96M','10');

Insert into GEN_PROCESOS 
(IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values 
('98P','JGR','1','Y',SYSDATE,'0','Tarjeta Gestión Inscripciones','JGR_TarjetaGestionInscripciones','96M','10');

INSERT INTO ADM_TIPOSACCESO (IDPROCESO,IDPERFIL,FECHAMODIFICACION,USUMODIFICACION,DERECHOACCESO,IDINSTITUCION) 
values ('96P','ADG',SYSDATE,'0','3','2005');

INSERT INTO ADM_TIPOSACCESO (IDPROCESO,IDPERFIL,FECHAMODIFICACION,USUMODIFICACION,DERECHOACCESO,IDINSTITUCION) 
values ('97P','ADG',SYSDATE,'0','3','2005');

INSERT INTO ADM_TIPOSACCESO (IDPROCESO,IDPERFIL,FECHAMODIFICACION,USUMODIFICACION,DERECHOACCESO,IDINSTITUCION) 
values ('98P','ADG',SYSDATE,'0','3','2005');

commit;
prompt .
select to_char(sysdate, 'hh24:mi:ss') as "Fin" from dual;
spool off