package org.itcgae.siga.db.services.com.providers;

import org.apache.ibatis.jdbc.SQL;

public class ModModeloPlantillaEnviosExtendsSqlProvider {
	
	public String selectPlantillasModelo(String idModelo, Short idInstitucion, String idLenguaje){
		SQL sql = new SQL();
		
		sql.SELECT("PLANTILLA.NOMBRE, PLANTILLA.IDTIPOENVIOS, MODELO.PORDEFECTO, MODELO.FECHABAJA, MODELO.IDINSTITUCION,"
				+ "(SELECT CAT.DESCRIPCION FROM ENV_TIPOENVIOS PLA LEFT JOIN GEN_RECURSOS_CATALOGOS CAT ON CAT.IDRECURSO = PLA.NOMBRE WHERE PLA.IDTIPOENVIOS = PLANTILLA.IDTIPOENVIOS AND CAT.IDLENGUAJE = '"+ idLenguaje +"') AS TIPOENVIO");
		sql.SELECT("PLANTILLA.IDPLANTILLAENVIOS");
		sql.SELECT("MODELO.IDMODELOCOMUNICACION");
		sql.FROM("MOD_MODELO_PLANTILLAENVIO MODELO");
		sql.JOIN("ENV_PLANTILLASENVIOS PLANTILLA ON PLANTILLA.IDPLANTILLAENVIOS = MODELO.IDPLANTILLAENVIOS AND PLANTILLA.IDINSTITUCION = '"+ idInstitucion +"' AND MODELO.IDTIPOENVIOS = PLANTILLA.IDTIPOENVIOS");
		sql.WHERE("MODELO.IDMODELOCOMUNICACION = '" + idModelo +"' AND MODELO.FECHABAJA IS NULL");
		
		return sql.toString();
	}
	
	public String selectPlantillasModeloHIST(String idModelo, Short idInstitucion, String idLenguaje){
		SQL sql = new SQL();
		
		sql.SELECT("PLANTILLA.NOMBRE, PLANTILLA.IDTIPOENVIOS, MODELO.PORDEFECTO, MODELO.FECHABAJA, MODELO.IDINSTITUCION,"
				+ "(SELECT CAT.DESCRIPCION FROM ENV_TIPOENVIOS PLA LEFT JOIN GEN_RECURSOS_CATALOGOS CAT ON CAT.IDRECURSO = PLA.NOMBRE WHERE PLA.IDTIPOENVIOS = PLANTILLA.IDTIPOENVIOS AND CAT.IDLENGUAJE = '"+ idLenguaje +"') AS TIPOENVIO");
		sql.SELECT("PLANTILLA.IDPLANTILLAENVIOS");
		sql.FROM("MOD_MODELO_PLANTILLAENVIO MODELO");
		sql.JOIN("ENV_PLANTILLASENVIOS PLANTILLA ON PLANTILLA.IDPLANTILLAENVIOS = MODELO.IDPLANTILLAENVIOS AND PLANTILLA.IDINSTITUCION = '"+ idInstitucion +"' AND MODELO.IDTIPOENVIOS = PLANTILLA.IDTIPOENVIOS");
		sql.WHERE("MODELO.IDMODELOCOMUNICACION = '" + idModelo +"'");
		
		return sql.toString();
	}

}
