-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2121
--   at:        2018-10-16 10:00:19 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE for_curso (
    idcurso                     NUMBER(10) NOT NULL,
    idinstitucion               NUMBER(4) NOT NULL,
    codigocurso                 VARCHAR2(100),
    nombrecurso                 VARCHAR2(100),
    preciodesde                 NUMBER(10),
    preciohasta                 NUMBER(10),
    fechainscripciondesde       DATE,
    fechainscripcionhasta       DATE,
    fechaimparticiondesde       DATE,
    fechaimparticionhasta       DATE,
    numeroplazas                NUMBER(10),
    idvisibilidadcurso          NUMBER(2) NOT NULL,
    idestadocurso               NUMBER(10) NOT NULL,
    usumodificacion             NUMBER(10),
    fechamodificacion           DATE,
    idtiposervicio              NUMBER(10),
    descripcion                 VARCHAR2(200),
    lugar                       VARCHAR2(200),
    minimoasistencia            NUMBER(10),
    autovalidacioninscripcion   NUMBER(2),
    documentacionadjunta        VARCHAR2(200),
    encuestasatisfaccion        VARCHAR2(200),
    informacionadicional        VARCHAR2(200),
    flagarchivado               NUMBER(2)
);

CREATE INDEX for_curso__idx ON
    for_curso ( idcurso ASC );

ALTER TABLE for_curso ADD CONSTRAINT for_curso_pk PRIMARY KEY ( idcurso );

CREATE TABLE for_estadocurso (
    idestadocurso       NUMBER(2) NOT NULL,
    descripcion         VARCHAR2(100),
    usumodificacion     NUMBER(5),
    fechabaja           DATE,
    fechamodificacion   DATE
);

CREATE INDEX for_estadocurso__idx ON
    for_estadocurso ( idestadocurso ASC );

ALTER TABLE for_estadocurso ADD CONSTRAINT for_estadocurso_pk PRIMARY KEY ( idestadocurso );

CREATE TABLE for_estadoinscripcion (
    idestadoinscripcion   NUMBER(10) NOT NULL,
    descripcion           VARCHAR2(100),
    usumodificacion       NUMBER(10),
    fechamodificacion     DATE,
    fechabaja             DATE
);

ALTER TABLE for_estadoinscripcion ADD CONSTRAINT for_estadoinscripcion_pk PRIMARY KEY ( idestadoinscripcion );

CREATE TABLE for_inscripcion (
    idinscripcion         NUMBER(10) NOT NULL,
    idinstitucion         NUMBER(4) NOT NULL,
    idestadoinscripcion   NUMBER(10) NOT NULL,
    fechasolicitud        DATE,
    calificacion          VARCHAR2(100),
    idpersona             NUMBER(10),
    idcurso               NUMBER(10) NOT NULL
);

ALTER TABLE for_inscripcion ADD CONSTRAINT for_inscripcion_pk PRIMARY KEY ( idinscripcion );

CREATE TABLE for_modopago (
    idmodopago          NUMBER(2) NOT NULL,
    descripcion         VARCHAR2(100),
    usumodificacion     NUMBER(10),
    fechabaja           DATE,
    fechamodificacion   DATE
);

ALTER TABLE for_modopago ADD CONSTRAINT for_modopago_pk PRIMARY KEY ( idmodopago );

CREATE TABLE for_persona_curso (
    idpersona                 NUMBER(10) NOT NULL,
    idcurso                   NUMBER(10) NOT NULL,
    idrol                     NUMBER(2) NOT NULL,
    usumodificacion           NUMBER(10),
    fechamodificacion         DATE,
    idinstitucion             NUMBER(4) NOT NULL,
    idtipocoste               NUMBER(2) NOT NULL,
    tarifa                    NUMBER(10),
    for_roles_idinstitucion   NUMBER(4) NOT NULL
);

ALTER TABLE for_persona_curso ADD CONSTRAINT for_persona_curso_pk PRIMARY KEY ( idpersona,
idcurso );

CREATE TABLE for_roles (
    idrol               NUMBER(2) NOT NULL,
    descripcion         VARCHAR2(100),
    usumodificacion     NUMBER(10),
    fechabaja           DATE,
    fechamodificacion   DATE,
    idinstitucion       NUMBER(4) NOT NULL
);

ALTER TABLE for_roles ADD CONSTRAINT for_roles_pk PRIMARY KEY ( idrol,
idinstitucion );

CREATE TABLE for_temacurso (
    idtemacurso         NUMBER(10) NOT NULL,
    usumodificacion     NUMBER(10),
    idinstitucion       NUMBER(4) ,
    descripcion         VARCHAR2(100),
    fechamodificacion   DATE,
    fechabaja           DATE
);

CREATE INDEX for_temacurso__idx ON
    for_temacurso ( idtemacurso ASC );

ALTER TABLE for_temacurso ADD CONSTRAINT for_temacurso_pk PRIMARY KEY ( idtemacurso );

CREATE TABLE for_temacurso_curso (
    idcurso             NUMBER(10) NOT NULL,
    idtemacurso         NUMBER(10) NOT NULL,
    usumodificacion     NUMBER(10),
    fechamodificacion   DATE,
    idinstitucion       NUMBER(4) NOT NULL,
    fechabaja           DATE
);

CREATE INDEX for_temacurso_curso__idx ON
    for_temacurso_curso (
        idcurso
    ASC,
        idtemacurso
    ASC,
        idinstitucion
    ASC );

ALTER TABLE for_temacurso_curso ADD CONSTRAINT for_temacurso_curso_pk PRIMARY KEY ( idcurso,
idtemacurso );

CREATE TABLE for_tipocoste (
    idtipocoste         NUMBER(2) NOT NULL,
    descripcion         VARCHAR2(100),
    usumodificacion     NUMBER(10),
    fechabaja           DATE,
    fechamodificacion   DATE
);

ALTER TABLE for_tipocoste ADD CONSTRAINT for_tipocoste_pk PRIMARY KEY ( idtipocoste );

CREATE TABLE for_visibilidadcurso (
    idvisibilidadcurso   NUMBER(2) NOT NULL,
    descripcion          VARCHAR2(100),
    usumodificacion      NUMBER(5),
    fechabaja            DATE,
    fechamodificacion    DATE
);

CREATE INDEX for_visibilidadcurso__idx ON
    for_visibilidadcurso ( idvisibilidadcurso ASC );

ALTER TABLE for_visibilidadcurso ADD CONSTRAINT for_visibilidad_pk PRIMARY KEY ( idvisibilidadcurso );

ALTER TABLE for_curso
    ADD CONSTRAINT for_curso_for_estadocurso_fk FOREIGN KEY ( idestadocurso )
        REFERENCES for_estadocurso ( idestadocurso );

ALTER TABLE for_curso
    ADD CONSTRAINT for_curso_for_visibdcurso_fk FOREIGN KEY ( idvisibilidadcurso )
        REFERENCES for_visibilidadcurso ( idvisibilidadcurso );

ALTER TABLE for_inscripcion
    ADD CONSTRAINT for_insc_for_estinscripcio_fk FOREIGN KEY ( idestadoinscripcion )
        REFERENCES for_estadoinscripcion ( idestadoinscripcion );

ALTER TABLE for_inscripcion
    ADD CONSTRAINT for_inscripcion_for_curso_fk FOREIGN KEY ( idcurso )
        REFERENCES for_curso ( idcurso );

ALTER TABLE for_persona_curso
    ADD CONSTRAINT for_per_curso_for_curso_fk FOREIGN KEY ( idcurso )
        REFERENCES for_curso ( idcurso );

ALTER TABLE for_persona_curso
    ADD CONSTRAINT for_per_curso_for_roles_fk FOREIGN KEY ( idrol,
    for_roles_idinstitucion )
        REFERENCES for_roles ( idrol,
        idinstitucion );

ALTER TABLE for_persona_curso
    ADD CONSTRAINT for_per_curso_for_tpcoste_fk FOREIGN KEY ( idtipocoste )
        REFERENCES for_tipocoste ( idtipocoste );

ALTER TABLE for_temacurso_curso
    ADD CONSTRAINT for_temacu_curso_for_cur_fk FOREIGN KEY ( idcurso )
        REFERENCES for_curso ( idcurso );

ALTER TABLE for_temacurso_curso
    ADD CONSTRAINT for_temacu_curso_for_tem_fk FOREIGN KEY ( idtemacurso )
        REFERENCES for_temacurso ( idtemacurso );


        
CREATE SEQUENCE  "USCGAE"."SEQ_FORCURSO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  CYCLE ;
CREATE SEQUENCE  "USCGAE"."SEQ_FORTEMACURSOCURSO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  CYCLE ;
CREATE SEQUENCE  "USCGAE"."SEQ_FORPERSONACURSO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  CYCLE ;
CREATE SEQUENCE  "USCGAE"."SEQ_FORINSCRIPCION"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  CYCLE ;
CREATE SEQUENCE  "USCGAE"."SEQ_FORTEMACURSO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  CYCLE ;
        
commit;