  CREATE TABLE "USCGAE"."CEN_REG_MERCANTIL" 
   (	"ID_DATOS_REG" NUMBER(10,0) NOT NULL ENABLE, 
	"NUM_REGISTRO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IDENTIFICACION_REG" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FECHA_INSCRIPCION" DATE NOT NULL ENABLE, 
	"FECHA_CANCELACION" DATE, 
	"FECHAMODIFICACION" DATE, 
	"USUMODIFICACION" NUMBER(5,0), 
	 CONSTRAINT "PK_REG_MERCANTIL" PRIMARY KEY ("ID_DATOS_REG")
	 
	 TABLESPACE "TS_SIGA" ;
	 
COMMENT ON TABLE "USCGAE"."CEN_REG_MERCANTIL"  IS 'Esta tabla sirve para almacenar los datos del registro mercantil de la sociedad';