
Insert into GEN_PROCESOS (IDPROCESO,IDMODULO,TRAZA,TARGET,FECHAMODIFICACION,USUMODIFICACION,DESCRIPCION,TRANSACCION,IDPARENT,NIVEL) values ('999','GEN','1','Y',to_date('07/05/2018','DD/MM/RRRR'),'0','Desplegar Rueda Configuración',null,'0','10');
