Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.masInfo','Mas información','0','1',to_date('09/06/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.masInfo','Més informació','0','2',to_date('09/06/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.masInfo','Mas información#EU','0','3',to_date('09/06/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('gratuita.personaJG.literal.masInfo','Mas información#GL','0','4',to_date('09/06/10','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.solicitudIncorporacion.literal.seUsaDniIntroducido','Se han cargado los datos del usuario con el número de identificación que ha introducido','0','1',to_date('09/06/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.solicitudIncorporacion.literal.seUsaDniIntroducido','S''han carregat les dades de l''usuari amb el número d''identificació que ha introduït','0','2',to_date('09/06/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.solicitudIncorporacion.literal.seUsaDniIntroducido','Se han cargado los datos del usuario con el número de identificación que ha introducido#EU','0','3',to_date('09/06/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.solicitudIncorporacion.literal.seUsaDniIntroducido','Se han cargado los datos del usuario con el número de identificación que ha introducido#GL','0','4',to_date('09/06/10','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.resultadoDuplicados.numeroColegiadoUtilizado','Número de colegiado ya en uso','0','1',to_date('15/12/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.resultadoDuplicados.numeroColegiadoUtilizado','Número de col·legiat ja en ús','0','2',to_date('15/12/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.resultadoDuplicados.numeroColegiadoUtilizado','Número de colegiado ya en uso#EU','0','3',to_date('15/12/10','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.resultadoDuplicados.numeroColegiadoUtilizado','Número de colegiado ya en uso#GL','0','4',to_date('15/12/10','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.tipoIdentificacion','Tipo Identificación','0','1',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.tipoIdentificacion','Tipus Identificació','0','2',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.tipoIdentificacion','Tipo Identificación#EU','0','3',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.tipoIdentificacion','Tipo Identificación#GL','0','4',to_date('10/01/04','DD/MM/RR'),'0','3');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.naturalDe','Natural de','0','1',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.naturalDe','Natural de','0','2',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.naturalDe','Natural de#EU','0','3',to_date('10/01/04','DD/MM/RR'),'0','3');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('censo.SolicitudIncorporacion.literal.naturalDe','Natural de#GL','0','4',to_date('10/01/04','DD/MM/RR'),'0','3');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pys.gestionSolicitudes.literal.nCuenta','Nº Cuenta','0','1',to_date('10/03/04','DD/MM/RR'),'0','15');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pys.gestionSolicitudes.literal.nCuenta','Núm. Compte','0','2',to_date('10/03/04','DD/MM/RR'),'0','15');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pys.gestionSolicitudes.literal.nCuenta','Nº Cuenta#EU','0','3',to_date('10/03/04','DD/MM/RR'),'0','15');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('pys.gestionSolicitudes.literal.nCuenta','Nº Cuenta#GL','0','4',to_date('10/03/04','DD/MM/RR'),'0','15');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('facturacion.cuentasBancarias.uso','Uso','0','1',to_date('12/06/13','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('facturacion.cuentasBancarias.uso','Ús','0','2',to_date('12/06/13','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('facturacion.cuentasBancarias.uso','Uso#EU','0','3',to_date('12/06/13','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('facturacion.cuentasBancarias.uso','Uso#GL','0','4',to_date('12/06/13','DD/MM/RR'),'0','19');
