Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaGenerales.partidoJudicial','Partido Judicial','0','1',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaGenerales.partidoJudicial','Partit Judicial','0','2',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaGenerales.partidoJudicial','Partido Judicial#EU','0','3',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaGenerales.partidoJudicial','Partido Judicial#GL','0','4',to_date('08/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numNotificaciones','Nº Notificaciones','0','1',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numNotificaciones','Nº Notificacions','0','2',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numNotificaciones','Nº Notificaciones#EU','0','3',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numNotificaciones','Nº Notificaciones#GL','0','4',to_date('08/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numFormadores','Nº Formadores','0','1',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numFormadores','Nº Formadors','0','2',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numFormadores','Nº Formadores#EU','0','3',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numFormadores','Nº Formadores#GL','0','4',to_date('08/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numAsistentes','Nº Asistentes','0','1',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numAsistentes','Nº Assistents','0','2',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numAsistentes','Nº Asistentes#EU','0','3',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('agenda.fichaEvento.tarjetaNotificaciones.resumen.numAsistentes','Nº Asistentes#GL','0','4',to_date('08/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.datosGenerales.resumen.periodoInscripcion','Período de Inscripción','0','1',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.datosGenerales.resumen.periodoInscripcion','Període d''inscripció','0','2',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.datosGenerales.resumen.periodoInscripcion','Período de Inscripción#EU','0','3',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.datosGenerales.resumen.periodoInscripcion','Período de Inscripción#GL','0','4',to_date('08/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.datosGenerales.resumen.periodoImparticion','Período de Impartición','0','1',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.datosGenerales.resumen.periodoImparticion','Període d''impartició','0','2',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.datosGenerales.resumen.periodoImparticion','Período de Impartición#EU','0','3',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.datosGenerales.resumen.periodoImparticion','Período de Impartición#GL','0','4',to_date('08/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaPrecios.resumen.numRegistros','Nº Registros','0','1',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaPrecios.resumen.numRegistros','Nº Registres','0','2',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaPrecios.resumen.numRegistros','Nº Registros#EU','0','3',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaPrecios.resumen.numRegistros','Nº Registros#GL','0','4',to_date('08/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaCertificados.resumen.numCertificados','Nº Certificados','0','1',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaCertificados.resumen.numCertificados','Nº Certificats','0','2',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaCertificados.resumen.numCertificados','Nº Certificados#EU','0','3',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaCertificados.resumen.numCertificados','Nº Certificados#GL','0','4',to_date('08/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaSesiones.resumen.numSesiones','Nº Sesiones','0','1',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaSesiones.resumen.numSesiones','Nº Sessions','0','2',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaSesiones.resumen.numSesiones','Nº Sesiones#EU','0','3',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaSesiones.resumen.numSesiones','Nº Sesiones#GL','0','4',to_date('08/03/19','DD/MM/RR'),'0','19');

Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaCargasMasivas.resumen.numCargas','Nº Cargas','0','1',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaCargasMasivas.resumen.numCargas','Nº Càrregues','0','2',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaCargasMasivas.resumen.numCargas','Nº Cargas#EU','0','3',to_date('08/03/19','DD/MM/RR'),'0','19');
Insert into GEN_DICCIONARIO (IDRECURSO,DESCRIPCION,ERROR,IDLENGUAJE,FECHAMODIFICACION,USUMODIFICACION,IDPROPIEDAD) values ('formacion.fichaCursos.tarjetaCargasMasivas.resumen.numCargas','Nº Cargas#GL','0','4',to_date('08/03/19','DD/MM/RR'),'0','19');