create public synonym ADM_CONFIG for uscgae.ADM_CONFIG;
create public synonym ADM_CONFIG_PK for uscgae.ADM_CONFIG_PK;
create public synonym AZU_PRUEBA for uscgae.AZU_PRUEBA;
create public synonym CARGAS_WS for uscgae.CARGAS_WS;
create public synonym CARGAS_WS_PAGINA for uscgae.CARGAS_WS_PAGINA;
create public synonym CFG_PARAM_COLEGIO_IDX for uscgae.CFG_PARAM_COLEGIO_IDX;
create public synonym CFG_PARAM_COLEGIOS for uscgae.CFG_PARAM_COLEGIOS;
create public synonym CMN_DATOS_XML for uscgae.CMN_DATOS_XML;
create public synonym GEN_DICCIONARIO for uscgae.GEN_DICCIONARIO;
create public synonym PK_CARGAS_WS_IDX for uscgae.PK_CARGAS_WS_IDX;
create public synonym PK_CARGAS_WS_PAG_IDX for uscgae.PK_CARGAS_WS_PAG_IDX;
create public synonym PK_CMN_DATOS_XML for uscgae.PK_CMN_DATOS_XML;
create public synonym PK_GEN_DICCIONARIO for uscgae.PK_GEN_DICCIONARIO;
create public synonym SI_GEN_DICCIONARIO_IDLENGUAJE for uscgae.SI_GEN_DICCIONARIO_IDLENGUAJE;
create public synonym SI_GEN_DICCIONARIO_IDPROPIEDAD for uscgae.SI_GEN_DICCIONARIO_IDPROPIEDAD;
create public synonym SI_IDRECURSO_DICCIONARIO_UNICO for uscgae.SI_IDRECURSO_DICCIONARIO_UNICO;

create or replace public synonym BORRAME_RESOLUCION_2003 for uscgae.BORRAME_RESOLUCION_2003;
create or replace public synonym F_COMUNICACIONES_EJG_2003 for uscgae.F_COMUNICACIONES_EJG_2003;
create or replace public synonym F_CON_GETAITOR for uscgae.F_CON_GETAITOR;
create or replace public synonym F_DIRECCION_PERSONAJG for uscgae.F_DIRECCION_PERSONAJG;
create or replace public synonym F_GETCABECERAGUARDIAS2 for uscgae.F_GETCABECERAGUARDIAS2;
create or replace public synonym F_GETCOMPONENTES for uscgae.F_GETCOMPONENTES;
create or replace public synonym F_GETCOMPONENTES_COLEGIADOS for uscgae.F_GETCOMPONENTES_COLEGIADOS;
create or replace public synonym F_GETGUARDIASINSCRITO for uscgae.F_GETGUARDIASINSCRITO;
create or replace public synonym F_GETNOMBREPARTIDOSTURNO for uscgae.F_GETNOMBREPARTIDOSTURNO;
create or replace public synonym F_GET_PRETENSION_DESIGNA for uscgae.F_GET_PRETENSION_DESIGNA;
create or replace public synonym F_GET_TURNOASISTENCIA for uscgae.F_GET_TURNOASISTENCIA;
create or replace public synonym F_GETTURNOSINSCRITO for uscgae.F_GETTURNOSINSCRITO;
create or replace public synonym F_JM_COMPRUEBA_GUARDIAS for uscgae.F_JM_COMPRUEBA_GUARDIAS;
create or replace public synonym F_JM_COMPRUEBA_GUARDIAS_2003 for uscgae.F_JM_COMPRUEBA_GUARDIAS_2003;
create or replace public synonym F_SIGA_ACTIVIDADES_SOCIEDAD for uscgae.F_SIGA_ACTIVIDADES_SOCIEDAD;
create or replace public synonym F_SIGA_ASUNTOASOCIADO_MV for uscgae.F_SIGA_ASUNTOASOCIADO_MV;
create or replace public synonym F_SIGA_ASUNTOORIGEN_MV for uscgae.F_SIGA_ASUNTOORIGEN_MV;
create or replace public synonym F_SIGA_CAT_NUMEJG for uscgae.F_SIGA_CAT_NUMEJG;
create or replace public synonym F_SIGA_CAT_NUMEJG_OFI for uscgae.F_SIGA_CAT_NUMEJG_OFI;
create or replace public synonym F_SIGA_GETABREVTURNO for uscgae.F_SIGA_GETABREVTURNO;
create or replace public synonym F_SIGA_GETANIONUMEROCAJ for uscgae.F_SIGA_GETANIONUMEROCAJ;
create or replace public synonym F_SIGA_GETCODEXT_ECIVIL for uscgae.F_SIGA_GETCODEXT_ECIVIL;
create or replace public synonym F_SIGA_GETCODIDIOMA for uscgae.F_SIGA_GETCODIDIOMA;
create or replace public synonym F_SIGA_GETDELITOS for uscgae.F_SIGA_GETDELITOS;
create or replace public synonym F_SIGA_GETDELITOS_ASISTENCIA for uscgae.F_SIGA_GETDELITOS_ASISTENCIA;
create or replace public synonym F_SIGA_GETDELITOS_DESIGNA for uscgae.F_SIGA_GETDELITOS_DESIGNA;
create or replace public synonym F_SIGA_GETDELITOS_EJG for uscgae.F_SIGA_GETDELITOS_EJG;
create or replace public synonym F_SIGA_GET_IDULTIMOESTADOCAJG for uscgae.F_SIGA_GET_IDULTIMOESTADOCAJG;
create or replace public synonym F_SIGA_GETJURISDICCION for uscgae.F_SIGA_GETJURISDICCION;
create or replace public synonym F_SIGA_GETNOMBREGUARDIA for uscgae.F_SIGA_GETNOMBREGUARDIA;
create or replace public synonym F_SIGA_GETNOMBRETURNO for uscgae.F_SIGA_GETNOMBRETURNO;
create or replace public synonym F_SIGA_GETNOMBREUSUINSTIT for uscgae.F_SIGA_GETNOMBREUSUINSTIT;
create or replace public synonym F_SIGA_GETNUMEROANIOCAJ for uscgae.F_SIGA_GETNUMEROANIOCAJ;
create or replace public synonym F_SIGA_GETPAIS for uscgae.F_SIGA_GETPAIS;
create or replace public synonym F_SIGA_GETPARAMETRO for uscgae.F_SIGA_GETPARAMETRO;
create or replace public synonym F_SIGA_GETPRIMDELITOASISTENCIA for uscgae.F_SIGA_GETPRIMDELITOASISTENCIA;
create or replace public synonym F_SIGA_GETRATIFICACION for uscgae.F_SIGA_GETRATIFICACION;
create or replace public synonym F_SIGA_GETTURNOS_INSCRITO for uscgae.F_SIGA_GETTURNOS_INSCRITO;
create or replace public synonym F_SIGA_GET_ULTIMOESTADOEJG for uscgae.F_SIGA_GET_ULTIMOESTADOEJG;
create or replace public synonym F_SIGA_NOMBRE_PARTIDO for uscgae.F_SIGA_NOMBRE_PARTIDO;
create or replace public synonym F_SIGA_PERTENECEGRUPOFIJO for uscgae.F_SIGA_PERTENECEGRUPOFIJO;
create or replace public synonym F_2083_GETDESIGNA_EJG for uscgae.F_2083_GETDESIGNA_EJG;
create or replace public synonym I2018_GETTURNOSINSCRITO for uscgae.I2018_GETTURNOSINSCRITO;
create or replace public synonym PROC_ACT_SOCIEDADJURIDICA for uscgae.PROC_ACT_SOCIEDADJURIDICA;
create or replace public synonym PROC_ACTUALIZARGENPARAMETROS for uscgae.PROC_ACTUALIZARGENPARAMETROS;
create or replace public synonym PROC_DESIGNA_PROCURADOR_2010 for uscgae.PROC_DESIGNA_PROCURADOR_2010;
create or replace public synonym PROC_DESIGNA_PROCURADOR_2035 for uscgae.PROC_DESIGNA_PROCURADOR_2035;
create or replace public synonym PROC_DESIGNA_PROCURADOR_2083 for uscgae.PROC_DESIGNA_PROCURADOR_2083;
create or replace public synonym PROC_OBTENERCODIGODESIGNA for uscgae.PROC_OBTENERCODIGODESIGNA;
create or replace public synonym PROC_RESOLUCION_2003 for uscgae.PROC_RESOLUCION_2003;
create or replace public synonym PROC_SIGA_RESOL_2050 for uscgae.PROC_SIGA_RESOL_2050;
create or replace public synonym V_BADAJOZ_CONFIRMING for uscgae.V_BADAJOZ_CONFIRMING;
create or replace public synonym V_BADAJOZ_LISTADOFACT_GUARDIAS for uscgae.V_BADAJOZ_LISTADOFACT_GUARDIAS;
create or replace public synonym V_GIJON_INFORMEFACT_GUARDIAS for uscgae.V_GIJON_INFORMEFACT_GUARDIAS;
create or replace public synonym V_GIJON_INFORMEFACT_GUA_2010 for uscgae.V_GIJON_INFORMEFACT_GUA_2010;
create or replace public synonym V_GIJON_LISTADOFACT_GUARDIAS for uscgae.V_GIJON_LISTADOFACT_GUARDIAS;
create or replace public synonym V_GIJON_LISTADOFACT_TURNOS for uscgae.V_GIJON_LISTADOFACT_TURNOS;
create or replace public synonym V_SIGA_CAJG_2011 for uscgae.V_SIGA_CAJG_2011;
create or replace public synonym V_SIGA_CAT_CAJG for uscgae.V_SIGA_CAT_CAJG;
create or replace public synonym V_SIGA_CAT_SJCS_FAC_ASI for uscgae.V_SIGA_CAT_SJCS_FAC_ASI;
create or replace public synonym V_SIGA_CAT_SJCS_FAC_OFI for uscgae.V_SIGA_CAT_SJCS_FAC_OFI;
create or replace public synonym V_SIGA_JUST_GUARDIAS_CONSELL for uscgae.V_SIGA_JUST_GUARDIAS_CONSELL;
create or replace public synonym V_WS_2064_EJG for uscgae.V_WS_2064_EJG;
create or replace public synonym V_2005_GUARDIAS_NORMALES for uscgae.V_2005_GUARDIAS_NORMALES;
create or replace public synonym V_2014_GUARDIAS_NORMALES for uscgae.V_2014_GUARDIAS_NORMALES;
create or replace public synonym V_2023_GUARDIAS_NORMALES for uscgae.V_2023_GUARDIAS_NORMALES;
create or replace public synonym V_2051_GUARDIAS_NORMALES for uscgae.V_2051_GUARDIAS_NORMALES;
create or replace public synonym V_2083_GUIAJUDICIAL for uscgae.V_2083_GUIAJUDICIAL;