Insert into GEN_MENU (IDMENU,ORDEN,TAGWIDTH,IDPARENT,FECHAMODIFICACION,USUMODIFICACION,URI_IMAGEN,IDRECURSO,GEN_MENU_IDMENU,IDPROCESO,IDLENGUAJE,PATH,FECHA_BAJA,IDCLASS) values ('99C','31000','100',' ',to_date('22/01/04','DD/MM/RR'),'0',null,'menu.configuracion',null,'99C','1',' ',null,'config');

commit;