GRANT SELECT ON USCGAE.ADM_CONFIG TO ROLE_SIGA_R;
GRANT DELETE, INSERT, SELECT, UPDATE ON USCGAE.ADM_CONFIG TO ROLE_SIGA;

GRANT SELECT ON USCGAE.GEN_DICCIONARIO TO ROLE_SIGA_R;
GRANT DELETE, INSERT, SELECT, UPDATE ON USCGAE.GEN_DICCIONARIO TO ROLE_SIGA;

GRANT SELECT ON USCGAE.GEN_DICCIONARIO TO ROLE_SIGA_R;
GRANT DELETE, INSERT, SELECT, UPDATE ON USCGAE.GEN_DICCIONARIO TO ROLE_SIGA;

GRANT EXECUTE ON USCGAE.F_SIGA_PERFILES_USUARIO TO ROLE_SIGA_R;
GRANT EXECUTE ON USCGAE.F_SIGA_PERFILES_USUARIO TO ROLE_SIGA;

GRANT SELECT ON USCGAE.cmn_datos_xml TO ROLE_SIGA_R;
GRANT DELETE, INSERT, SELECT, UPDATE ON USCGAE.cmn_datos_xml TO ROLE_SIGA;

GRANT SELECT ON USCGAE.cargas_ws TO ROLE_SIGA_R;
GRANT DELETE, INSERT, SELECT, UPDATE ON USCGAE.cargas_ws TO ROLE_SIGA;

GRANT SELECT ON USCGAE.cargas_ws_pagina TO ROLE_SIGA_R;
GRANT DELETE, INSERT, SELECT, UPDATE ON USCGAE.cargas_ws_pagina TO ROLE_SIGA;

GRANT SELECT ON USCGAE.cfg_param_colegios TO ROLE_SIGA_R;
GRANT DELETE, INSERT, SELECT, UPDATE ON USCGAE.cfg_param_colegios TO ROLE_SIGA;

GRANT SELECT ON USCGAE.cfg_param_colegios TO ROLE_SIGA_R;
GRANT DELETE, INSERT, SELECT, UPDATE ON USCGAE.cfg_param_colegios TO ROLE_SIGA;

